### PR TITLE
Remove FTB modpack support

### PR DESCRIPTION
**Pull request by Scrumplex**
We have been contacted by Feed the Beast to drop support for the FTB modpack browser from Prism Launcher.

Please keep discussions civil. This decision is not specifically targeted towards Prism Launcher.

### CODE REVIEW

**Review by DioEgizio — APPROVED** [review]
Rip FTB

**Comment by uriesk** [comment]
one of the reasons why i switched back to PolyMc

**Comment by pedr69** [comment]
this seems like a great feature!
the users are gonna love this

**Review by flowln — APPROVED** [review]

**Review by txtsd — APPROVED** [review]
😕

**Comment by AutumnalModding** [comment]
:popcorn: Get your popcorn here, folks.
Hopefully this'll be the end of this launcher...!
And then everyone can switch back to using PolyMC, as all should be.

**Comment by LuciusV** [comment]
And why you just don't ignore them? Their behaviour should not be supported by agreeing with their absurd requests.

**Comment by hadeedsarfaraz** [comment]
I do believe that they are the bigger entity here and have more power. Overwolf has Money, and wants the ad revenue. Even if it is for a worse launcher, any third party launcher has no choice but to do this.

**Comment by ghost** [comment]
FTB bad😕

**Comment by mcg-anon** [comment]
Can you remove curseforge too please?
They made it obvious that they don't want you.

**Comment by TheAwesome98-Real** [comment]
> Can you remove curseforge too please? They made it obvious that they don't want you.

modrinth wipes

**Comment by AutumnalModding** [comment]
"marked as offtopic"
can't silence the truth lmao

**Comment by Scrumplex** [comment]
After feedback from some community members, I can add that there is more nuance to the story than I initially thought.

On a legal basis, we probably don't have to follow the request of Slowpoke here, as there are no ToS, EULA or DRM we are breaking here. The API is publicly accessible and even has an official public documentation.[[1]] Apparently the API we were using was initially operated by CreeperHost as a general purpose modpack API, though it is unclear if that's still the case.

I think if we didn't comply we would just end up being blocked by the API, and as we want to avoid drama where possible we thought we should just comply.

In any case, here are reasons why dropping support for FTB is not as bad as it seems at first:
- FTB also publishes their modpacks to CurseForge
- Prism Launcher tries to promote free and open source software where possible and Modrinth is the platform of choice for this goal
- Code was untouched for a long time
- (more?, comment below)

Some downsides of this change:
- Some older FTB modpacks are now inaccessible
- (more?, comment below)

Of course, in an ideal world this didn't need to happen.

[1]: https://www.reddit.com/r/feedthebeast/comments/ftqtfj/new_ftb_launcher_released_115_pack_ftb_omnia/fmcbal1/?context=3

**Comment by DioEgizio** [comment]
> FTB also publishes their modpacks to CurseForge

Tbh they stopped publishing modpacks there since like 1.12 times. I also want to add that the ftb api is very buggy and highly unstable, it broke a lot of times, so removing even if we kept ftb they would break the API

**Comment by IThundxr** [comment]
https://github.com/PrismLauncher/prismlauncher.org/pull/262 blog post associated with this PR.

**Comment by hisashiburii** [comment]
rip ftb

**Comment by xAffan** [comment]
Didn't curseforge also ask you to remove their support? Why the double standards.

**Comment by IThundxr** [comment]
> Didn't curseforge also ask you to remove their support? Why the double standards.

Nope they haven’t if they wanted us to do that they would have revoked our api key

**Comment by xAffan** [comment]
> > Didn't curseforge also ask you to remove their support? Why the double standards.
> 
> Nope they haven’t if they wanted us to do that they would have revoked our api key

Since they said that some launchers making profit off of them was the main reason for their disallowance, is it possible that you can try to get an exception? Since prism is no profit foss open source

**Comment by IThundxr** [comment]
> > > Didn't curseforge also ask you to remove their support? Why the double standards.
> 
> > 
> 
> > Nope they haven’t if they wanted us to do that they would have revoked our api key
> 
> 
> 
> Since they said that some launchers making profit off of them was the main reason for their disallowance, is it possible that you can try to get an exception? Since prism is no profit foss open source

I can't say much but we are talking about this with them but can't say if it will come back soon cause it's a lot of legal stuff

**Comment by PanoptesDreams** [comment]
IMO: FTB has been in the toilet for a long while.

Dropping support allows devs to focus on important features like the ones coming with the 7.0 release, which were a nice surprise for someone like me who doesn't read source code like the news.

Keep up the amazing work!


EDIT: After reading the talk chain I understand the reasoning from a monetary standpoint and have no objection to FTB trying to protect their IP.

Whoever these 3rd/4th party 'devs' are stealing work to actively profit off of, I say this with the sincerest heart, F*** you.
(Read [this](https://prismlauncher.org/news/ftb-removal/) if you don't understand)

**Comment by glektarssza** [comment]
Super unfortunate but understandable that FTB needs to be seen protecting their IP if they want any ability to enforce their trademarks in the cases that really matter. That's how the trademark system works. Use it or lose it.

Hopefully some alternative can be found to allow people to import FTB packs into Prism Launcher from, say, the FTB App once installed through there.

Thanks for the blog post. It really helped with the transparency behind this decision as well as understanding where FTB is coming from on this issue.

**Comment by PanoptesDreams** [comment]
> Hopefully some alternative can be found to allow people to import FTB packs into Prism Launcher from, say, the FTB App once installed through there.

I think there was mention somewhere that later down the line it can be replaced by a simple pack importer. No different from importing a zip. it just can't tap into the Curseforge API.

**Comment by IThundxr** [comment]
> > Hopefully some alternative can be found to allow people to import FTB packs into Prism Launcher from, say, the FTB App once installed through there.
> 
> 
> 
> I think there was mention somewhere that later down the line it can be replaced by a simple pack importer. No different from importing a zip. it just can't tap into the Curseforge API.
> 
> 

Using the curseforge api is fine it's just ftb didn't want launchers to list their packs inside the launchers

**Comment by deacfb** [comment]
so how much money did overwolf give to ftb?
no one wants to use the bloatware by overwolf, it's at least 10x slower when downloading a modpack

**Comment by 4rz0** [comment]
I suggest changing the line in the [About-section of the webpage](https://prismlauncher.org/about/) that says it is possible to `"Install modpacks from many platforms such as [...] FTB [...]"` accordingly.
As it is not possible anymore to install directly from the platform.

**Comment by Shados** [comment]
> FTB also publishes their modpacks to CurseForge

Do they still *actually* do that? The last update to one of their modpacks on CF was in 2021, AFAICT, while many of their packs have received further updates on their own site.

**Comment by deacfb** [comment]
> > FTB also publishes their modpacks to CurseForge
> 
> Do they still _actually_ do that? The last update to one of their modpacks on CF was in 2021, AFAICT, while many of their packs have received further updates on their own site.

no, ftb modpacks on curseforge hasn't been updated for years

**Comment by furtabs** [comment]
FTB will probably be contacting you shortly regarding this stance as their policy has recently changed.

**Comment by Trial97** [comment]
> FTB will probably be contacting you shortly regarding this stance as their policy has recently changed.

Do you have any sources for that? Or just wait and hope for the best?

**Comment by glkdrlgkrlzflnjkgh** [comment]
Its quite absurd that prism launcher having FTB support apparently "causes financial loss" to FTB, even though its a way to access FTB without ads. probably corporate greed? i dont know. potentially.

**Pull request merged**
