### PR TITLE
Remove old updater code

### PR DESCRIPTION
**Pull request by Scrumplex**

### CODE REVIEW

**Comment by Scrumplex** [comment]
I don't know if this works on macOS :eyes:

**Review by flowln — APPROVED** [review]
LGTM!

you should probably make some way of testing if it works (maybe a release on your branch, and make a temporary branch based on this with a different URL for the updater?) on macOS, and ping the test subjects for it :>

**Comment by DioEgizio** [comment]
> I don't know if this works on macOS 👀

works fine, even tried updating and everything worked

**Comment by Scrumplex** [comment]
Moving this to 7.0 as it's fairly unimportant

**Comment by ghost** [comment]
Why is this unimportant? the old updater code needs to be exterminated asap it's one of the most annyoing things i've ever seen in my life

**Review by bvemmm — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Pull request merged**
