### PR TITLE
Update BUILD.md, add macOS instructions

### PR DESCRIPTION
**Pull request by whitebear60**
Added macOS building instructions, please correct me if I'm wrong in some cases.

Signed-off-by: Mihail Yaremenko <m50421@outlook.com>

### CODE REVIEW

**Comment by DioEgizio** [comment]
this is kinda redundant with https://prismlauncher.org/wiki/development/build-instructions/#macos

**Comment by whitebear60** [comment]
Actually, as I stated previously in Discord, this issue started with build issues with website instructions, so I decided to post here the command arguments that worked for me (probably the biggest difference is absence of the `build` folder and starting the build directly in the PrismLauncher folder... But probably that should've gone into the website repository, if you think that here it would've been redundant...

**Comment by DioEgizio** [comment]
you might wanna contribute to the website then

**Comment by ryanccn** [comment]
I've been referencing the GitHub Actions for so long lol

**Comment by txtsd** [comment]
Thank you, but it would be better if you added these instructions at [PrismLauncher/prismlauncher.github.io](https://github.com/PrismLauncher/prismlauncher.github.io/blob/master/src/wiki/development/build-instructions.md#macos) instead.

**Pull request closed without merging**
