### PR TITLE
fix: set HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK to 1

### PR DESCRIPTION
**Pull request by DioEgizio**
actually fixes the issue this time :catquake:

### CODE REVIEW

**Comment by Scrumplex** [comment]
I don't think this is a good workaround. We would probably end up with a broken installation here considering OpenSSL 3 is a major bump. Maybe we can just tell Homebrew to not fail when `brew link` fails

**Comment by DioEgizio** [comment]
Tbh at least openssl version works

https://github.com/DioEgizio/PrismLauncher/actions/runs/3886389523/jobs/6631434068#step:18:90

**Review by flowln — APPROVED** [review]
this may not be a good workaround, but we can get a better one later, rn it would be good to stop the actions from failing imo :slightly_smiling_face:

**Review by Scrumplex — APPROVED** [review]
¯\\\_(ツ)_/¯

**Pull request merged**
