### PR TITLE
Update mod loader / intermediary automatically when changing minecraft version

### LINKED ISSUE #562: Automatically update mod loader when Minecraft version is changed
### Role

I play the latest version of Minecraft with Fabric

### Suggestion

When the user changes the Minecraft version, Prism should automatically update the mod loader (Forge/Fabric/intermediary mappings) to a compatible version.

### Benefit

If the user forgets to update the mod loader, they will get a nasty and confusing crash when launching the game. Updating the mod loader automatically means this crash can't happen.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

After changing the Minecraft version, we get this:

image

The intermediary mappings are incompatible with the chosen Minecraft version, which causes this instance to crash on launch. Ideally, a situation like this should not be possible.

### PR DESCRIPTION
**Pull request by TheKodeToad**
Fixes #562 (I changed it because I was worried it would close as not planned but in reflection that makes no sense) 

HyperSoop did point some things out, but this does allow for mod loader versions to be anchored using the Customise button. I would think if you wanted to try something stupid you'd probably try this anyway, and it will reduce the number of clicks for normal users.

This doesn't update fabric or quilt loader versions as they are not tied to any particular MC version unlike more heavyweight options.

The task handling is possibly broken but it seems to work in my testing.

image

I pinky promise not to force push next time.

### CODE REVIEW

**Comment by Scrumplex** [comment]
I don't think VersionPage is the best place to handle this. We have `ComponentUpdateTask` for this. The code of that is just :skull:

**Comment by TheKodeToad** [comment]
I can't quite work out the right place in the file to put the logic.

**Comment by TheKodeToad** [comment]
Can anyone help with this? Sorry. This file hurts my brain.

**Comment by flowln** [comment]
I noticed `PackProfile` has a `minecraftChanged` signal that gets emitted every time someone changes the minecraft version, maybe you could make some slot connected to it to react to this change. Note that the intermediary versions get hardcoded in the dependency resolution code when they're created: https://github.com/PrismLauncher/PrismLauncher/blob/6ea1234a3bb9787a77680ff528f21bdf1e40989c/launcher/minecraft/ComponentUpdateTask.cpp#L602

So, I did a little thing using that, and simply removing all dependency components, with a lambda at `PackProfile`s constructor connected to the aforementioned signal:

```cpp
    connect(this, &PackProfile::minecraftChanged, this, [this]{
        int i = 0;
        while (i < d->components.size()) {
            if (d->components.at(i)->m_dependencyOnly)
                remove(i);
            else
                i += 1;
        }

        reload(Net::Mode::Offline);
    });
```

it's very filthy and there seems to be some weird behavior with the list view when switching versions, particularly with snapshots and stuff like that :c
however, it seems to do the job too, the intermediaries get correctly removed and then re-added in the dependency resolution with the correct version.

I hope this can help you somehow :)

**Comment by TheKodeToad** [comment]
> I noticed `PackProfile` has a `minecraftChanged` signal that gets emitted every time someone changes the minecraft version, maybe you could make some slot connected to it to react to this change. Note that the intermediary versions get hardcoded in the dependency resolution code when they're created:
> 
> https://github.com/PrismLauncher/PrismLauncher/blob/6ea1234a3bb9787a77680ff528f21bdf1e40989c/launcher/minecraft/ComponentUpdateTask.cpp#L602
> 
> So, I did a little thing using that, and simply removing all dependency components, with a lambda at `PackProfile`s constructor connected to the aforementioned signal:
> 
> ```c++
>     connect(this, &PackProfile::minecraftChanged, this, [this]{
>         int i = 0;
>         while (i < d->components.size()) {
>             if (d->components.at(i)->m_dependencyOnly)
>                 remove(i);
>             else
>                 i += 1;
>         }
> 
>         reload(Net::Mode::Offline);
>     });
> ```
> 
> it's very filthy and there seems to be some weird behavior with the list view when switching versions, particularly with snapshots and stuff like that :c however, it seems to do the job too, the intermediaries get correctly removed and then re-added in the dependency resolution with the correct version.
> 
> I hope this can help you somehow :)

Ah, thanks! This won't work with Forge and LiteLoader though, but I think I can figure it out.

**Comment by TheKodeToad** [comment]
I've moved the same code to PackProfile instead. The reason for the rebase is so I can see whether it somehow causes problems with modpacks (I doubt it though).

**Review by flowln — APPROVED** [review]
this looks good to me, thanks!
please signoff the last commit though :p

**Comment by TheKodeToad** [comment]
> this looks good to me, thanks! please signoff the last commit though :p

I don't believe it (again)! All fixed now.

**Comment by Scrumplex** [comment]
I have created #690 yesterday, that handles Fabric Intermediary within ComponentUpdateTask. There isn't really a clean way to do this for Forge or LiteLoader.

Eventually we should just rewrite the whole dependency logic from scratch.

**Comment by TheKodeToad** [comment]
> I have created #690 yesterday, that handles Fabric Intermediary within ComponentUpdateTask. There isn't really a clean way to do this for Forge or LiteLoader.
> 
> Eventually we should just rewrite the whole dependency logic from scratch.

There isn't a *clean* way right now but this does work. Should I close this?

**Comment by Scrumplex** [comment]
Your PR works for Forge and LiteLoader though, doesn't it? Maybe we can keep yours around for that. My PR can't really deal with those two at all

**Comment by TheKodeToad** [comment]
Yes, it does. Additionally yours deletes customised components and switches to invalid versions which isn't that nice.

**Comment by Scrumplex** [comment]
> Additionally yours deletes customised components and switches to invalid versions which isn't that nice.

Hmm good point. Maybe I should fix that

**Comment by ghost** [comment]
You should consider adding a toggle in the settings for this feature. Don't be afraid to give the user choice

**Comment by TheKodeToad** [comment]
Arghh scary user choice! Locking the version by pressing Customise probably is enough for most people. Additionally, if the user is selecting an unsupported version, it will not change the mapping/loader version.

If there's something else you want to point out, don't hesistate!

**Comment by ghost** [comment]
Scary customize button! It's not an excuse, it's a completely different feature.

**Comment by TheKodeToad** [comment]
> Scary customize button! It's not an excuse, it's a completely different feature.

You're scaring me now! I'm not opposed to adding a setting, but maybe we should wait for a response from one of the maintainers. It's not obvious which section this should go in.

**Comment by ghost** [comment]
I think in Launcher -> Features might be a good spot, it already has a metadata related setting

**Comment by flowln** [comment]
conflicting with develop :cry:

**Comment by TheKodeToad** [comment]
i can fix this i think :sob:

**Comment by TheKodeToad** [comment]
I realise having worked with tasks more that it doesn't handle failure.

**Comment by DioEgizio** [comment]
this is failing

**Comment by TheKodeToad** [comment]
Let's see whether merging develop into it makes a difference (reworded :p)

**Comment by DioEgizio** [comment]
didn't work

also what's the diff between this and https://github.com/PrismLauncher/PrismLauncher/pull/690

**Comment by TheKodeToad** [comment]
I don't think the other one works with Forge or LiteLoader

**Comment by TheKodeToad** [comment]
Yes, I think maybe these floating functions should maybe go in another source file.

**Review by DioEgizio — APPROVED** [review]

**Comment by TheKodeToad** [comment]
Is there a nicer way to do this though (that still allows Forge support, it seems like scrumplex's solution is cleaner)?

**Comment by TheKodeToad** [comment]
Hmm, I think considering how the launcher behaves with LWJGL, Scrumplex's solution makes more sense. Maybe it would be better, with Forge, to have a popup or warning suggesting that the user changes the version!

**Pull request closed without merging**
