### PR TITLE
fix: update libnbtplusplus submodule's URL

### PR DESCRIPTION
**Pull request by flowln**
Signed-off-by: flow <flowlnlnln@gmail.com>

### CODE REVIEW

**Review by DioEgizio — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
Wait. flake.nix as well

**Review by Scrumplex — CHANGES_REQUESTED** [review]
update flake.nix as well :trollface:

**Comment by flowln** [comment]
how do i update flake.lock

**Comment by Scrumplex** [comment]
> how do i update flake.lock

I do :trollface:

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
(You would need to change the url in `flake.nix` and then run `nix flake update`)

**Comment by flowln** [comment]
> I do :trollface:

ok :relaxed:

**Pull request merged**
