### PR TITLE
feat(windows Qt autoinstall): use aqtinstall to install QT during configure if needed

### PR DESCRIPTION
**Pull request by Ryex**
Use a powershell wrapper for aqtinstall to automatically install QT on windows during the configure step if needed

Turned off with `-DMSVC_QT_AUTOINSTALL=off`
caches a completed install state so aqt is not rerun on reconfigure
installs `debug_information` modules for debug builds 

automatically configures `CMAKE_PREFIX_PATH` to find the installed qt

### CODE REVIEW

**Comment by Trial97** [comment]
Just for tracking is this blocking/replacing the other PR: https://github.com/PrismLauncher/PrismLauncher/pull/1466 ?

**Comment by Ryex** [comment]
Ah, I forgot I made that one. No. that one was more about the presets and need to be updated anyway. this is just to manage QT as a dep on windows.

**Review by Trial97 — COMMENTED** [review]
lgtm (but I'm no windows expert)

**Review by Trial97 — APPROVED** [review]

**Review by getchoo — CHANGES_REQUESTED** [review]
this doesn't make much sense imo. it's fairly non standard for a project to download missing build dependencies when not found (by default), let alone something the size of qt. following from our own example, this doesn't happen with *any* of our dependencies, even those we directly vendor with submodules. i don't see any reason to start doing this, as i believe installing platform specific dependencies should remain fairly separate from our cross platform build system

now regarding the script: i like the idea of making qt easier to install on windows. i'm sure we can all agree that it's the hardest part of getting prism to build on windows, and the issue most people have. i don't think a wrapper script is a way to improve that, though. 

the main functions of the script - listing qt versions, supported architectures, modules, and actually installing qt - are all already in `aqt`. why don't we just have users install that instead? it seems we do the same thing in ci for this reason; aqt can easily be used in place of this script

similar to our build process on linux, i think the best solution here is not trying to automatically do everything for the user and hide it away, but document it. in the case of qt, we could give command snippets for installing and using `aqt` (similar to our linux instructions) right along with our `cmake` commands. this would honestly be minimal effort (`Invoke-WebRequest -Uri $aqt_url -OutFile aqt.exe; aqt.exe install-qt ...`) in comparison to what we're doing here, along with making this explicitly opt-in for users who already have qt installed in other ways (or want to do it differently somehow)

**Comment by Ryex** [comment]
the thing is that aqt *isn't* easy to use. you have to know ahead of time what build arch and exact qt version to request and if you don't want to install everything with `--all` you need to know what modules are being used.
using aqt usually means using a command generator or calling aqt three or more times to find that information.

> it's fairly non standard for a project to download missing build dependencies when not found

that's not actually true. in the CMake ecosystem it's relativity common
if you didn't notice the Quazip submodule we use does this with BZip2 already

image

```
// ...
-- Using bundled QuaZip
-- Using Qt version 6
-- Fetching bzip2 https://sourceware.org/git/bzip2.git master
```

**Comment by getchoo** [comment]
> the thing is that aqt isn't easy to use. you have to know ahead of time what build arch and exact qt version to request and if you don't want to install everything with --all you need to know what modules are being used.
using aqt usually means using a command generator or calling aqt three or more times to find that information.

or one command in our documentation someone could copy and paste (just like on linux). if a user would like to do more, they could look at `aqt`'s own documentation
it's not like this wrapper script improves this either; if someone would like to do more than what we provide them with, they have to look into this completely undocumented wrapper

> in the CMake ecosystem it's relativity common

> if you didn't notice the Quazip submodule we use does this with BZip2 already

i think this being the only example in our project (and not actually from our project) is enough to show this *isn't* common. i don't know why we're arguing this. it's not often used and usually considered bad practice. cmake is a build system, not a dependency manager

**Comment by Ryex** [comment]
> cmake is a build system, not a dependency manager

It's clear that you have strong opinions about this, that's fine. But CMake is a *bit* more than just a build system. Or rather, it's a build system specifically designed for languages like for C/C++ and others where for a long time package managment was a foreign concept and so CMake for good reason *does* include the tools to do this. CMake has `file(DOWNLOAD  ... )` and `file(ARCHIVE_EXTRACT ...)` for a reason.

CMake's documentation has a whole section on [using-dependencies: Downloading And Building (dependencies) From Source](https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#id9). v3.24 added `FetchContent` and `FetchContent_Declare` to allow projects to set up their own bespoke  systems for package management.

So IMO - while this isn't ideal - on windows where package management is a newfangled concept to the ecosystem, and for a c++ project where package management has long been a dream; this is a valid and even comfortable solution.

**Comment by getchoo** [comment]
> on windows where package management is a newfangled concept to the ecosystem

i wouldn't say it's new; a proper solution to this in `vcpkg` has been out since 2016. if we want actual package management for our windows developers, we should be using that (which also does have cmake integration, and could give more reason to merge #1466 as that's the main way you use it)

> this is a valid and even comfortable solution.

just because a solution is valid doesn't make it a good one. this script can be easily replaced by ~two lines in our build docs. using cmake to run a powershell script wrapper doesn't solve much of anything compared to this, but introduces the maintenance burden of keeping up to date with `aqt`'s syntax + features, and annoyance to developers who (rightfully) don't expect configuring cmake to download *all of qt* - especially if they have installed it through another method themselves. i wouldn't call this type of implementation "comfortable" for these reasons either

**Comment by Trial97** [comment]
> i wouldn't say it's new; a proper solution to this in `vcpkg` has been out since 2016. if we want actual package management for our windows developers, we should be using that (which also does have cmake integration, and could give more reason to merge #1466 as that's the main way you use it)

It would be nice to have integration with vcpkg that way we would not need to keep submodules of the libraries that we use in our project and would also streamline the dev builds (also I do not like the current approach where we maintain a submodule of the library inside our project).

**Comment by Ryex** [comment]
since we explored vcpkg and conan in the discord thread and we arn't interested in this method I'll close

**Pull request closed without merging**
