### PR TITLE
clean up README

### PR DESCRIPTION
**Pull request by jitterdev**
use the referral code instead for discord server invite links.

### CODE REVIEW

**Comment by NotNite** [comment]
Not sure the server in "Discord server" should be capitalized. It's not a proper noun, unlike Discord.

**Comment by aprilthepink** [comment]
also pr does different things than it says.

**Review by AshtakaOOf — COMMENTED** [review]
This PR isn't needed

**Comment by jitterdev** [comment]
> Not sure the server in "Discord server" should be capitalized. It's not a proper noun, unlike Discord.

it was used as "Discord Server" in one place and "Discord server" in another so i decided to stick with the former. I can update it to be "Discord server" for both places though.

**Comment by jitterdev** [comment]
> its better to use invite codes instead of vanity (incase server loses lvl 3)

this is incredibly rare for large servers and ive never seen it happen unless the server is small and is struggling to get boosters. The server has over 90 boosters as of right now so this will probably never be a problem

**Review by Scrumplex — APPROVED** [review]
Thanks

**Review by AshtakaOOf — CHANGES_REQUESTED** [review]
Make the `[Discord Server](https://discord.gg/hX4g537UNE)` like this maybe? `[Discord Server: https://discord.gg/prismalauncher](https://discord.gg/hX4g537UNE)`

**Comment by jitterdev** [comment]
I don't feel like using non-referral links will be necessary. It's smart to plan ahead but Discord offers a warning anyways for when a server is about to lose boost status. If maintaining boost status proves to be an issue, I'm fine with using a user-generated permanent link instead but as of now we should be fine.

**Comment by Lutitious** [comment]
vanity links are cool imo they should stay

**Comment by Lutitious** [comment]
we could also just have https://prismlauncher.org/discord auto redirect to a discord link

**Review by flowln — APPROVED** [review]

**Pull request merged**
