### PR TITLE
Grammar & Formatting Improvements

### PR DESCRIPTION
**Pull request by Aresiel**
Improved grammar and formatting (in some places), mainly of code comments. Consistency is key!

### CODE REVIEW

**Review by Scrumplex — CHANGES_REQUESTED** [review]
:trollface:

**Review by Scrumplex — CHANGES_REQUESTED** [review]
:thinking:

**Comment by Aresiel** [comment]
> 🤔

Are you suggesting that I replace comments with emojis?

**Comment by BeansBeefBroccoli** [comment]
This is confusing

**Comment by AshtakaOOf** [comment]
Wdym? this is completely normal :)

**Comment by Aresiel** [comment]
crap wrong button-

**Pull request closed without merging**
