### PR TITLE
Add Maxwell cat option

### PR DESCRIPTION
**Pull request by jdev082**
This PR adds Maxwell as an option.
image
image

This PR is not yet finished as it has a few problems.

1. Needs a better image 
2. I need to sign off my commits

Is there any way to sign off commits that have already been pushed?

### CODE REVIEW

**Comment by jdev082** [comment]
Also, ignore my misspelled commits.

**Comment by jdev082** [comment]
Improved maxwell png
image

**Comment by jdev082** [comment]
I have signed off the commits and swapped out the maxwell png to a more suitable one.

**Review by getchoo — APPROVED** [review]
i think the cropping could be a bit better here, but i still like the idea of another silly cat
image

**Comment by jdev082** [comment]
> i think the cropping could be a bit better here, but i still like the idea of another silly cat

That was the best image I could find.

**Comment by TheKodeToad** [comment]
In my opinion there are already maybe too many cats (sorry)! So I think #668 being resolved should be preferred over adding more of them :3

**Comment by jdev082** [comment]
> In my opinion there are already maybe too many cats (sorry)! So I think #668 being resolved should be preferred over adding more of them :3

One more can't hurt?

**Comment by TheKodeToad** [comment]
You seem to have deleted your comment, but one more won't hurt. I'm just saying custom cats is probably the best long-term solution in my opinion!

**Comment by getchoo** [comment]
i actually hadn't seen 668 yet, and yeah i can kinda agree for the long term it would be better. i'd still be up for this being the last cat before then though

**Comment by TheKodeToad** [comment]
at this rate we'll need a cat pr/issue label x3

**Comment by Regular-Baf** [comment]
We need Catpacks (please can this be the official name)

**Comment by TheKodeToad** [comment]
Prism Launcher DLC when

**Comment by Trial97** [comment]
Do not know if it helps but PR https://github.com/PrismLauncher/PrismLauncher/pull/1253 implemented the catpacks.

**Comment by getchoo** [comment]
yeah with catpacks being added and easy to use, i think it might be time to end upstream prs for them (a sad moment). the only exceptions i can really see would be for "cats" that have a lot of love from the wider prism community - like rory and teawie

**Comment by jdev082** [comment]
> yeah with catpacks being added and easy to use, i think it might be time to end upstream prs for them (a sad moment). the only exceptions i can really see would be for "cats" that have a lot of love from the wider prism community - like rory and teawie

maxwell funny

**Comment by Scrumplex** [comment]
I don't think we want to add too many cats. We should probably prefer #1253 and rely on community cat packs

**Comment by Trial97** [comment]
Now that catpacks are a thing can this PR be closed?

**Comment by Scrumplex** [comment]
> Now that catpacks are a thing can this PR be closed?

yep

**Pull request closed without merging**
