### PR TITLE
Validate maximum memory allocation

### LINKED ISSUE #426: Suggestion with hardwere reserved memory laptops.
### Role

To be simple / play modpacks.

### Suggestion

A checkbox that bypass a checkJVMArgs()

### Benefit

So I can finnaly use PrismLauncher instead of GDLauncher.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The main issue is blocked JVM Args,
My hardwere has 6.9 GB Ram because 1.1 is hardwere reserved I am using zram for extra ram.

I am alaways using -Xmx -Xms args to allocate memory higher then 6.9. Some modpacks will crash unlikly if I dont allocate 8 GB Ram (Tested with Project Ozone 3) thats modpack is RAM Hungry. 

Sorry for my bad english.

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #426 

Add a small checkmark/cross/warning symbol to the memory setting to tell the user if their input is a good idea or not.

Also raise memory limit to 1 TiB :trollface:

### CODE REVIEW

**Comment by Scrumplex** [comment]
New screenshots:
Valid memory allocation
Memory allocation approaching system memory
Memory allocation exceeding system memory

**Review by edgars-cirulis — APPROVED** [review]
Tested with my memory reserved hardwere.
 - Allocate more then 6.9 GB Test passed. instance lunches with 8 GB

Looks good to me

**Review by TheKodeToad — CHANGES_REQUESTED** [review]
`updateThresholds` is duplicated. Apart from that (mostly) looks good. Maybe sysMiB could be `static`?

**Comment by Scrumplex** [comment]
> `updateThresholds` is duplicated. Apart from that (mostly) looks good. Maybe sysMiB could be `static`?

It is. But sadly, all instance-override settings are like that. We need to clean that up in the future.

**Comment by TheKodeToad** [comment]
> > `updateThresholds` is duplicated. Apart from that (mostly) looks good. Maybe sysMiB could be `static`?
> 
> It is. But sadly, all instance-override settings are like that. We need to clean that up in the future.

:P seems like Prism does that a lot (likely inherited from MultiMC).

Maybe you could still make the variable static?
Also, I don't see a need for the block at the end.

**Review by flowln — APPROVED** [review]
looking good to me!

I was gonna say that it would perhaps make sense to also fix #427 in here, but I wasn't able to reproduce that issue neither here nor or develop, so idk :woman_shrugging:

**Comment by ghost** [comment]
> but I wasn't able to reproduce that issue neither here nor or develop

That issue only occurs with the setup screen

https://user-images.githubusercontent.com/110736028/202907998-69382623-901e-422b-8a43-16c968f8d98c.mp4

**Comment by flowln** [comment]
ah, that makes a bit more sense xD

well then, this PR needs to bump the maximum memory in that place too
i wonder though, maybe it would be nicer if we could remove the VersionSelectWidget thingy from JavaSettingsWidget, and make it generic enough so that we can reuse it in all three Java thingies?

**Comment by Scrumplex** [comment]
> maybe it would be nicer if we could remove the VersionSelectWidget thingy from JavaSettingsWidget, and make it generic enough so that we can reuse it in all three Java thingies?

Ideally, all settings pages should just be able to handle both global and instance-specific pages, depending on how they were instantiated.
That way, we could get rid of a lot of duplicate code.

**Comment by flowln** [comment]
> Ideally, all settings pages should just be able to handle both global and instance-specific pages, depending on how they were instantiated. That way, we could get rid of a lot of duplicate code.

well, yeah, but in this particular case, even if we did that, there'd still be some duplicate code with the widget for the wizard :|

**Review by DioEgizio — APPROVED** [review]

**Pull request merged**
