### PR TITLE
Update metainfo

### PR DESCRIPTION
**Pull request by AshtakaOOf**
This should be merged right after https://github.com/PrismLauncher/prismlauncher.org/pull/208

### CODE REVIEW

**Review by DioEgizio — APPROVED** [review]

**Comment by AshtakaOOf** [comment]
Tell me if I should modify the text and add more stuff

**Comment by DioEgizio** [comment]
Add modpack updating screenshots

**Comment by Scrumplex** [comment]
Moving to an imaginary 6.2 milestone as this would need to be backported in case we release a 6.2

**Review by Scrumplex — APPROVED** [review]

**Comment by AshtakaOOf** [comment]
Me when :skull:

**Pull request merged**
