### PR TITLE
Remove appveyor

### PR DESCRIPTION
**Pull request by AshtakaOOf**
I forgor :skull: I also wanna cry
But seriously I forgor to remove the &logo=appveyor thing AAAAAH!!!

Signed-off-by: Adrien <66513643+AshtakaOOf@users.noreply.github.com>

### CODE REVIEW

**Comment by AshtakaOOf** [comment]
I shouldn't do PR late at night next time

**Review by Scrumplex — APPROVED** [review]
I was wondering why there was this weird logo but didn't think about it further lol

**Review by flowln — APPROVED** [review]
you forgor :skull:

**Comment by AshtakaOOf** [comment]
Yes I forgor :skull:

**Pull request merged**
