### PR TITLE
Renaming instance groups

### LINKED ISSUE #1502: Renaming Instance Groups
### Role

I play Minecraft

### Suggestion

Be able to rename a group instead of having to make a new one

### Benefit

If you have lot of instances, and want to rename their group, having to move all of them into a new group just for a rename is an inconvenience.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### PR DESCRIPTION
**Pull request by TheKodeToad**
I need sleep as mentioned

It's seems to work, but I'm not quite sure how well. Just opening this so people can comment!

### CODE REVIEW

**Comment by TheKodeToad** [comment]
I haven't noticed any issues apart from one which disappeared :P

**Comment by DioEgizio** [comment]
seems to work but i think many people wouldn't except this feature, so maybe a little ✏️ icon next to the name instead of having to right click?

**Comment by TheKodeToad** [comment]
I don't think a coloured icon would look right...

**Review by Trial97 — APPROVED** [review]

**Comment by Trial97** [comment]
> I don't think a coloured icon would look right...

Regarding that, you can use the rename icon that we already use for rename instance

You can also add icons in the group menu similar to icons in the instance menu(but that would be a stretch of this PR)

**Comment by TheKodeToad** [comment]
That's a coloured icon - depending on the theme

**Comment by Trial97** [comment]
> That's a coloured icon - depending on the theme

Then create a new icon base on breeze_dark(for example) rename icon and leave the rest to the themes to add a new one

**Comment by TheKodeToad** [comment]
I'd rather not bother with it - there is already an instance view rewrite in progress

**Review by TayouVR — APPROVED** [review]
works

**Pull request merged**
