### PR TITLE
added suport for atlauncher browser download

### LINKED ISSUE #282: Unsupported download type browser for DNS Techpack 6.x from ATLauncher
### Operating System

Windows, Linux

### Version of Prism Launcher

Prism Launcher 5.0 Portable

### Version of Qt

Qt 6.3.0

### Description of bug

Unable to download DNS techpack 6.6.x from ATLauncher

Screenshot_20221024_081234

### Steps to reproduce

* Add new instance
* Go to ATLauncher
* Install DNS Techpack 6.x

### Suspected cause

Related :

- https://github.com/MultiMC/Launcher/pull/3314
- https://github.com/MultiMC/Launcher/issues/4374

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes: #282

As the links from DNS Techpack 6.x are no longer valid please suggest a pack to test this against.

### CODE REVIEW

**Comment by DioEgizio** [comment]
is there any way to test this pr?

**Comment by Trial97** [comment]
For the moment no.
Only if you know another atl pack that has a browser mod type.
The one mentioned in the ticket doesn't work anymore(the URLs point to a different thing).

**Comment by Trial97** [comment]
@DioEgizio now this can be tested with: Silvania Ultimatum pack, the latest version, and select OptiFine optional mod or with Kingdoms Of The Valley latest version which the browser downloads journeyman.
Thanks to the help of  RyanTheAllmighty who pointed me to the packs here: https://discord.com/channels/117047818136322057/1006343149553188894

**Review by DioEgizio — APPROVED** [review]

**Review by TayouVR — APPROVED** [review]
as this is reusing the dialog it says "blocked mods" in the title, but I think that can be ignored for the time being, unless you want to go and change that, maybe with an override to the function/ctor?

**Comment by Trial97** [comment]
I think "Blocked mods" is the best way to describe this as these mods are not downloadable through normal means and you need to do the same steps as curseforge ones(go to the download link and manually download them)

**Pull request merged**
