### PR TITLE
Allow you to use offline mode without an account.

### PR DESCRIPTION
**Pull request by AVuTuVA**

### CODE REVIEW

**Comment by forkiesassds** [comment]
No.

**Comment by DioEgizio** [comment]
no.

**Comment by DIDIRUS4** [comment]
Yes.

**Comment by manul694** [comment]
Yes*

**Comment by forkiesassds** [comment]
@DIDIRUS4 @manul694 There is an amazing website where you can [get Minecraft](https://www.minecraft.net/get-minecraft) legitimately.

**Comment by DIDIRUS4** [comment]
> @DIDIRUS4 @manul694 There is an amazing website where you can [get Minecraft](https://www.minecraft.net/get-minecraft) legitimately.

We already have Licence Minecraft, but why you block login in Minecraft Client with online-mode: false ? Mojang officially allowing it in server.properties for example, why you hate offline mode ?

Minecraft Client seems like Minecraft Server. But idk why you restrict online-mode: false in Client, if Mojang have it in main configuration. Everyone can get Minecraft Server Core for free in Internet.

 I don't understand Europe community in that issue....

**Comment by forkiesassds** [comment]
> We already have Licence Minecraft, but why you block login in Minecraft Client with online-mode: false ? Mojang officially allowing it in server.properties for example, why you hate offline mode ?

1. It's only in cases for instance like a LAN party in a remote place where you don't really have internet access
2. It causes security issues where players can impersonate eachother

> Minecraft Client seems like Minecraft Server. But idk why you restrict online-mode: false in Client, if Mojang have it in main configuration. Everyone can get Minecraft Server Core for free in Internet.

So what? There isn't anything to protect the client jars from being downloaded by anyone and anything because implementing such security measures is too time consuming and a hassle to maintain and make sure it's secure.

> I don't understand Europe community in that issue....

I'm European, and I have no idea what you're talking about. North American people will also say the same in regards to piracy and it's not really dependent on where people live.

**Comment by Scrumplex** [comment]
We had this discussion multiple times now. Read the EULA. You need to buy a license of the game to legitimately play the game.

**Pull request closed without merging**
