### PR TITLE
libs: update quazip submodule

### PR DESCRIPTION
**Pull request by edgars-cirulis**
Signed-off-by: Edgars Cīrulis <edgarsscirulis@gmail.com>

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Review by flowln — CHANGES_REQUESTED** [review]
the system dependency in our `CMakeLists.txt` still looks for QuaZip 1.3. Seems like a bad idea to depend on two different versions of the same library in different contexts.

**Comment by Scrumplex** [comment]
> the system dependency in our `CMakeLists.txt` still looks for QuaZip 1.3. Seems like a bad idea to depend on two different versions of the same library in different contexts.

Isn't that just the minimum version?

**Comment by flowln** [comment]
> Isn't that just the minimum version?

not sure, i would guess it would pick up '1.3.x', but i wouldn't expect it to catch '1.4'. But maybe it does, CMake is weird sometimes :thinking:

**Comment by Scrumplex** [comment]
Well, I am running the `prismlauncher-git` AUR package on my system, and it hasn't complained about my QuaZip 1.4 installation.

**Comment by flowln** [comment]
> Well, I am running the `prismlauncher-git` AUR package on my system, and it hasn't complained about my QuaZip 1.4 installation.

Did it use the system install, or did it fall back to the bundled one though? Since it uses `QUIET` the end result will be the same.

**Comment by Scrumplex** [comment]
> > Well, I am running the `prismlauncher-git` AUR package on my system, and it hasn't complained about my QuaZip 1.4 installation.
> 
> Did it use the system install, or did it fall back to the bundled one though? Since it uses `QUIET` the end result will be the same.

system install:

```
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Git commit: cefa1662ef822323940fabc18fc48bee1937eb4f
-- Git tag: -128-NOTFOUND
-- Git refspec: refs/heads/develop
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib/libxkbcommon.so (found suitable version "1.5.0", minimum required is "0.5.0") 
-- Found WrapVulkanHeaders: /usr/include  
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for one of the modules 'scdoc'
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found Java: /usr/bin/java (found suitable version "1.8.0.362", minimum required is "1.7") found components: Development 
-- Using system zlib
-- Using system QuaZip
-- Using system tomlplusplus
-- Using system cmark
-- Using system ghc_filesystem
-- Configuring done
-- Generating done
-- Build files have been written to: /home/scrumplex/.cache/paru/clone/prismlauncher-git/src/build
```


Also from CMake docs:

> The `[version]` argument requests a version with which the package found should be compatible.

and

> The `EXACT` option requests that the version be matched exactly.

https://cmake.org/cmake/help/latest/command/find_package.html#id7

**Comment by flowln** [comment]
Well, the versions aren't necessarily compatible here, seeing there was ABI changes. Doesn't matter though, if CMake says they are, i'm not gonna fight it :woman_shrugging: 

Anyways, this seems like just a package issue rather than a Prism one. There seems to be not much, if any, changes in QuaZip 1.4 that would affect us, so upgrading isn't really necessary at all. The only one giving any issues with that atm seems to be Arch bumping their package with ABI changes because yes.

Nix also needs updating, because for some reason we have a nix CI here.

**Comment by Scrumplex** [comment]
IMO, it would be a bad idea to bump to 1.4 ourselves, as no stable distribution offers that version.

**Comment by edgars-cirulis** [comment]
> IMO, it would be a bad idea to bump to 1.4 ourselves, as no stable distribution offers that version.

gotcha

**Comment by flowln** [comment]
> IMO, it would be a bad idea to bump to 1.4 ourselves, as no stable distribution offers that version.

I agree, which is why I don't see the point in bumping the submodule either. As I've said in the beginning, having different versions based on using the bundled ones or the system one seems like a bad idea.

**Comment by Scrumplex** [comment]
Aren't we statically linking the submodule?

**Comment by flowln** [comment]
> Aren't we statically linking the submodule?

Yes, but I don't think it's a bad idea because of the ABI changes, i'm more concerned about possibly having issues in one version and not other, and then having to debug through that with one extra variable mixed in. Not that it's super probable to occur, but it seems better to be on the safer side. And it's not like we're losing anything not bumping it yet. 
The release is pretty new, why should be bump it now, instead of waiting for distros to pick it up, and do it all at once?

**Comment by DioEgizio** [comment]
Yeah I don't see the point of this pr and the last commit breaks linking prism with old quazip when it works completely fine

**Pull request closed without merging**
