### PR TITLE
Branding

### PR DESCRIPTION
**Pull request by LauraWebdev**
Hey there,

I've decided to create some branding assets for this project. I've included all source svg files as well as exported png versions for dark background, light backgrounds and an icon only version in common icon sizes.

I am not sure where to document branding colors, I've used these values for the gradient:
Light - #5DA93F
Dark - #10454F

image
image

### CODE REVIEW

**Comment by AshtakaOOf** [comment]
These are pretty cool but for now you should submit them on the discord server

**Comment by Aproxia-dev** [comment]
Honestly in my opinion, if we're naming it **Prism** Launcher, I feel like the green color looks sort of weird. I'm much more thinking of some bright-ish blue/pink colors to imitate a glassy prism.

Note: I do know that the colors I said might feel like i'm intentionally trying to make it branded after the trans flag, but i genuinely think the color combination would fit better with the name lol

**Comment by Aproxia-dev** [comment]
Also now after looking at it for a bit longer it reminds me of Ethereum way too much lmao

**Comment by Octelly** [comment]
> Honestly in my opinion, if we're naming it **Prism** Launcher, I feel like the green color looks sort of weird. I'm much more thinking of some bright-ish blue/pink colors to imitate a glassy prism.
> 
> Note: I do know that the colors I said might feel like i'm intentionally trying to make it branded after the trans flag, but i genuinely think the color combination would fit better with the name lol

i think purple would be good
perhaps rainbow or something?

**Comment by Octelly** [comment]
user selectable colour to match their desktop would be cool, kinda like you can usually choose your system's accent colour

**Comment by Aproxia-dev** [comment]
> > Honestly in my opinion, if we're naming it **Prism** Launcher, I feel like the green color looks sort of weird. I'm much more thinking of some bright-ish blue/pink colors to imitate a glassy prism.
> > Note: I do know that the colors I said might feel like i'm intentionally trying to make it branded after the trans flag, but i genuinely think the color combination would fit better with the name lol
> 
> i think purple would be good perhaps rainbow or something?

Actually I really like the idea of making it purple.

And maybe there could be a beam of light that the prism itself is splitting into a rainbow like that one image that I assume most of us know from physics class or the album art from Pink Floyd's The Dark Side Of The Moon lol

**Comment by dynamyc010** [comment]
> > > Honestly in my opinion, if we're naming it **Prism** Launcher, I feel like the green color looks sort of weird. I'm much more thinking of some bright-ish blue/pink colors to imitate a glassy prism.
> > > Note: I do know that the colors I said might feel like i'm intentionally trying to make it branded after the trans flag, but i genuinely think the color combination would fit better with the name lol
> > 
> > i think purple would be good perhaps rainbow or something?
> 
> Actually I really like the idea of making it purple.
> 
> And maybe there could be a beam of light that the prism itself is splitting into a rainbow like that one image that I assume most of us know from physics class or the album art from Pink Floyd's The Dark Side Of The Moon lol

Purple would be cool looking ngl
I like purple

**Comment by LauraWebdev** [comment]
> These are pretty cool but for now you should submit them on the discord server

I tried, however it seems like Discord doesn't let me join (maybe due to spam protections).

**Comment by LauraWebdev** [comment]
Also, thanks for all the comments. I'm of course open for any changes, suggestions or using this as the base for a different approach.

The initial colors were chosen based on the connection to Minecraft's grass block.

**Comment by dynamyc010** [comment]
> Also, thanks for all the comments. I'm of course open for any changes, suggestions or using this as the base for a different approach.
> 
> The initial colors were chosen based on the connection to Minecraft's grass block.

That sounds fair enough, but maybe it'd be better to branch off the grass block?
Not like it's been doing us many favors in the past...

Yesterday I saw the crying obsidian as quite an interesting block

Also, here's the invite to the server
https://discord.gg/prismlauncher

**Comment by Aproxia-dev** [comment]
> > Also, thanks for all the comments. I'm of course open for any changes, suggestions or using this as the base for a different approach.
> > The initial colors were chosen based on the connection to Minecraft's grass block.
> 
> That sounds fair enough, but maybe it'd be better to branch off the grass block? Not like it's been doing us many favors in the past...
> 
> Yesterday I saw the crying obsidian as quite an interesting block
> 
> Also, here's the invite to the server https://discord.gg/prismlauncher

i'm having the same issue, the invite is just not working, probably because of the sheer amount of people trying to join.

**Comment by dynamyc010** [comment]
> > > Also, thanks for all the comments. I'm of course open for any changes, suggestions or using this as the base for a different approach.
> > > The initial colors were chosen based on the connection to Minecraft's grass block.
> > 
> > That sounds fair enough, but maybe it'd be better to branch off the grass block? Not like it's been doing us many favors in the past...
> > 
> > Yesterday I saw the crying obsidian as quite an interesting block
> > 
> > Also, here's the invite to the server https://discord.gg/prismlauncher
> 
> i'm having the same issue, the invite is just not working, probably because of the sheer amount of people trying to join.

Ah, sadness :(
I can't even make an old-school invite either so meh

**Comment by LauraWebdev** [comment]
@dynamyc010 since Discord is a closed community and to have a more "open source", maybe it would be best if I just close this PR and create an issue for an open discussion about this? It would be great if this project (unlike PolyMC or MultiMC) could be a true open source software with transparent discussions.

**Comment by Aproxia-dev** [comment]
> @dynamyc010 since Discord is a closed community and to have a more "open source", maybe it would be best if I just close this PR and create an issue for an open discussion about this? It would be great if this project (unlike PolyMC or MultiMC) could be a true open source software with transparent discussions.

there's already #51, might be nice to move over there.

**Comment by dynamyc010** [comment]
> @dynamyc010 since Discord is a closed community and to have a more "open source", maybe it would be best if I just close this PR and create an issue for an open discussion about this? It would be great if this project (unlike PolyMC or MultiMC) could be a true open source software with transparent discussions.

Well the Discord already has an icon submissions channel so I'm not sure how many people would see yours, but could worth a shot.

(Also, I'm not a dev or anything, I'm just expressing my opinion and trying to help as much as I can)

**Comment by Octelly** [comment]
> > @dynamyc010 since Discord is a closed community and to have a more "open source", maybe it would be best if I just close this PR and create an issue for an open discussion about this? It would be great if this project (unlike PolyMC or MultiMC) could be a true open source software with transparent discussions.
> 
> Well the Discord already has an icon submissions channel so I'm not sure how many people would see yours, but could worth a shot.
> 
> (Also, I'm not a dev or anything, I'm just expressing my opinion and trying to help as much as I can)

considering that noone seems to be able to join the server, could you try telling someone on the server about the issue?

**Comment by dynamyc010** [comment]
> > > @dynamyc010 since Discord is a closed community and to have a more "open source", maybe it would be best if I just close this PR and create an issue for an open discussion about this? It would be great if this project (unlike PolyMC or MultiMC) could be a true open source software with transparent discussions.
> > 
> > Well the Discord already has an icon submissions channel so I'm not sure how many people would see yours, but could worth a shot.
> > 
> > (Also, I'm not a dev or anything, I'm just expressing my opinion and trying to help as much as I can)
> 
> considering that noone seems to be able to join the server, could you try telling someone on the server about the issue?

Smart idea.

**Comment by Octelly** [comment]
> > > > @dynamyc010 since Discord is a closed community and to have a more "open source", maybe it would be best if I just close this PR and create an issue for an open discussion about this? It would be great if this project (unlike PolyMC or MultiMC) could be a true open source software with transparent discussions.
> > > 
> > > 
> > > Well the Discord already has an icon submissions channel so I'm not sure how many people would see yours, but could worth a shot.
> > > (Also, I'm not a dev or anything, I'm just expressing my opinion and trying to help as much as I can)
> > 
> > 
> > considering that noone seems to be able to join the server, could you try telling someone on the server about the issue?
> 
> Smart idea.

ok but will you do it :eye:

**Comment by dynamyc010** [comment]
> > > > > @dynamyc010 since Discord is a closed community and to have a more "open source", maybe it would be best if I just close this PR and create an issue for an open discussion about this? It would be great if this project (unlike PolyMC or MultiMC) could be a true open source software with transparent discussions.
> > > > 
> > > > 
> > > > Well the Discord already has an icon submissions channel so I'm not sure how many people would see yours, but could worth a shot.
> > > > (Also, I'm not a dev or anything, I'm just expressing my opinion and trying to help as much as I can)
> > > 
> > > 
> > > considering that noone seems to be able to join the server, could you try telling someone on the server about the issue?
> > 
> > 
> > Smart idea.
> 
> ok but will you do it eye

if you ask me nicely

**Comment by Octelly** [comment]
> > > > > > @dynamyc010 since Discord is a closed community and to have a more "open source", maybe it would be best if I just close this PR and create an issue for an open discussion about this? It would be great if this project (unlike PolyMC or MultiMC) could be a true open source software with transparent discussions.
> > > > > 
> > > > > 
> > > > > Well the Discord already has an icon submissions channel so I'm not sure how many people would see yours, but could worth a shot.
> > > > > (Also, I'm not a dev or anything, I'm just expressing my opinion and trying to help as much as I can)
> > > > 
> > > > 
> > > > considering that noone seems to be able to join the server, could you try telling someone on the server about the issue?
> > > 
> > > 
> > > Smart idea.
> > 
> > 
> > ok but will you do it eye
> 
> if you ask me nicely

pretty please :pleading_face:

**Comment by music-cat-bread** [comment]
@LauraWebdev Just wanted to ask, which font have you used?

**Comment by jn64** [comment]
@comand100vip It's [Inter](https://rsms.me/inter/) (Heavy and Medium)

**Comment by music-cat-bread** [comment]
Okay, thanks!

**Comment by LauraWebdev** [comment]
It was indeed Inter

**Comment by eyduh** [comment]
> Also now after looking at it for a bit longer it reminds me of Ethereum way too much lmao

this was my first impression "wonky ethereum/sims"

**Pull request closed without merging**
