### PR TITLE
feat: Make Konami Code a *bit* more obvious

### PR DESCRIPTION
**Pull request by TayouVR**
very important change :)

<summary>
<details>
</img>
</summary>

### CODE REVIEW

**Review by leia-uwu — APPROVED** [review]
LGTM!!!!

**Review by DioEgizio — APPROVED** [review]
Best feature ever

**Review by getchoo — APPROVED** [review]
amazing 🙏🏻

**Comment by SoulKit** [comment]
Where would I be without this most important change. Ty

**Pull request merged**
