### PR TITLE
fix: more user friendly Java warning text

### LINKED ISSUE #256: Let the user know of the "Disable Java compatibility checks" option.
### Role

I use the launcher.

### Suggestion

I want the launcher to inform the user of how and where they can disable the Java compatibility check and where they can download the needed version of Java whenever the check doesn't let the instance start up.

### Benefit

so it's more intuitive for new users.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### LINKED ISSUE #344: Minecraft 1.19.2 not launching with Java 19, but is compatible with it (tested with MultiMC).
### Role

I play Minecraft 1.19.2 with Fabric mods.

### Suggestion

I want the launcher to mark Java 19 as "compatible" with Minecraft 1.19.x.

### Benefit

so users of Arch Linux and Arch-based distros like me can use Minecraft 1.19 without needing to use an "old" version of Java (Java 17 or Java 18 in this case).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### PR DESCRIPTION
**Pull request by ryanccn**
closes #344
Closes #256

### CODE REVIEW

**Comment by Scrumplex** [comment]
I think this message should just point people to the setting to configure Java in general. The checkbox to skip this check is pretty obvious there

**Comment by ryanccn** [comment]
@Scrumplex how about "Go to instance Java settings to change your Java version or disable the Java compatibility check if you know what you're doing"

**Comment by TayouVR** [comment]
I think the "disable the Java compatibility check **if you know what you're doing**" is important, to stop people from trying to play with the wrong java and then asking for help when it doesn't work. 
So yes, I think changing it to 
> "Go to instance Java settings to change your Java version or disable the Java compatibility check if you know what you're doing"

is good.

**Review by flowln — APPROVED** [review]
i feel like the imperative here is a bit too aggressive, but maybe that's just me being me :p

**Review by txtsd — APPROVED** [review]

**Pull request merged**
