### PR TITLE
removed demo

### PR DESCRIPTION
**Pull request by Trial97**
Why?
@TheKodeToad

### CODE REVIEW

**Review by TheKodeToad — COMMENTED** [review]
> Why?

I was concerned with some of the ways this feature could be abused, specifically with another change introduced in 9.0. (I am being vague as this is public). We don't have to remove the feature entirely, but the user can add `--demo` themselves anyway... It's also very easy to create a microsoft account which doesn't own minecraft and play demo mode in the official launcher

The last parameter here can also safely be removed and "demo", demo changed to "demo", false: https://github.com/PrismLauncher/PrismLauncher/blob/develop/libraries/launcher/legacy/org/prismlauncher/legacy/LegacyFrame.java#L99

**Comment by TayouVR** [comment]
I had commented on this on discord, but I want to say it here, too.

I am generally against removing demo mode, and instead improving its detection via meta and possibly launcher side checks.

**Comment by TheKodeToad** [comment]
We really have gotta remove it if we rework meta
If there is some way we can stop people from just removing --demo i don't think it's worth it - who wants to play modded mc in demo mode? Just use the vanilla launcher

**Comment by Trial97** [comment]
Yeah but with recent changes this had conflicts, that I do not want to resolve. Feel free to fix the conflicts and reopen it if needed

**Pull request closed without merging**
