### PR TITLE
Print build platform on launch

### PR DESCRIPTION
**Pull request by Scrumplex**

### CODE REVIEW

**Comment by Ryex** [comment]
Please do *not* make this change. The updater PR relies on the build platform containing this information to properly filter release assets.
Or at least if the matrix name is removed from the `BUILD_PLATFORM` it needs to be moved to another constant so it is available.

**Comment by Scrumplex** [comment]
> Or at least if the matrix name is removed from the BUILD_PLATFORM it needs to be moved to another constant so it is available.

Some of our downstream distributions already use BUILD_PLATFORM to differentiate their builds. I think this would be very helpful for support (you could tell what distribution someone is using in logs)

**Comment by Ryex** [comment]
> > Or at least if the matrix name is removed from the BUILD_PLATFORM it needs to be moved to another constant so it is available.
> 
> Some of our downstream distributions already use BUILD_PLATFORM to differentiate their builds. I think this would be very helpful for support (you could tell what distribution someone is using in logs)

I suppose I'll add a new constant `BUILD_ARTIFACT` to hold the matrix name.

**Review by getchoo — APPROVED** [review]
> Some of our downstream distributions already use BUILD_PLATFORM to differentiate their builds. I think this would be very helpful for support (you could tell what distribution someone is using in logs)

yeah i 100% agree with this, it's much better to know what we're dealing with

**Review by DioEgizio — APPROVED** [review]

**Review by Ryex — APPROVED** [review]

**Pull request merged**
