### PR TITLE
refactor(nix): synchronize changes from nixpkgs

### PR DESCRIPTION
**Pull request by Scrumplex**
Updates the nix derivation to mostly match the one in nixpkgs.

See https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/prismlauncher/default.nix

### CODE REVIEW

**Comment by Scrumplex** [comment]
CC @Minion3665

**Review by Minion3665 — APPROVED** [review]
Looks good to me and builds & runs fine

**Comment by DioEgizio** [comment]
why was ninja removed?

**Comment by Scrumplex** [comment]
> why was ninja removed?

It doesn't matter much anyway. It wasn't used in nixpkgs, so I removed it here as well

**Comment by DioEgizio** [comment]
I mean it makes building considerably faster though

**Comment by Scrumplex** [comment]
> I mean it makes building considerably faster though

is it? IIRC nix already sets `-jX` by default so it shouldn't matter much

**Comment by DioEgizio** [comment]
ninja still makes it faster, it's not just make with -jX by default

**Comment by Minion3665** [comment]
We should likely have parity between here and nixpkgs, we could consider adding ninja to nixpkgs instead of removing it from here if that is preferred

**Comment by Scrumplex** [comment]
Looking at [this benchmark](https://david.rothlis.net/ninja-benchmark/) it doesn't seem to matter much for a project the size of Prism Launcher (~1600 .cpp/.h/.ui files)

**Review by flowln — APPROVED** [review]

**Review by DioEgizio — APPROVED** [review]
I guess for now it's fine

**Pull request merged**
