### PR TITLE
fix: only show scrollbars when needed

### PR DESCRIPTION
**Pull request by leia-uwu**

### CODE REVIEW

**Review by flowln — COMMENTED** [review]
my only issue here is with the Notes page, it looks very off without the scrollbar, prob needs some padding to compensate for the lack of scrollbar
Notes text area too close to the border of the dialog

**Comment by leia-uwu** [comment]
image

**Review by Diegiwg — APPROVED** [review]

**Comment by Scrumplex** [comment]
The 6px margin seems hacky. I think different Qt themes might have different margins here, so it could look weird for those.

**Comment by leia-uwu** [comment]
i forgor to run git add :skull:

**Review by Scrumplex — APPROVED** [review]
Fine for me

**Comment by Scrumplex** [comment]
Thanks

**Review by flowln — APPROVED** [review]
thx!

**Pull request merged**
