### PR TITLE
disable sparkle when update url is empty + allow overriding INSTALL_BUNDLE

### PR DESCRIPTION
**Pull request by getchoo**
if `-DMACOSX_SPARKLE_UPDATE_FEED_URL` is set to `""`, sparkle will be completely removed from the build. this allows allows for the fixup_bundle to be overridden.

~~this will also help with building the nix package on mac so pls approve 🥺~~

### CODE REVIEW

**Comment by Scrumplex** [comment]
Alternatively you could also check if the URL is empty in cmake 🤔

**Comment by getchoo** [comment]
imo it makes sense to make it a dedicated option, since like i said it could be used for other platforms in the future - otherwise you would have to do something like `-D<platform>_<framework/name>_URL` depending on what you're building for. a dedicated enable option would make it much easier in that situation, as well as not requiring you to dig a bit into the cmake files to see that just setting the url to a blank string would also work. i think it also falls in line with `Launcher_UPDATER_BASE`, which is unused so far but could also be built upon in the future similar to this

**Comment by Scrumplex** [comment]
I personally like to keep things simple. Unsetting the appcast url means that Sparkle just can not possibly work, while `UPDATER_ENABLE` would just be an arbitrary toggle.

Another issue I see is that we can now have an unexpected state where Sparkle is included but not used because the URL is empty.

**Comment by getchoo** [comment]
> Unsetting the appcast url means that Sparkle just can not possibly work, while UPDATER_ENABLE would just be an arbitrary toggle

yeah that is a good point...i'll change it now

**Comment by getchoo** [comment]
ok this is becoming a bit of a mess, so i'm just going to scrap the pr here and put all the changes required for the nix package into another pr 😆

**Pull request closed without merging**
