### PR TITLE
Allow editing of running instances

### LINKED ISSUE #247: Keep "Settings" available while the instance is running
### Role

I use the launcher.

### Suggestion

I want the settings tab to not be hidden while the instance is running, as those settings only apply on startup and have no effect on runtime.

### Benefit

There's a period of time after the game closes while the instance is still considered running; this suggestion being implemented would allow one to get to adjusting their startup options a second or two earlier (trust, it's way more annoying than you think to wait those few seconds). Also adds consistency to the UI.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### LINKED ISSUE #424: Queue mods to download while instance is still running
### Role

I enjoy spontaneously downloading mods.

### Suggestion

Let mods from the built in mod downloader queue mods for download even if the instance is running.

### Benefit

Less relaunching (see below)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Sometimes you want to download some mods while Minecraft is running, but then you might reopen Minecraft and you suddenly think of another mod to download. This would allow you to keep playing Minecraft while you queue mods to download in the meantime, and when you think that you got a sufficient amount of mods, you could relaunch and they would all load with one relaunch :)

### LINKED ISSUE #505: Allow access to download mods screen while game is running
### Role

I use Prism Launcher to manage multiple modded and vanilla Minecraft instances

### Suggestion

The download mods button in instance settings should be usable while that instance is open

### Benefit

I use a lot of client-side visual or utility mods and sometimes I'll think of a mod that I want to add in the middle of gameplay, but don't care enough to restart my game for it immediately. In those cases, it would be nice to be able to just alt tab over to the launcher and download the mod immediately, instead of having to either manually download it, or wait and then probably forget.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Mods downloaded this way should appear greyed out until the game is closed, or otherwise have some indicator that they aren't loaded yet. Mod updating still wouldn't be available while the game is open, since that requires changing the mods that are already loaded.

### LINKED ISSUE #852: Allow instance (mods) management during execution
### Role

Installing or managing mods

### Suggestion

Allow the normal interactions with download mods/remove/enable/disable while game is running

### Benefit

It would be easier to do things like install missing dependencies or quickly add ideas without needing to close out the game or manual explorer file management

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This may or may not be feasible or realistic. I am not expecting this to actually end up happening, but it would be nice.
Clearly allowing for renamed/deleted jars during runtime is not so straightforward; however, maybe a queued operation could be done? Attempting to remove/disable a mod would change it's checkmark into orange for "will be disabled" or red for "will be removed" or green for "will be enabled" as in "once instance is closed".
This is mostly useful to creating or modifying packs, obviously. But it would be a significant quality of life improvement when trying many different things instead of needing to take notes of "disable these, enable these" between launches.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #424 and fixes #505
And also  fixes #247
One more for the luck: fixes #852

### CODE REVIEW

**Comment by TheKodeToad** [comment]
I remember my single issue on PolyMC for all of this lol (https://web.archive.org/web/20220608121622/https://github.com/PolyMC/PolyMC/issues/756)

Edit: renamed based on that issues name

**Review by getchoo — APPROVED** [review]
works well, even after trying to break it a bit by deleting mods 😆

**Comment by TheKodeToad** [comment]
To my knowledge deleting mods *will* have consequences :p

**Review by Ryex — APPROVED** [review]

**Comment by getchoo** [comment]
> To my knowledge deleting mods _will_ have consequences :p

it won't let you, at least on windows /shrug

**Comment by TheKodeToad** [comment]
*Including on Linux

I can try to demonstrate in the form of a video if that helps

**Comment by TheKodeToad** [comment]
Okay, turns out somehow it's fine to do this on Quilt which is weird since Java loads classfiles lazily normally... however on Fabric it's very easy to reproduce

**Comment by Trial97** [comment]
> Okay, turns out somehow it's fine to do this on Quilt which is weird since Java loads classfiles lazily normally... however on Fabric it's very easy to reproduce

Should I just add a Warning to remove and disable when the game is running?
e.g.  
```
If you remove/disable this resource while the game is running it may crash your game.
Are you sure you want to do this?
Yes | No
```

**Comment by TheKodeToad** [comment]
That seems like the best plan!

**Comment by TheKodeToad** [comment]
It doesn't really apply to resource packs though, I don't believe they can crash your game

**Comment by Trial97** [comment]
Then should this warning only apply to mods?

**Comment by getchoo** [comment]
i think it would be better to be safe than sorry here, especially for any resource packs that might be doing something abnormal - though admittedly there are probably *very* few, if any that could cause this. couldn't hurt though right?

**Comment by TheKodeToad** [comment]
> i think it would be better to be safe than sorry here, especially for any resource packs that might be doing something abnormal - though admittedly there are probably _very_ few, if any that could cause this. couldn't hurt though right?

I'm not sure about abnormal. You may get a few missing textures from disabling a totally innocent resource pack! :woman_shrugging:

**Comment by Trial97** [comment]
> I'm not sure about abnormal. You may get a few missing textures from disabling a totally innocent resource pack! woman_shrugging

I'm more inclined to keep the current approach(I'm too lazy to distinguish between resources).  
But if that is needed for this PR to be accepted I can change it in such a way that only mods get the warning

**Comment by TheKodeToad** [comment]
it's fine - I think this works! it does say `may`. I don't think a resource pack being disabled *can* crash your game but I don't know (if so it's probably a bug).

**Review by TheKodeToad — APPROVED** [review]
I feel like the version page should be unlocked too. You could do that in another PR though!

**Pull request merged**
