### PR TITLE
Renamed inappropriate instances of "PrismLauncher" to "Prism Launcher"

### PR DESCRIPTION
**Pull request by ZombieNub**
- Changed some instances of "PrismLauncher" to "Prism Launcher"

### CODE REVIEW

**Comment by ZombieNub** [comment]
This changes a few instances of PrismLauncher to Prism Launcher. This should correct issue #126, but I haven't been able to test if it actually has. Launcher still works after build, so I don't think this simple renaming has damaged anything.

**Comment by Scrumplex** [comment]
Thanks. The changes you made are for documentation and metadata for Linux desktops

**Review by Scrumplex — APPROVED** [review]

**Comment by ZombieNub** [comment]
Glad to have helped the Linux users!

**Review by flowln — APPROVED** [review]

**Comment by flowln** [comment]
Will conflict with #100 btw. I'll merge that one first since it came first :p

**Comment by ZombieNub** [comment]
Changed the code to resolve the conflict in favor of #100

**Review by Scrumplex — APPROVED** [review]
Thanks again!

**Pull request merged**
