### PR TITLE
Game logs are now encoded in UTF-8

### LINKED ISSUE #2419: Game log isn't encoded with UTF-8
### Operating System

Windows 10 

### Version of Prism Launcher

8.3

### Version of Qt

6.6.3

### Description of bug

When non english characters (in this case, Russian) characters appear in the log (the log within Prism), they appear encoded incorrectly. 

This is copied and pasted from the log
```
[14:52:54] [Render thread/INFO]: [CHAT] Ð¸Ð³Ñ€Ð¾ÐºÐ°, Ð¿Ñ€Ð¸Ð³Ð»Ð°ÑÐ¸Ð²ÑˆÐµÐ³Ð¾ Ð’Ð°Ñ Ð½Ð° ÑÐµÑ€Ð²ÐµÑ€.
[14:52:54] [Render thread/INFO]: [CHAT] 
[14:52:54] [Render thread/INFO]: [CHAT] ÐÐ°Ð³Ñ€Ð°Ð´Ð°: á´‡á´á´‡Ê€á´€ÊŸá´… Ð½Ð° 3 Ð´Ð½Ñ (Ð’Ð°Ð¼ Ð¸ ÐŸÑ€Ð¸Ð³Ð»Ð°ÑÐ¸Ð²ÑˆÐµÐ¼Ñƒ)
[14:52:54] [Render thread/INFO]: [CHAT] Ð•ÑÐ»Ð¸ Ñƒ Ð’Ð°Ñ ÑƒÐ¶Ðµ ÐµÑÑ‚ÑŒ á´‡á´á´‡Ê€á´€ÊŸá´…, Ñ‚Ð¾Ð³Ð´Ð°
```

### Steps to reproduce

1. Copy and paste something in russian in chat
2. Open Prism log
3. See how the chat message appears incorrectly

### Suspected cause

I suspect the log isn't using UTF-8 like it should be.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by marrrrrrme6**
fix #2419

### CODE REVIEW

**Comment by TayouVR** [comment]
question is, if that breaks any other codepoints? if someone has their OS set to e.g. that asian one, would that break the logs then if we decode it as UTF-8?
https://github.com/PolyMC/PolyMC/pull/968
https://github.com/PrismLauncher/PrismLauncher/commit/3c4b45c9e76db3373baccefda59bae01c460df28

**Comment by marrrrrrme6** [comment]
For now, I've added `-Dfile.encoding=UTF-8` and tested Japanese.
There were no problems with Japanese.
I don't understand other languages ​​such as Chinese, so could you please test them for me?

**Comment by marrrrrrme6** [comment]
The following tests were done on minecraft 1.12.2 and 1.21.1. In 1.12.2, `-Dfile.encoding=UTF-8` was added to the arguments.

The issue of garbled characters in sections (§) has been resolved.
1.21.1:
image
1.12.2:
image
MultiMC/Launcher#5435

Chinese, accent aigu and Russian are also no problem.
1.21.1:
image
1.12.2:
image
https://github.com/PolyMC/PolyMC/pull/968#issuecomment-1204597793
MultiMC/Launcher#2998

Special characters are no problem.
1.21.1:
image
1.12.2:
image
PolyMC/PolyMC#806

Use utf-8 is not checked. https://github.com/PolyMC/PolyMC/pull/968#issuecomment-1214176882

**Comment by Ryex** [comment]
Wasn't there an issue with using UTF-8 in 1.7 and earlier?
we do want to support those early versions too.

**Comment by marrrrrrme6** [comment]
Everything was fine.
I couldn't enter §.
I also tried 1.2.5 and b1.7.3 but the chat wouldn't open.

1.7.10:
image

1.5.2:
image

1.3.2:
image

**Comment by Ryex** [comment]
huh. I could have sworn this was brought up before and it broke things...
let's ask @Scrumplex. He has a better memory of the project.

**Comment by Scrumplex** [comment]
> He has a better memory of the project.

I sadly dont remember

**Comment by Ryex** [comment]
alright well, if we're going to add this, `-Dfile.encoding=UTF-8` needs to be added as a default java argument or this actually *will* break things.

**Comment by TayouVR** [comment]
forgot to send this comment yesterday as I was thinking of asking for some feedback on discord...

> then it sounds like the launcher should automatically add that flag.
> But I'm not sure if that could cause any issues for anyone

from what you are describing it seems that this should work even with older versions without any issues, so I suppose its fine to blanket apply the flag to every version. 
But I'm still skeptical of it working in some really early versions.

I was thinking if we could have a toggle in the settings "Use UTF-8 for log files", which both adds the launch flag and configures the log reader to use UTF-8 instead of the system charset
But I would need other peoples opinions on this.
I'm gonna ask for some input on discord, see if anyone maybe has more to say about this topic

**Comment by marrrrrrme6** [comment]
> alright well, if we're going to add this, `-Dfile.encoding=UTF-8` needs to be added as a default java argument or this actually _will_ break things.

In https://github.com/marrrrrrme6/PrismLauncher/tree/test, I add `-Dfile.encoding=UTF-8` to the default arguments, but I'm not sure if this is ok.

**Comment by TheKodeToad** [comment]
> alright well, if we're going to add this, `-Dfile.encoding=UTF-8` needs to be added as a default java argument or this actually _will_ break things.

This will potentially break things too. Since this also controls the encoding for loading files (at least I think it does and the name suggests that) it could mean loading files encoded differently as utf-8...

**Comment by marrrrrrme6** [comment]
I am not originally a C++ engineer, and I modified it based on https://github.com/PrismLauncher/PrismLauncher/issues/2419#issuecomment-2171762795, but I don't know any more about it than that, so I would like someone to take over.

**Comment by TheKodeToad** [comment]
Alright... closing this then

**Pull request closed without merging**
