### PR TITLE
Translate standard buttons

### LINKED ISSUE #2833: StandardButtons ignore selected language
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4, develop at dc678078940d04202e00c62dbf40357358dc4ef3

### Version of Qt

Qt 6.7.1 (stable), Qt 6.7.2 (develop)

### Description of bug

When selecting a different language, the standard buttons provided by Qt should also be translated. This is not the case.

GPUyBxM4R7ZA7mTd

### Steps to reproduce

* Change Prism's language to something other than English
* Observe that the StandardButtons do not get translated appropriately

### Suspected cause

These translation files are not present.
https://github.com/PrismLauncher/PrismLauncher/blob/dc678078940d04202e00c62dbf40357358dc4ef3/launcher/translations/TranslationsModel.cpp#L481-L490

(Code itself works, tested by manually placing the appropriate files there.)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #2833

### CODE REVIEW

**Review by TayouVR — APPROVED** [review]

**Comment by TayouVR** [comment]
build failures? hmmmmmm 
I can compile locally just fine

**Review by Kationor — CHANGES_REQUESTED** [review]
I feel like Prism should just ship the Qt translations along with its own. That way, we cannot miss any cases of Qt strings not getting translated. (example I just found: the context menu in the http renderer used when downloading mods)
grafik

**Review by Ryex — APPROVED** [review]

**Comment by Trial97** [comment]
@Kationor I don't have a good way for what you want: somehow include all qt strings inside our translation.
The files mentioned in the issue https://github.com/Trial97/PrismLauncher/blob/872df044708c0553154b3f9d5362b38386956aa6/launcher/translations/TranslationsModel.cpp#L479-L491 should be provided by your distribution

Another approach that I took into consideration was to download them from https://code.qt.io/cgit/qt/qttranslations.git/. Still, in this case not all languages(that Prism supports) are translated and there isn't a way to isolate a language so we would need to download I presume all the repository.

From my limited search, I could not find a way to generate the qt translation strings to add them to our translation repo(for users to translate them too).

So if you know how to do it feel free to PR it or at least suggest a viable alternative

**Comment by Kationor** [comment]
@Trial97 Embedding pre-existing Qt translations within the translation files Prism already ships should be pretty simple in terms of implementation (I haven't looked at licensing issues yet). 
You would just need to grab the corresponding translation from the repo you've already pointed out, combine it with Prism's translations using `lconvert`, and then ship the combined translations instead of just our own translations.
There are other options as well, but this particular one wouldn't need any launcher-side code changes (only changes to the translation generation scripts)

If this approach is used, it's mostly a problem for the Translations repo.

**Comment by Trial97** [comment]
@Kationor like this: https://github.com/PrismLauncher/Translations/pull/19

**Comment by Trial97** [comment]
I will merge this but as a better fix we have the translation PR mentioned.

**Pull request merged**
