### PR TITLE
Add flat white icons

### LINKED ISSUE #516: [Suggestion] White Flat Icons
### Role

I use the QT dark mode and a custom QT dark theme on Linux.

### Suggestion

I want there to be a white version of the flat icons.

### Benefit

I would no longer have to manually install my icon theme and it would be nicer to have an actual name for it in the icon theme selector instead of 'Custom'.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have made an icon theme that already modifies all of the flat icons to be a nice white colour, which fits in well with the dark colour scheme.

Link: https://cdn.discordapp.com/attachments/694176292995858492/970374862868738098/custom.zip

### PR DESCRIPTION
**Pull request by he3als**
This is mainly for dark mode users, as I think that the regular colour of the flat icons do not look good with dark mode.

Fixes https://github.com/PolyMC/PolyMC/issues/516

**Note:** I just assumed that you can make a folder in the resources folder and a new icon pack will get added.

image

### CODE REVIEW

**Review by Lutitious — APPROVED** [review]

**Comment by DioEgizio** [comment]
please [sign off your commits](https://github.com/PrismLauncher/PrismLauncher/blob/develop/CONTRIBUTING.md)

**Comment by he3als** [comment]
sorry, i use github desktop and i am not too sure how to. i will look into it though. i did just replace the colour value in each file with notepad++ though, so ye i edited it lol

**Review by AurorusFur — APPROVED** [review]

**Review by Desoroxxx — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]
Preliminary review: looks good!

**Review by ryanccn — APPROVED** [review]

**Comment by flowln** [comment]
this doesn't seem to be selectable from the UI though? At least it doesn't show up in my end :thinking:

**Comment by Scrumplex** [comment]
> this doesn't seem to be selectable from the UI though? At least it doesn't show up in my end thinking

yep

**Comment by Scrumplex** [comment]
Can you apply this patch? @he3als 

```patch
From 77f7779bef23180714dfef123031ae15ead89598 Mon Sep 17 00:00:00 2001
From: Sefa Eyeoglu <contact@scrumplex.net>
Date: Sat, 22 Oct 2022 15:27:46 +0200
Subject: [PATCH] fix: add flat_white to code

Signed-off-by: Sefa Eyeoglu <contact@scrumplex.net>
---
 launcher/CMakeLists.txt                   |  1 +
 launcher/main.cpp                         |  1 +
 launcher/resources/flat_white/index.theme |  2 +-
 launcher/ui/pages/global/LauncherPage.cpp | 13 ++++++++++---
 launcher/ui/pages/global/LauncherPage.ui  |  5 +++++
 5 files changed, 18 insertions(+), 4 deletions(-)

diff --git a/launcher/CMakeLists.txt b/launcher/CMakeLists.txt
index 6ad91a85..e3945a47 100644
--- a/launcher/CMakeLists.txt
+++ b/launcher/CMakeLists.txt
@@ -602,6 +602,7 @@ SET(LAUNCHER_SOURCES
     resources/OSX/OSX.qrc
     resources/iOS/iOS.qrc
     resources/flat/flat.qrc
+    resources/flat_white/flat_white.qrc
     resources/documents/documents.qrc
     ../${Launcher_Branding_LogoQRC}
 
diff --git a/launcher/main.cpp b/launcher/main.cpp
index c6a7614c..e2116f38 100644
--- a/launcher/main.cpp
+++ b/launcher/main.cpp
@@ -84,6 +84,7 @@ int main(int argc, char *argv[])
         Q_INIT_RESOURCE(OSX);
         Q_INIT_RESOURCE(iOS);
         Q_INIT_RESOURCE(flat);
+        Q_INIT_RESOURCE(flat_white);
         return app.exec();
     }
     case Application::Failed:
diff --git a/launcher/resources/flat_white/index.theme b/launcher/resources/flat_white/index.theme
index a0b3ba6f..0292509f 100644
--- a/launcher/resources/flat_white/index.theme
+++ b/launcher/resources/flat_white/index.theme
@@ -1,5 +1,5 @@
 [Icon Theme]
-Name=White Flat
+Name=Flat (White)
 Comment=White version of the flat icons (for dark mode)
 Inherits=multimc
 Directories=scalable
diff --git a/launcher/ui/pages/global/LauncherPage.cpp b/launcher/ui/pages/global/LauncherPage.cpp
index 1e5df5b2..a91b6bbc 100644
--- a/launcher/ui/pages/global/LauncherPage.cpp
+++ b/launcher/ui/pages/global/LauncherPage.cpp
@@ -310,9 +310,12 @@ void LauncherPage::applySettings()
         s->set("IconTheme", "flat");
         break;
     case 7:
-        s->set("IconTheme", "multimc");
+        s->set("IconTheme", "flat_white");
         break;
     case 8:
+        s->set("IconTheme", "multimc");
+        break;
+    case 9:
         s->set("IconTheme", "custom");
         break;
     }
@@ -408,14 +411,18 @@ void LauncherPage::loadSettings()
     {
         ui->themeComboBox->setCurrentIndex(6);
     }
-    else if (theme == "multimc")
+    else if (theme == "flat_white")
     {
         ui->themeComboBox->setCurrentIndex(7);
     }
-    else if (theme == "custom")
+    else if (theme == "multimc")
     {
         ui->themeComboBox->setCurrentIndex(8);
     }
+    else if (theme == "custom")
+    {
+        ui->themeComboBox->setCurrentIndex(9);
+    }
 
     {
         auto currentTheme = s->get("ApplicationTheme").toString();
diff --git a/launcher/ui/pages/global/LauncherPage.ui b/launcher/ui/pages/global/LauncherPage.ui
index 0d14f147..76a25f2e 100644
--- a/launcher/ui/pages/global/LauncherPage.ui
+++ b/launcher/ui/pages/global/LauncherPage.ui
@@ -300,6 +300,11 @@
               <string>Flat</string>
              </property>
             </item>
+            <item>
+             <property name="text">
+              <string>Flat (White)</string>
+             </property>
+            </item>
             <item>
              <property name="text">
               <string>Legacy</string>
-- 
2.38.1

```

**Review by Scrumplex — CHANGES_REQUESTED** [review]
This now needs some new icons: `delete` `export` `rename` `tag`.

See https://github.com/PrismLauncher/PrismLauncher/pull/187

**Comment by flowln** [comment]
@Scrumplex i think there's some things missing in your patch:

Should also add the qrc file [here](https://github.com/PrismLauncher/PrismLauncher/blob/2ec43101043885b124a0870b30afd35074f79e35/launcher/CMakeLists.txt#L960) too I think.
`white_flat` -> `flat_white` in `LauncherPage::loadSettings()` to keep similar to other instances.

**Comment by Scrumplex** [comment]
> @Scrumplex i think there's some things missing in your patch:
> 
> Should also add the qrc file [here](https://github.com/PrismLauncher/PrismLauncher/blob/2ec43101043885b124a0870b30afd35074f79e35/launcher/CMakeLists.txt#L960) too I think. `white_flat` -> `flat_white` in `LauncherPage::loadSettings()` to keep similar to other instances.

Thanks! Fixed now. My comment above is up-to-date.

**Comment by he3als** [comment]
Sorry for not signing off the commits, I am a noob to Git (although, I am going to switch over to it and learn it instead of GitHub Desktop) and I forgot to.

Thank you for fixing the PR though, I assumed that it would automatically be added as when I searched up some of the included icon themes with GitHub's search, it had no results. I guess it is just not great at finding stuff

**Comment by Scrumplex** [comment]
You can try running `git rebase --signoff develop` to sign all your commits (after that do a force push: `git push --force`

**Comment by he3als** [comment]
Would that break anything though? Should I do the preferred method instead?

https://github.com/PrismLauncher/PrismLauncher/pull/65/checks?check_run_id=9047071415

**Comment by he3als** [comment]
Should be good now.

**Review by flowln — APPROVED** [review]
it looks mostly fine. thanks!

please see Scrumplex's comment though: https://github.com/PrismLauncher/PrismLauncher/pull/65#pullrequestreview-1151972430

**Comment by he3als** [comment]
I have added the new icons

**Comment by flowln** [comment]
oh. I think you forgot to add them to the qrc file :p

**Comment by he3als** [comment]
whoops...

**Review by Scrumplex — COMMENTED** [review]
`tag.svg` and `delete.svg` are gray, not white.

Also you forgot to add the new icons to the .qrc file

**Comment by he3als** [comment]
It should actually be good now... I am sorry, this pull request is a bit of a mess (due to me)...

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
Thanks!

**Pull request merged**
