### PR TITLE
Fix mod list text clipping

### LINKED ISSUE #20: Mod Downloader Font Sizes
The font sizes in the mod downloader are disproportionate. https://imgur.com/a/zQOeuvM
(Running Fedora 36 KDE Edition [X11], Kernel Version 5.19.15)

Also, is CurseForge support going to be added in the near future? (needing to apply for new api key)

### PR DESCRIPTION
**Pull request by Sebbl0508**
Fix issue in #20

### CODE REVIEW

**Comment by flowln** [comment]
image
'g's, 'p's and other long letters get cut off with this, because you reduced the padding :/

**Comment by Sebbl0508** [comment]
Yeah, i have no idea about QT. I'll try to fix it

**Comment by flowln** [comment]
Now there's no clipping, but the text is still too close to the bottom, it looks too close to the title from item below. That's why the `2.2*` was there for. I suppose the issue in #20 happens because the custom theme makes the item look smaller, so the math used here doesn't work out, and changing the height of the description `rect`doesn't look right (why does it work?).

I propose we instead center the text on the remaining height, from the bottom of the rect to the bottom of the title text. I made a patch for that, you can have a look, and make any changes you feel need to be done to it (or maybe it doesn't fix the issue at all, i wasn't able to reproduce it):

```patch
From 11801ab00753dda5ab5267b2b603964b8476a498 Mon Sep 17 00:00:00 2001
From: flow <flowlnlnln@gmail.com>
Date: Tue, 18 Oct 2022 15:13:02 -0300
Subject: [PATCH] fix: properly center project descriptions

In particular, this takes into account the space used by the title, so
(hopefully) there won't be problems with custom themes with that.

Signed-off-by: flow <flowlnlnln@gmail.com>
---
 launcher/ui/widgets/ProjectItem.cpp | 20 +++++++++++++++++---
 1 file changed, 17 insertions(+), 3 deletions(-)

diff --git a/launcher/ui/widgets/ProjectItem.cpp b/launcher/ui/widgets/ProjectItem.cpp
index 93d3fca1..1011d6e4 100644
--- a/launcher/ui/widgets/ProjectItem.cpp
+++ b/launcher/ui/widgets/ProjectItem.cpp
@@ -51,6 +51,8 @@ void ProjectItemDelegate::paint(QPainter* painter, const QStyleOptionViewItem& o
     auto remaining_width = rect.width() - icon_width - 2 * icon_x_margin;
     rect.setRect(rect.x() + icon_width + 2 * icon_x_margin, rect.y(), remaining_width, rect.height());
 
+    int title_height = 0;
+
     {  // Title painting
         auto title = index.data(UserDataTypes::TITLE).toString();
 
@@ -66,8 +68,10 @@ void ProjectItemDelegate::paint(QPainter* painter, const QStyleOptionViewItem& o
         font.setPointSize(font.pointSize() + 2);
         painter->setFont(font);
 
+        title_height = QFontMetrics(font).height();
+
         // On the top, aligned to the left after the icon
-        painter->drawText(rect.x(), rect.y() + QFontMetrics(font).height(), title);
+        painter->drawText(rect.x(), rect.y() + title_height, title);
 
         painter->restore();
     }
@@ -90,9 +94,19 @@ void ProjectItemDelegate::paint(QPainter* painter, const QStyleOptionViewItem& o
                 description += cut_text.at(1).second;
         }
 
+        int description_x = rect.x();
+
+        // Have the y-value be set based on the number of lines in the description, to centralize the
+        // description text with the space between the base and the title.
+        int description_y = rect.y() + title_height + (rect.height() - title_height) / 2;
+        if (cut_text.size() == 1)
+            description_y -= opt.fontMetrics.height() / 2;
+        else
+            description_y -= opt.fontMetrics.height();
+
         // On the bottom, aligned to the left after the icon, and featuring at most two lines of text (with some margin space to spare)
-        painter->drawText(rect.x(), rect.y() + rect.height() - 2.0 * opt.fontMetrics.height(), remaining_width,
-                          4 * opt.fontMetrics.height(), Qt::TextWordWrap, description);
+        painter->drawText(description_x, description_y, remaining_width,
+                          cut_text.size() * opt.fontMetrics.height(), Qt::TextWordWrap, description);
     }
 
     painter->restore();
-- 
2.38.0
```

**Comment by Scrumplex** [comment]
@Sebbl0508 can you run `git rebase HEAD~3 --signoff` and `git push --force` to comply with the DCO bot?

**Comment by Sebbl0508** [comment]
Oh no  
  
Edit:  
`git rebase HEAD~3 --signoff` rebases about 16 commits because i merged upstream into this branch, and puts my signature on them.

**Comment by Sebbl0508** [comment]
Nvm, think i fixed it

**Comment by Sebbl0508** [comment]
I tested the current fix, and on my laptop (which has x1.25 font scaling set up in gnome tweaks) it's still clipped  
https://i.imgur.com/a/UYKg2ne.png

**Comment by flowln** [comment]
> I tested the current fix, and on my laptop (which has x1.25 font scaling set up in gnome tweaks) it's still clipped [i.imgur.com/a/UYKg2ne.png](https://i.imgur.com/a/UYKg2ne.png)

yea there's no space for two lines no matter what. what could be done in this case would be checking if the two lines height is less then or equal to the space between the title and the bottom, and if it is less, we use only a single line.

**Comment by Sebbl0508** [comment]
This fix now draws the descriptions with only a single line on my laptop with font scaling.  
I still have to check if this works for normal scaling on my PC.

**Comment by forkiesassds** [comment]
> This fix now draws the descriptions with only a single line on my laptop with font scaling. I still have to check if this works for normal scaling on my PC. 

It shouldn't end abruptly and instead end with 3 dots

**Comment by flowln** [comment]
_now_ it should be fixed for good :p 
@Sebbl0508 can you check if this is right for you?

**Comment by Sebbl0508** [comment]
Looks good on my laptop now, thanks!

**Review by flowln — APPROVED** [review]
thank you! team work ftw :fist_oncoming:

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
Thanks!

**Pull request merged**
