### PR TITLE
fix a minor spelling error in Mod.cpp

### LINKED ISSUE #2047: just a simple spellfix
"form" should be "from"
https://github.com/PrismLauncher/PrismLauncher/blob/4cda04271fd615657e1eed7a32f791cbcdcbea76/launcher/minecraft/mod/Mod.cpp#L277

### PR DESCRIPTION
**Pull request by erikLundstedt**
closes https://github.com/PrismLauncher/PrismLauncher/issues/2047

### CODE REVIEW

**Review by TheKodeToad — APPROVED** [review]
Thank you! Honestly, these things aren't exactly high priority and I don't think an issue was needed lol

**Review by TheKodeToad — CHANGES_REQUESTED** [review]
Oh, I can see several other grammar errors now. TBH I don't think it's worth fixing them but if you want that's fine I guess...

**Comment by erikLundstedt** [comment]
> Thank you! Honestly, these things aren't exactly high priority and I don't think an issue was needed lol

no worries

I just noticed when opening the terminal-emulator where I started the program from.
I cant really donate money to foss projects, even ones that I use almost daily, as I need the money for things like food, but when I notice something this simple,I do like to contribute, it's the spirit of open source, isn't it
:-)

**Comment by erikLundstedt** [comment]
> Oh, I can see several other grammar errors now. TBH I don't think it's worth fixing them but if you want that's fine I guess...

I can take a look tomorrow

I have no "real" experience with C++ but fixing spelling mistakes where I see them is pretty nice, and I like to contribute what I can

**Comment by TheKodeToad** [comment]
> > Thank you! Honestly, these things aren't exactly high priority and I don't think an issue was needed lol
> 
> no worries
> 
> I just noticed when opening the terminal-emulator where I started the program from. I cant really donate money to foss projects, even ones that I use almost daily, as I need the money for things like food, but when I notice something this simple,I do like to contribute, it's the spirit of open source, isn't it :-)

Oh, I can see why it'd be annoying in that context :P I just feel like there are *many* other typos and it's probably not worth your time, or anyone else's, to fix all of them.

**Comment by erikLundstedt** [comment]
> > > Thank you! Honestly, these things aren't exactly high priority and I don't think an issue was needed lol
> > 
> > 
> > no worries
> > I just noticed when opening the terminal-emulator where I started the program from. I cant really donate money to foss projects, even ones that I use almost daily, as I need the money for things like food, but when I notice something this simple,I do like to contribute, it's the spirit of open source, isn't it :-)
> 
> Oh, I can see why it'd be annoying in that context :P I just feel like there are _many_ other typos and it's probably not worth your time, or anyone else's, to fix all of them.

honestly, because I like FOSS stuff(all/most of my own code is GPLv2 compatible), but don't have any c++ knowledge(I did learn java in high-school and I work with programming at my day-job) I do like to contribute what I can, the one other project I have actually contributed to is the README.md of my terminal emulator

I am just happy about being able to contribute something at all
I might end up taking a look tomorrow for "fun", I was planning on reinstalling my PC(I usually do once a year), so im gonna have a bit of "downtime", where I can sit with my laptop and look for stuff to fix, again, I really just like being able to contribute anything at all to a project I use a whole lot

**Review by Trial97 — APPROVED** [review]

**Comment by Trial97** [comment]
@TheKodeToad are you ok with just merging this without the other fixes that you mentioned here: https://github.com/PrismLauncher/PrismLauncher/pull/2048#pullrequestreview-1834743398 .
It looks like there no updates for some time and in case they come back they can open a new PR.

**Review by TheKodeToad — APPROVED** [review]

**Pull request merged**
