### PR TITLE
Remove blue-ish tint from flat white icons

### PR DESCRIPTION
**Pull request by ghost**
Remove the blue-ish tint from flat-white icon theme in order to make it match with the current dark theme.
I believe the original author made it for the old theme, where it looked fine but looks off in the current state.
Replaced the original color with #eeeeee

### CODE REVIEW

**Comment by ghost** [comment]
obraz

**Comment by ghost** [comment]
why the hell would it fail

**Comment by DioEgizio** [comment]
> why the hell would it fail

github actions being github actions and randomly breaking

**Comment by Scrumplex** [comment]
CC @he3als

**Review by TheKodeToad — APPROVED** [review]
Haven't checked fully, but it seems all the files are changed.

**Comment by he3als** [comment]
I do not mind if it is replaced, I prefer the tint personally though.

**Review by Scrumplex — APPROVED** [review]

**Comment by DioEgizio** [comment]
now that #521 is merged, shouldn't shortcut.svg also get unblued?

**Review by DioEgizio — APPROVED** [review]

**Comment by ghost** [comment]
Sorry for not doing this myself, I've been busy with real life for a bit and kept forgetting. Thanks :p

**Pull request merged**
