### PR TITLE
Replace http with https on skins

### LINKED ISSUE #2928: Skins api not responding to HTTP requests making launcher hang for a minute
### Operating System

Windows, macOS, Linux, Other

### Version of Prism Launcher

8.4 Flatpak

### Version of Qt

Qt 6.7.3

### Description of bug

Unable to launch any instance, hangs on "Fetching the Minecraft profile"

Player head images are missing (defaults to grayscale one)

image

### Steps to reproduce

Start launcher
Attempt to start an instance

### Suspected cause

For me recently skins API simply does not respond to HTTP requests rendering my bot fleet unable to fetch player head (skin) images. Fixed it by finding and replacing first `http://` with `https://` prior to executing request.

Servers and other locations however still provide non-https links.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #2928
Should work with https but I don't know if this will break on other systems or not

### CODE REVIEW

**Comment by maxsupermanhd** [comment]
Probably not terrible idea to put it behind a settings toggle just to avoid regression

**Comment by Trial97** [comment]
@maxsupermanhd This seems like a change that we either have or not, as I'm pretty sure most users wouldn't know what it is or for what it is used.

**Comment by maxsupermanhd** [comment]
Fair point here but is it really that much more clutter/work to implement a toggle that can potentially save some people from regression if they encounter it?

In some sense that might actually be a *me* problem now that I think about it, can't deny something is wrong with auth servers and maybe it's affecting skins service too. Note how there is 0 people that came in with same problem. I use quiet heavy request tampering on router level to bypass government black boxes and I am in Russia so think of that what you will.

**Review by getchoo — APPROVED** [review]
I'm not sure what would regress here. If you're able to play Minecraft, you should be able to make HTTPS requests to minecraft.net. If the `textures` subdomain is the only one causing issues, I doubt it would be an issue of preferring HTTPS at all

**Review by Ryex — APPROVED** [review]

**Review by TayouVR — APPROVED** [review]

**Pull request merged**
