### PR TITLE
fixed squished mod icons

### LINKED ISSUE #1736: List views with icons are squished if the first element has no icon
### Operating System

_No response_

### Version of Prism Launcher

[Prism Launcher 8.0, taken from this action](https://github.com/PrismLauncher/PrismLauncher/actions/runs/6587530293)

### Version of Qt

Qt 6.6.0

### Description of bug

In the mod/resourceshader menus, if the first element in the list lacks an icon, all other elements are squished.

image

image

### Steps to reproduce

- Create a new instance
- Add two resource packs to it: one with an icon, and one without
- Sort the packs in various ways so they change their order.

### Suspected cause

The list elements lack a minimum height parameter, and inherit the one from the topmost list element instead

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #1736

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Long icons are cut off 
image
I think they should be offset to the left

**Comment by TheKodeToad** [comment]
they should probably just be scaled into a square
or just moved into the name column

**Comment by Desoroxxx** [comment]
> they should probably just be scaled into a square or just moved into the name column

I feel like the padding of the checkbox is unnecessary, so just reducing that and making them offset compared to the rest would fix the issue without making them super small

**Comment by TayouVR** [comment]
@Desoroxxx while the first column has a fixed with, you can just move the column headers around (make wider or smaller). Make the image column wider to see the full image.
we could make the column automatically adjust size based on the largest image, but with how large some images are that can end up looking quite silly..

**Comment by Desoroxxx** [comment]
> @Desoroxxx while the first column has a fixed with, you can just move the column headers around (make wider or smaller). Make the image column wider to see the full image. we could make the column automatically adjust size based on the largest image, but with how large some images are that can end up looking quite silly..

Oh, yeah, although I do not remember resizing the checkbox collum, maybe it's default size should be checked

**Comment by Desoroxxx** [comment]
> Oh, yeah, although I do not remember resizing the checkbox collum, maybe it's default size should be checked

I misread, but my original point still stand, why is the enabled column 3 times bigger than the checkbox it contains

**Comment by TayouVR** [comment]
> why is the enabled column 3 times bigger than the checkbox it contains

because the header is that wide.

**Comment by Trial97** [comment]
Now this fixes resource packs and texture packs.
This only fixes the height as the width of the mods icon is not a standard square.
Neoforge and Forge do not want to restrict the mod author

**Comment by TayouVR** [comment]
The rows need to be resized when hiding/showing the image column. the size hint already applies to the column specifically, but the row height doesn't update when the column is gone, currently.

**Comment by Trial97** [comment]
> The rows need to be resized when hiding/showing the image column. the size hint already applies to the column specifically, but the row height doesn't update when the column is gone, currently.

This should already happen. It may need a trigger(like sorting after a column) if you just disabled the column(some qt wankines).

**Comment by TayouVR** [comment]
I didn't try sorting, just toggling visibility of the image column. 
I do know toggling the column off, then closing the window and re-opening it fixes it, just toggling the column specifically doesn't resize the rows... 

I guess you would have to trigger a redraw or some other signal to make Qt realize that changes have happened and it needs to update. Not sure how to do it. guess its still better than how it was before, so I'm gonna approve ^^

**Review by TayouVR — APPROVED** [review]

**Comment by Desoroxxx** [comment]
Is this getting merged soon?

**Comment by TayouVR** [comment]
when we get a second approval, yes.

**Review by TheKodeToad — APPROVED** [review]
if it works

**Pull request merged**
