### PR TITLE
Do not automatically add Fabric if Quilt is in use

### LINKED ISSUE #818: Make prism launcher detect their respective loader if there's multiple loader versions on an update
### Role

I play modded Minecraft

### Suggestion

make prism launcher detect their respective loader if there's multiple loader versions on an update

### Benefit

So that if a mod has multiple loader versions for the same Minecraft version it won't crash

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

when installing a mod that has multiple loader versions for one Minecraft version, prism launcher just chooses the latest released version. For example on the wyntils mod they have forge, fabric, and quilt for 1.19.3. Each for their respective loaders. However when I update it on quilt it does the most recent which is fabric. If there was maybe a drop down menu to choose or if the launcher detected the correct version it'd help players with that problem

### PR DESCRIPTION
**Pull request by BalkanMadman**
Fix https://github.com/PrismLauncher/PrismLauncher/issues/818

Signed-off-by: BalkanMadman <zurabid2016@gmail.com>

### CODE REVIEW

**Comment by BalkanMadman** [comment]
Just thought about it and it will definitely break current behaviour (since Quilt more or less supports Fabric mods, which would get filtered out by this commit.)

**Comment by BalkanMadman** [comment]
Technically we could filter out fabric-only versions of mods which support quilt. But that leads to another concern — what if end user wants the fabric version for some reason.
Another "fix" might be to let launcher update to that versions of the mods (which support Quilt) who explicitly advertise their support for it and, maybe present users with an option: latest version (which, per API, may support only Fabric) or version which explicitly support Quilt.    

What I mean is that Prism (for Quilt instances) could use the latest version for Fabric-only mods and the version which explicitly supports Quilt for mods which advertise such support

**Comment by BalkanMadman** [comment]
I am not a programmer and definitely not a UI guy. Will talk about this one with devs on Discord

**Comment by TayouVR** [comment]
as we expand on the mod browsing UI there should be a plethora of filters, including mod loaders. Then users can restrict their mods to only fabric, only quilt or both, and if the user were to choose a incompatible modloader either thats not possible or there'd be a fat warning

**Pull request closed without merging**
