### PR TITLE
Improve code readability

### PR DESCRIPTION
**Pull request by Scrumplex**

### CODE REVIEW

**Review by TheKodeToad — APPROVED** [review]
No more worrying about naming conventions!

**Comment by DioEgizio** [comment]
:trollface:

**Review by DioEgizio — CHANGES_REQUESTED** [review]
no fun

**Comment by Scrumplex** [comment]
Dang. I forgot to update the license headers.

**Comment by Scrumplex** [comment]
Oops wrong button




/s

**Comment by TheKodeToad** [comment]
Actually serious: *please* CODE_STYLE.md and clangd reformat.

**Pull request closed without merging**
