### PR TITLE
Update developers

### PR DESCRIPTION
**Pull request by TheKodeToad**
I hope I did this right :P

### CODE REVIEW

**Review by getchoo — APPROVED** [review]

**Comment by getchoo** [comment]
omg it me

**Review by Ryex — APPROVED** [review]

**Comment by TheKodeToad** [comment]
Btw, I thought it was okay to keep flow as she has done so much :p

**Comment by Scrumplex** [comment]
Maybe we could also just sort this alphabetically to not favor anyone over another

**Comment by TheKodeToad** [comment]
I tried to do it in order of people being granted org membership. I couldn't remember if tayou or ryex came first though :p

**Pull request merged**
