### PR TITLE
New instance icons

### PR DESCRIPTION
**Pull request by felinusfish**
Cool new icons. 🍆🥚

Fish will add screenshots later

~Scrumplex

### CODE REVIEW

**Comment by Scrumplex** [comment]
@ZekeSmith we are gonna need someone to fix these SVGs. Adobe's Figma sucks apparently

**Comment by AwesomeQubic** [comment]
10/10 description I approve

**Comment by theofficialgman** [comment]
> @ZekeSmith we are gonna need someone to fix these SVGs. Adobe's Figma sucks apparently

what is the issue with the svgs?

**Comment by Scrumplex** [comment]
> > @ZekeSmith we are gonna need someone to fix these SVGs. Adobe's Figma sucks apparently
> 
> what is the issue with the svgs?

Just try them in the launcher. The masks don't work with Qt's SVG renderer, which is why most don't have rounded corners

**Comment by theofficialgman** [comment]
I see... qt needs SVG Tiny 1.2 compatible files only.

**Comment by felinusfish** [comment]
I would work on them, but I've been banned from the Discord server so I have no way to ask for any help on this

**Comment by theofficialgman** [comment]
> I would work on them, but I've been banned from the Discord server so I have no way to ask for any help on this

I think I already gave you all the information that you need. SVG tiny 1.2 doesn't support masking which your current SVGs utilize to round the outer corners. If your software supports exporting as SVG tiny 1.2 compatible then that might be all you need to do. Otherwise you will have to change the svgs manually to not use masking but still achieve the same effect.

maybe the suggestions here might help you: https://bugreports.qt.io/browse/QTBUG-28636?focusedCommentId=192782&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-192782

**Comment by theofficialgman** [comment]
I have successfully converted one svg to not use masks... the embedded image was made with the help of illustrator and manually merging paths together


Note, its very convenient to use dolphin file manager to preview the SVGs (since it has the same limitations)
I think I can manually edit the remaining SVGs which should be faster, this is my attempt:

```
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect width="16" height="16" rx="3" fill="#D9AA81"/>
<rect width="16" height="16" rx="3" fill="url(#paint0_linear_47_622)"/>
<rect x="2" y="6" width="2" height="2" fill="white"/>
<rect x="12" y="6" width="2" height="2" fill="white"/>
<rect x="4" y="8" width="8" height="2" fill="#F0B98F"/>
<rect x="6" y="14" width="4" height="2" fill="#B67748"/>
<rect x="4" y="10" width="2" height="4" fill="#86352A"/>
<rect x="10" y="10" width="2" height="4" fill="#86352A"/>
<path fill="#E3C894" d="M4,14v-2H2v3.8C2.3,15.9,2.6,16,3,16h3v-2H4z"/>
<path fill="#E3C894" d="M14,12h-2v2h-2v2h3c0.4,0,0.7-0.1,1-0.2V12z"/>
<rect x="2" y="8" width="2" height="2" fill="#BD7454"/>
<rect x="12" y="8" width="2" height="2" fill="#BD7454"/>
<path fill="#BD7454" d="M14,15.8c1.2-0.4,2-1.5,2-2.8v-3h-2V15.8z"/>
<path fill="#BD7454" d="M2,15.8V10H0v3C0,14.3,0.8,15.4,2,15.8z"/>
<defs>
<linearGradient id="paint0_linear_47_622" x1="8" y1="0" x2="8" y2="16" gradientUnits="userSpaceOnUse">
<stop stop-color="#D19B73"/>
<stop offset="1" stop-color="#D2976C"/>
</linearGradient>
</defs>
</svg>
```




I just need to figure out a way to generate those path values from the original shapes

edit: turns out thats quite difficult. basically, for all shapes that currently lie outside of the rounded corner, they need to be converted to paths where the rounding is accomplished through a cubic Bezier curve and the rest of the geometry is drawn with absolute or relative move and line commands.

**Comment by TheKodeToad** [comment]
Is #238 being used instead? Or are both icon sets being added? Just interested.

**Comment by theofficialgman** [comment]
😢 
I really like these icons and there are so many more of them. Not really a fan of the other ones...

**Comment by felinusfish** [comment]
Sorry. I'd have finished this if I wasn't banned suddenly without warning.

**Comment by WaterSword** [comment]
These icons could still be used, but we would need you to give them a specific licence. As currently we don't know under what licence they would be. The best idea is probably the CC BY-SA 4.0 license, which the logo and related assets use too. I love these icons and it would be a real shame to see them go unused.

**Comment by felinusfish** [comment]
Yeah I'm fine with the CC BY-SA 4.0 license

**Pull request closed without merging**
