### PR TITLE
Add button to refresh themes and catpacks

### PR DESCRIPTION
**Pull request by Trial97**
I added a massive refresh button under the Catpacks selection.
Once clicked the themes, icons, and catpacks are refreshed(clear the existing ones and get the new ones from folders)

Right now it's a button should I make the refresh automatic: once you open the settings? 

Here is a preview:
 
image

### CODE REVIEW

**Comment by ghost** [comment]
> Right now it's a button should I make the refresh automatic: once you open the settings?

I think making it auto refresh when settings is opened is probably the more intuitive. Why not have both though?

**Comment by Trial97** [comment]
> Why not have both though?

I want to not have that massive button there, but the other option is not so easy to control as you will have that refresh happen each time you open the settings.
As this is one of my PRs that does not have an issue to base on I will wait for more users to express their opinion on this before really implementing the auto-refresh.

**Review by Rubyboat1207 — APPROVED** [review]

**Comment by theMackabu** [comment]
I prefer auto-refresh but the refresh button can stay incase someone wants to reload on the spot. A more elaborate solution would be to check for watch for changes and auto-refresh.

**Review by theMackabu — APPROVED** [review]

**Review by theMackabu — APPROVED** [review]
quite a useful change

**Comment by TheKodeToad** [comment]
I've been a little reluctant to approve because of the massive button :P
Maybe shrink it (using a spacer?) and i think it'll look good?

**Comment by TheKodeToad** [comment]
Maybe also write "Refresh all" so it's clear what it refreshes

**Comment by Trial97** [comment]
Now it looks as follows: image

**Review by DioEgizio — APPROVED** [review]

**Review by Ryex — APPROVED** [review]

**Pull request merged**
