### PR TITLE
Insert build instructions into the repository for temporary quick access

### PR DESCRIPTION
**Pull request by SSUPII**
While thought to be temporary, having tested build instructions in the repository itself will be a good starting point for the future website and in general have them quick to find.

I only added Linux instructions (Debian 11) as it is the only one I can currently test to be working.

### CODE REVIEW

**Review by NotNite — CHANGES_REQUESTED** [review]
I think we should be using Markdown headers instead of HTML (`#`, `##`, `###` and so forth). It's more readable in plain text IMO.

**Comment by SSUPII** [comment]
It is. I think GitHub also does a small preview of the markdown if they are used. I will update it and keep that way in the future.

**Comment by NotNite** [comment]
I want to eventually push to linting with [markdownlint](https://github.com/DavidAnson/markdownlint), but that's for later I guess.

**Comment by Scrumplex** [comment]
This is fine for now. It will be gone again, once we set up our website again

**Review by Scrumplex — APPROVED** [review]

**Review by flowln — APPROVED** [review]

**Comment by SSUPII** [comment]
Thank. I have added packages for other distributions thanks to a couple of Discord users (that I don't know if I can mention). I will keep those if they can be used for the future, final version of the BUILD file on the website.

**Pull request merged**
