### PR TITLE
Fixup Warnings in MSVC build

### PR DESCRIPTION
**Pull request by TheLastRar**
MSVC build spits out a large number of warnings during building, this pr tackles some of those warnings

I had removed a definition for `qhash` in `JsonFormat.h`, as far as I could tell nothing used it.

During this I noted that the parent parameter was not being used in rowCount & columnCount, this has been changed to match the advice given in the documentation of `QAbstractItemModel`, some of the classes where tested with `QAbstractItemModelTester `, which also picked up on the issue.

I also marked `loadExtraPackInfo` as an abstract method, since any class deriving from ListModel overrode this method.

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Comment by flowln** [comment]
The documentation says that `rowCount()` and `columnCount()` should return 0 when the parent is valid only in the cases of table based models (https://doc.qt.io/qt-6/qabstractitemmodel.html#columnCount). I'm not sure it applies to simple lists though? tbh i'm not exactly sure about what qualifies as a table based model :slightly_smiling_face:

**Comment by Scrumplex** [comment]
This should be what it's talking about: https://doc.qt.io/qt-6/qabstracttablemodel.html

**Comment by flowln** [comment]
> This should be what it's talking about: [doc.qt.io/qt-6/qabstracttablemodel.html](https://doc.qt.io/qt-6/qabstracttablemodel.html)

yes, but when is a model a table based model when we inherit directly from `QAbstractItemModel`? :thinking:

**Comment by Scrumplex** [comment]
I would assume that anything with more than one column would be a table model

**Comment by TheLastRar** [comment]
QAbstractListModel has similar code for columnCount
https://github.com/qt/qtbase/blob/067b53864112c084587fa9a507eb4bde3d50a6e1/src/corelib/itemmodels/qabstractitemmodel.cpp#L3968

**Review by flowln — COMMENTED** [review]
This patch seems to have broken the checkbox in the mods list. Double-clicking and the 'Enable'/'Disable' buttons still work fine, just the checkbox doesn't seem to be working anymore.

**Comment by TheLastRar** [comment]
> This patch seems to have broken the checkbox in the mods list. Double-clicking and the 'Enable'/'Disable' buttons still work fine, just the checkbox doesn't seem to be working anymore.

Found that `setData` in `ResourceFolderModel` was passing the index as if it was the parent.

I could split out `Check parent in rowCount/columnCount/canFetchMore` & `Pass index.parent() as parent parameter for rowCount` into a separate PR if you feel those commits need extra time to review compared to the rest of this PR

**Review by flowln — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
