### PR TITLE
fix(docs): use new format for adaptive images in README

### LINKED ISSUE #398: [Readme] dark/light mode image method is getting deprecated
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

### PR DESCRIPTION
**Pull request by ryanccn**
closes #398

### CODE REVIEW

**Comment by ryanccn** [comment]
junior job 😭

**Review by DioEgizio — APPROVED** [review]

**Review by flowln — APPROVED** [review]
junior member? :monocle_face:

**Comment by Scrumplex** [comment]
lol

**Review by Scrumplex — APPROVED** [review]

**Comment by ryanccn** [comment]
> junior member? 🧐

no u

**Pull request merged**
