### PR TITLE
readme: build instructions

### PR DESCRIPTION
**Pull request by edgars-cirulis**

### CODE REVIEW

**Review by TheKodeToad — APPROVED** [review]
Looks good!

**Comment by Kationor** [comment]
I feel like keeping a navigational page at the original location would be a (very slightly) better solution, since it would allow for a generic link as well as OS-specific links.

Edit for clarification:
The README and other generic places could point at, for example, `/wiki/development/build-instructions`. This page would then offer links to the OS-specific versions like `/wiki/development/build-instructions/linux` or wherever they're located.

**Review by Ryex — APPROVED** [review]

**Review by Trial97 — COMMENTED** [review]
I  belive that this should be done on the website

**Comment by Trial97** [comment]
And now with: https://github.com/PrismLauncher/prismlauncher.org/pull/498#event-13438032098 this should no longer be an issue.
@TheKodeToad  and @Ryex should we close this or merge it?

**Comment by edgars-cirulis** [comment]
> And now with: [PrismLauncher/prismlauncher.org#498 (comment)](https://github.com/PrismLauncher/prismlauncher.org/pull/498#event-13438032098) this should no longer be an issue. @TheKodeToad and @Ryex should we close this or merge it?

Needs to revamp the commit with build-instructions/linux, etc., instead of -

Also, if I'm looking for build instructions on another device like a phone, it will lead to Linux, but I would be looking for Windows. The same approach applies if I'm on Windows but looking for build instructions for Linux. So it leads to additional steps.

**Comment by TheKodeToad** [comment]
> And now with: [PrismLauncher/prismlauncher.org#498 (comment)](https://github.com/PrismLauncher/prismlauncher.org/pull/498#event-13438032098) this should no longer be an issue. @TheKodeToad and @Ryex should we close this or merge it?

Keep open - guessing the page the user wants to visit isn't great

**Comment by edgars-cirulis** [comment]
also should I remove https://github.com/PrismLauncher/PrismLauncher/blob/develop/BUILD.md because it seems orphaned file to me.

**Review by MCLP2005 — APPROVED** [review]
Seems okay 👍

**Review by Trial97 — APPROVED** [review]

**Pull request merged**
