### PR TITLE
Drop "DirectJava" launch method

### PR DESCRIPTION
**Pull request by TheKodeToad**

### CODE REVIEW

**Comment by Trial97** [comment]
You did beat me at this game :smile: I had it prepared here:(https://github.com/PrismLauncher/PrismLauncher/compare/develop...Trial97:lag2?expand=1)

**Comment by Scrumplex** [comment]
Did you forget to get rid of `launcher/minecraft/launch/DirectJavaLaunch.cpp`? :D

**Comment by TheKodeToad** [comment]
Oh no. I had the items selected but forgot to press delete I think.

**Review by getchoo — APPROVED** [review]
good yoink

**Review by DioEgizio — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
