### PR TITLE
Import config from `multimc.cfg` if available

### PR DESCRIPTION
**Pull request by RuiNtD**
Add fallback for multimc.cfg to make migration from MultiMC easier

### CODE REVIEW

**Review by timoreo22 — APPROVED** [review]
Second time's the charm !

**Review by flowln — APPROVED** [review]
good to see my overly generalized code that never ends up being useful besides the original feature was actually useful once :o

**Comment by RuiNtD** [comment]
> good to see my overly generalized code that never ends up being useful besides the original feature was actually useful once :o

fwiw, I looked at the code and it looks like it could cause a small config overriding problem if both `polymc.cfg` and `multimc.cfg`, but it's such a small edge case that I don't think it matters much.

**Comment by flowln** [comment]
> fwiw, I looked at the code and it looks like it could cause a small config overriding problem if both `polymc.cfg` and `multimc.cfg`, but it's such a small edge case that I don't think it matters much.

i think it will just get the first fallback it finds though, in this case it would be `polymc.cfg`, so it would ignore the mmc one

**Comment by RuiNtD** [comment]
> > good to see my overly generalized code that never ends up being useful besides the original feature was actually useful once :o
> 
> fwiw, I looked at the code and it looks like it could cause a small config overriding problem if both `polymc.cfg` and `multimc.cfg`, but it's such a small edge case that I don't think it matters much.

re-read the code should be good lol

**Pull request merged**
