### PR TITLE
add teawie as a cat

### PR DESCRIPTION
**Pull request by getchoo**
drawn by @SympathyTea

image
image

Signed-off-by: seth <getchoo@tuta.io>

### CODE REVIEW

**Comment by HurricanePootis** [comment]
I LOVE THIS!!!!!!!!!!!!!! (i will blow up teawie)

**Comment by SympathyTea** [comment]
this is everything i could ever want out of a launcher, tbh
so proud my dinky little meme drawing is getting this far

**Comment by AshtakaOOf** [comment]
Wait Teawie is a cat? Wth!

**Comment by getchoo** [comment]
> Wait Teawie is a cat? Wth!

yes, totally :sus:

**Comment by AshtakaOOf** [comment]
Change the cat option to "pet" then, but tbh it's too vibrant.

**Comment by SympathyTea** [comment]
> Change the cat option to "pet" then, but tbh it's too vibrant.

too vibrant?
elaborate pls

**Comment by getchoo** [comment]
i was thinking of changing it to "background," but pet is also a good choice

> but tbh it's too vibrant

how so? i know the blue and pink on the head are bright, but i wouldn't say it's overwhelming in any way. parts of rory are also fairly vibrant and i mean...the original multimc cat is literally all white. i don't see how this is much of an issue

**Comment by AshtakaOOf** [comment]
Doesn't fit the launcher at all, but that's my opinion.
My opinion is mostly trash anyway.

**Comment by sakecode** [comment]
good PR

**Comment by getchoo** [comment]
> Doesn't fit the launcher at all, but that's my opinion.

are they supposed to? do the other cats? the original multimc cat doesn't fit in with the new flat icons being used, and rory looks a lot more realistic and has colors not found anywhere else in the launcher. i would understand thinking a different pose might be better or that it should be scaled differently, but saying it doesn't fit in the launcher at all is a bit of stretch for what's the equivalent of a fun easter egg imo

**Comment by AshtakaOOf** [comment]
It's my opinion

**Comment by sakecode** [comment]
I agree with Getchoo they're more like Easter Eggs not suppose to fit in but be a fun reference to something.

**Comment by getchoo** [comment]
> It's my opinion

i know, i'm just trying to understand where you're coming from to see what changes should be made (if any) so it can be better

**Comment by AshtakaOOf** [comment]
Well first downscale the png to be less overwhelming...

**Comment by SympathyTea** [comment]
> Well first downscale the png to be less overwhelming...

both rory versions and the multimc cat are pretty large 
tbh i dont see your point

**Comment by AshtakaOOf** [comment]
But yeah actually don't listen to me I'm just sleepy.
Goodnight :)

**Comment by HurricanePootis** [comment]
I LOVE THIS (i will no longer try to blow up teawie :sob:)

**Comment by hisashiburii** [comment]
I LOVE TEAWIE (i make teawie memes sometimes)

**Comment by getchoo** [comment]
here are the event variants

christmas:
teawie-xmas

birthday:
teawie-bday

halloween:
teawie-spooky

**Review by timoreo22 — APPROVED** [review]

**Comment by TheKodeToad** [comment]
Whoa... that's a lot of emails I've had today! Thanks GitHub.

**Review by Scrumplex — COMMENTED** [review]
I like this. What's the license for these files though? Maybe add a comment about the license to the resources file

**Comment by UnlimitedCookies** [comment]
The question could become what background images should get bundled with the binary and which shouldn't. If all artwork files requested for inclusion by a PR get accepted, then this might become an icon pack instead of an MC launcher.

**Comment by TheKodeToad** [comment]
> The question could become what background images should get bundled with the binary and which shouldn't. If all artwork files requested for inclusion by a PR get accepted, then this might become an icon pack instead of an MC launcher.

Are you trying to suggest that's a bad thing?! We're all here for the cat(s).

**Comment by flowln** [comment]
> The question could become what background images should get bundled with the binary and which shouldn't. If all artwork files requested for inclusion by a PR get accepted, then this might become an icon pack instead of an MC launcher.

Eventually *all* background images should be removed from the binary, and dynamically loaded from a folder instead like what we do with themes currently, imo. But we don't yet have that logic, so for now we add the "cats" that a reasonable amount of people want in the launcher.

**Comment by SympathyTea** [comment]
> What's the license for these files though?
Teawie is under the CC BY-SA license, feel free to use him for this particular background "cat"

https://commons.wikimedia.org/wiki/File:Teawie.png
https://commons.wikimedia.org/wiki/File:Teawie_Party.png
https://commons.wikimedia.org/wiki/File:Teawie_Holiday.png
https://commons.wikimedia.org/wiki/File:Teawie_Halloween.png

**Comment by AshtakaOOf** [comment]
Teawie is a mouse? Or a cat from now on?

**Comment by getchoo** [comment]
> Maybe add a comment about the license to the resources file

all of the attribution terms have been added there :)
let me know if i missed anything

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
:tada:

**Pull request merged**
