### PR TITLE
Fixed the maximized option on the newer Minecraft versions

### LINKED ISSUE #181: Start maximised option not working
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

Ticking the option "Start Minecraft maximised?" will not result in it starting large, both global and instance specific.

### Steps to reproduce

1. Tick the "Start Minecraft maximised?" option on.
2. Launch an instance.

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #292: Gray out 'Start Minecraft maximized' option for versions that don't support it
### Role

I use Prism Launcher

### Suggestion

The 'Start Minecraft maximized' option seems to be broken on all Minecraft versions above 1.5.2 (see https://github.com/PrismLauncher/PrismLauncher/issues/181 and https://github.com/MultiMC/Launcher/issues/2770#issuecomment-515713767).

So it would make sense to just gray it out for all Minecraft versions above 1.5.2.

### Benefit

So that people won't be confused by it not working (like what happened here: https://github.com/PrismLauncher/PrismLauncher/issues/181).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is the option I'm talking about:

image

### PR DESCRIPTION
**Pull request by Trial97**
fixes #181
closes #292
Works on my machine but I would want to test it against other platforms
This doesn't really start it in maximized mode but just sets the game width and height to the maximum possible value.
~Warning I'm entirely sure that `java.awt` stuff is in the default java installation(I haven't worked with java for a long time)~

### CODE REVIEW

**Comment by TayouVR** [comment]
at least on my windows this makes it the right size, but the window title is outside of my monitor. :/
image

**Comment by Trial97** [comment]
Do you have more than one monitor?
The gap at the bottom is for the taskbar I think.

**Comment by Trial97** [comment]
With the latest commit the decoration size should also be taken into consideration.
Small warning the position of the window can't be controlled.

**Comment by TayouVR** [comment]
> Do you have more than one monitor? The gap at the bottom is for the taskbar I think.

I have 3 monitors, though the size of the gap is the size of the window title bar. The task bar is about twice that size.
I will have a look at the latest build ^^

**Comment by TayouVR** [comment]
image
Can we set the window position somehow?
If so; then we could fix this, by just shifting it down.
But at least I can reach the titlebar now, so its not too bad. Better than not changing the size at all.

Though changing the window position would reach into ugly platform specific APIs and code.. :/

**Comment by Trial97** [comment]
I can't control the window at all (size being the exception as we have some arguments for it) so the position change I believe is something not for this PR(maybe possible but I will not worry about it).
Also just to make sure that this is treated as a hack I added a big yellow warning(permanent on global settings; conditional on the instance settings)

**Review by TayouVR — APPROVED** [review]

**Comment by TheKodeToad** [comment]
>  Warning I'm entirely sure that java.awt stuff is in the default java installation(I haven't worked with java for a long time)

I assume you mean you're not entirely sure. It should be available, but in newer Minecraft versions (with LWJGL3) I'm pretty sure it causes some *big* problems!

**Comment by Trial97** [comment]
Do not worry I removed that in favor of some c++ code that does the same thing but a little better: https://github.com/PrismLauncher/PrismLauncher/pull/1894/commits/0cab57c0a81a8cb6b5c086ece38f09d35df78212
I just forgot to update the original PR message.
Right now all I do on this PR is as follows:
- using QT try to determine the size of the screen( this is not guaranteed to get me the right values)
- pass the calculated size to java launcher 
- in the launcher just pass that to Minecraft

The only reason I opted to also add a warning on the checkbox is because in theory even if the surface of the game is expanded at maximum(similar to how maximized would work) is not maximized.
The only change to the java code is the removal of maximized check for newer version(and passing the dimensions directly)

**Review by Ryex — APPROVED** [review]

**Pull request merged**
