### PR TITLE
Add a search bar to version lists

### PR DESCRIPTION
**Pull request by TheKodeToad**
image
Very questionable...

### CODE REVIEW

**Review by getchoo — APPROVED** [review]
very cool

**Review by TayouVR — APPROVED** [review]
I haven't had the time to test this, but scrolled through the code and couldn't spot anything wrong. so if it works; LGTM

**Comment by getchoo** [comment]
worked on my end as expected. now should we put this in 7.1 or 8.0? 🤔

**Comment by TheKodeToad** [comment]
I think 8.0, imo at this stage only bugfixes should be added otherwise it'll take a long time

**Comment by getchoo** [comment]
yeah sounds fair to me, especially since this one didn't have an issue attached to it or anything

i'll add it to the milestone, but it'll be blocked until https://github.com/PrismLauncher/PrismLauncher/pull/1187

**Comment by TheKodeToad** [comment]
i was worried some of my workarounds weren't great tbh

**Pull request merged**
