### PR TITLE
Fix crash when hiding columns on resource packs page

### PR DESCRIPTION
**Pull request by leia-uwu**
The page has 5 columns but there was only 4 items on the resize modes list :p

### CODE REVIEW

**Review by Trial97 — APPROVED** [review]

**Comment by leia-uwu** [comment]
why are the tests failing :(

**Comment by Trial97** [comment]
I had a similar failure on one of my PRs -> sometimes they fall randomly was the answer when I asked the same question.

**Review by getchoo — APPROVED** [review]
works as expected :)

**Comment by getchoo** [comment]
> sometimes they fall randomly was the answer when I asked the same question.

yeah the task test just feels a little silly sometimes in ci. nothing to worry about

**Review by Ryex — APPROVED** [review]

**Comment by Ryex** [comment]
my bad, miss-counted and after the latest column resize on hide patch I didn't test that page

**Pull request merged**
