### PR TITLE
Added option for direct java launch

### LINKED ISSUE #1137: Worse game performance compared to the official launcher
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

This is a little bit of a weird issue, but I seem to have reliably about 40% better FPS when using the official Minecraft Launcher than when using Prism Launcher.

For some context, before the 1.20 release, I've always been using the official launcher, however I want to make a custom modpack for this summer and I figured a 3rd party launcher would make things easier. I've also been interested in the performance improvements of 1.20. So before 1.20 released, I took some measurements in 1.19.4 in my performance testing world. Today I installed Prism Launcher, expecting it to make no performance difference because why would a launcher do that, added a fresh instance for 1.20, copied over my worlds and game options, as well as the JVM args I'm usually running the game with, and took the same measurements as before. But to my surprise there was a noticeable drop in performance. So I tried the same test with the official launcher, this time updated to 1.20, and the performance using the official launcher was better than in 1.19.4, and both were noticeably better than the 1.20 performance using Prism Launcher.

I even made sure to set the official launcher to use the same Java install as the Prism Launcher (because before it was using a bundled-in version, which was 17.0.3 and my system install is 17.0.1, but after fixing for that, the results are the same. Tried repeating the test a couple times too.

So same version of the game (1.20), same world, same options, same JVM args, same Java install, instance stored on the same hard drive, same machine (and same GPU, my laptop has its iGPU hardware-disabled), but 40% higher FPS when using the official launcher (circa 200+-20 on Prism vs 280+-20 on the official launcher, with occasional larger dips on both). Windows is set to Best performance during both, and no other apps are running other than the launchers and background tasks.

JVM args used: `-Xmx4G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`. (With Prism Launcher `-Xmx4G -Xms4G` is omitted and min/max memory allocation is set to 4096 MiB in the GUI.

Attached two F3 screenshots as examples (with the lower FPS using Prism Launcher).
F3, Official Minecraft Launcher
F3, Prism Launcher

### Steps to reproduce

- Open a world using the official Minecraft Launcher
- Wait a couple minutes and check FPS using the F3 overlay
- Close the game
- Open an identical copy of the world (with same MC version, options, JVM args, etc.) using Prism Launcher
- Wait a couple minutes and check FPS using the F3 overlay

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
Added the setting.
Any language change is welcomed also is it an ok place?
It looks like it fixes https://github.com/PrismLauncher/PrismLauncher/issues/1137

### CODE REVIEW

**Comment by Scrumplex** [comment]
Not sure if we want this. I actually thought about dropping DirectJava launch in the long run, as it's pretty much unmaintained anyway.

**Comment by Trial97** [comment]
I would love to keep it as I was able to get a boost through this method, and from my testing, this still works(this PR just reveals the option in GUI ), but you can achieve this on develop by editing the instance.cfg .
Also by keeping this, we would have an option to launch the instance similar to how the Minecraft launcher does

**Comment by Trial97** [comment]
Or at least keep the DirectLaunch and this PR until somebody that reported #1137  test this and determine if it's moving faster with the direct launch or not.
Also in my tests, I did observe an improvement in frames, but I may be biased.

**Comment by Scrumplex** [comment]
Well, DirectJava would at best be a workaround in that case. It's probably just some Windows magic trying to detect the game and "optimizing" it

**Comment by Trial97** [comment]
Do not know about Windows as I tested it on Linux

**Comment by Trial97** [comment]
So I did receive a confirmation for this:https://github.com/PrismLauncher/PrismLauncher/issues/1137#issuecomment-1606328931 it does improve something.
As this doesn't really add the DirectJavaLaunch as a new method for launching but just exposes the setting for activating it, please consider reviewing and merging this PR.

**Comment by Scrumplex** [comment]
> As this doesn't really add the DirectJavaLaunch as a new method for launching but just exposes the setting for activating it, please consider reviewing and merging this PR.

Well. If this is merged, DirectJava would be considered a supported feature. 

Again, this would just be a workaround to trigger some optimization magic, so I don't like this approach. Someone should probably just figure out what's going on exactly.

**Comment by Trial97** [comment]
Then why not mark this as experimental or something and have a separate issue that investigates the 'magic'?
The code is there and works if you manually edit the config files. 
My take on this is that the current method is slower because it uses reflection to execute the main from the class.

Also if you are so against this please open and merge a PR that deletes the DirectJavaLaunch, as you said you already want to drop this.

**Comment by TheKodeToad** [comment]
I think this just needs some investigation...

**Comment by TheKodeToad** [comment]
Okay: I've had an idea for a while now and it's really not ground-breaking:
- Remove NewLaunch - it seems like it's not really needed and as useful any more (previously it could shorten the arguments a lot more, but that required hacks which have broken)
- Always launch directly - currently logic is needing to be duplicates as arguments are sent in with a different syntax which is parsed and converted to the actual MC args
- Move the legacy code to another repo called `LegacyLaunch`
- Publish the jars to a maven repository
- Inside meta, inject these jars as libraries on legacy versions. Change the main class to `org.prismlauncher.legacy.LegacyLaunch` or whatever the main class happens to be.
- Find a viable replacement for the functionality of waiting for the profiler to attach
- Profit (maybe)!

This would make https://github.com/PrismLauncher/PrismLauncher/pull/1164#issuecomment-1622191628 and maybe #443 a lot more viable!

**Comment by TheKodeToad** [comment]
Looks like Forge and LiteLoader make this more complicated though

**Comment by TheKodeToad** [comment]
Never mind, I'm stupid

**Comment by TheKodeToad** [comment]
https://github.com/PrismLauncher/PrismLauncher/issues/1137#issuecomment-1629110348

Maybe my idea wasn't so good then

**Comment by Scrumplex** [comment]
Yay. Another reason to yoink DirectJava out of the launcher.

Actually, we might take this opportunity and add an optional performance option with a big fat warning, that tricks the NVIDIA driver into doing its optimization stuff

Let's continue discussion in the #1137

**Comment by Scrumplex** [comment]
Thanks for the contribution, but as outlined above, I don't think we should encourage users to use DirectJava. Let's continue the discussion in #1137

**Pull request closed without merging**
