### PR TITLE
Feat: Windows (And portable linux / appimage) Auto Updater

### PR DESCRIPTION
**Pull request by Ryex**
As I previously discussed on the discord the options for auto updating on windows are abysmal. we are frankly better off rolling our own (simple) solution.

## The Plan

- [x] Pull release info from the github api
- [x] Check if there is a newer release
- [ ] Ask the user if they wish to update
- [ ] Launch update process and exit prism.
- [x] (Optional) Let the user select from available newer releases
- [x] Download appropriate release asset to temp location (accounting from architecture, portable install etc. Simple so long as our naming remains consistent) (make the algo fuzy to account for variance if it's is needed)
- [x] create local file that marks an update in progress
- [x] if there are files we **know** need to be removed between updates "remove" them but create back-up (os move)
- [ ] perform update
  - [ ] IF PORTABLE: 
    - [x] Extract to temp local folder
    - [x] create maker file in tmp folder so updater knows what's going on (contains target install path)
    - [x] Run new updater, exit current updater process
    - [ ] new updater process moves files out of temp dir to install dir and copies itself over old updater then exits 
  - [x] IF MSI / Setup.exe INSTALL:
    - [x] Run installer and exit updater
  - [x] IF Appimage 
    - [x] attempt to call embedded `AppImageUpdate`
- [ ] Next time prism starts is sees marker files, present user with update log and cleans up.

Presumably at every point in the process if there is an error there is still an intact launcher install

### CODE REVIEW

**Comment by TayouVR** [comment]
I just had a stupid idea, that turned into a maybe not that stupid idea...

Rather than writing our own update process with complicated logic, we could just tell winget (should always exist in win10/11) to update.

From the community discord:
> **Tayou** 
what if instead of making a updater our installer installs scoop and then just runs scoop install prismlauncher :)
:trollely:
perfect software installer, as all things should be
**Tayou**
I mean, heck... with winget being part of windows, when we eventually, inevitably, stop supporting win7... we could just have the installer install prism through winget. And update through the app by telling winget, hey.. update prism
**Toothy Fernsan**
prism is on winget already tho?
**Tayou**
I know, thats why I'm saying
we could do that
**Toothy Fernsan**
a
Yea
you dont even need admin for it
**Tayou**
rather than writing our own updater we just force ppl to use winget, by just uhh, telling winget to install the new version :P 
**Toothy Fernsan**
it just needs to open a cmd and run winget upgrade PrismLauncher.PrismLauncher
**Tayou**
my idea with scoop was originally a joke, but this is actually not that stupid of an idea....
**Toothy Fernsan**
shouldn't even be hard to do

**Comment by Ryex** [comment]
Winget is only garenteed to be installed on windows 11. Windows 10 didn't include it until much later updates. 

Even then winget won't really handle the portable install case.

there really isn't all that much "complicated logic" involved in the updater.

**Comment by getchoo** [comment]
> Rather than writing our own update process with complicated logic, we could just tell winget (should always exist in win10/11) to update.

i agree with this honestly. winget (and other package managers like scoop and choco) are much more robust solutions. this change could also interfere with the latter two package managers, as unlike winget, they don't attempt to use the same install processes traditional exes do. 

> Winget is only garenteed to be installed on windows 11. Windows 10 didn't include it until much later updates.

i also don't think this much of an issue. windows 21h2 (where i'm pretty sure it's included) is reaching eol soon, and it seems most windows 10 users will be upgrading to 22h2 [soon](https://www.windowscentral.com/software-apps/windows-10/microsoft-will-force-all-windows-10-users-to-upgrade-to-version-22h2-next-month) as well.

the bigger issue here would be for regular users having to use the terminal to get auto updates. this is just not user friendly and of course shouldn't be expected. a built in auto updater would solve this...but i still don't think it's really the best solution considering what i've previously mentioned. imo, for a user friendly update experience, prism could be provided on the microsoft store. this has been [discussed before](https://discord.com/channels/1031648380885147709/1031823065937629267/1100796570695372850), and now that win32 app publishing has been [opened to everyone](https://developer.microsoft.com/en-us/microsoft-store/desktop-apps), i think it would be a much better alternative and a good way to set an example of how modern windows applications should be distributed. a cool side effect of this as well: it would also be able to be installed with winget, as ms store support there is ofc included, allowing for both average and power users to have a better experience

**Comment by getchoo** [comment]
>  (Optional) Let the user select from available newer releases

i would also like to take note of this; i don't see much of a reason why the updater shouldn't just update to the latest version possible. we've had [a](https://github.com/PrismLauncher/PrismLauncher/security/advisories/GHSA-wxgx-8v36-mj2m) [couple](https://github.com/PrismLauncher/PrismLauncher/security/advisories/GHSA-gq28-qx55-mh2r) security issues before, and i'm sure there will be more. users should be pushed towards the most recent versions possible, as they are what's currently supported and have all of the bug/security fixes that have been released at the time. it would also prevent people from upgrading to broken versions if we ever have a 6.2 -> 6.3 emergency patch again. 

this could be annoying for some i understand, but i think it'd be worth it for the majority of users who have no reason to not be on the latest version - especially as it wouldn't stop others from manually upgrading to a specific version using the exes from releases.

**Pull request closed without merging**
