### PR TITLE
Several Modrinth export fixes

### LINKED ISSUE #1862: Allow multiple lines summary in Modrinth pack
Theseus supports multiline summaries. I didn't implement this because I wasn't sure whether it was permitted by the format (I don't think it's documented).

### PR DESCRIPTION
**Pull request by TheKodeToad**
- [Fix server side mods being marked as unsupported on client](https://github.com/PrismLauncher/PrismLauncher/commit/138df66355b54151302f0b143ec1c2a5a4eb11c8) - read the comment I added for more info
- [Allow multiline description](https://github.com/PrismLauncher/PrismLauncher/commit/6a943639dd651759f87441da1d303d773511b72f) - fixes #1862

### CODE REVIEW

**Review by Trial97 — APPROVED** [review]
The export part is a little shady for me but if you say it works lgtm!

**Comment by TheKodeToad** [comment]
Could you elaborate?

**Comment by Trial97** [comment]
This is related to a discussion that we had previously: https://discord.com/channels/1031648380885147709/1209079645815967805 and https://github.com/PrismLauncher/PrismLauncher/pull/2142
In that discussion, we concluded that the mod is incorrectly marked as server-side only and we do not need to make any changes to the import and export.
Maybe I'm overthinking stuff but I still believe that the mrpack implementation we have is correct: like that mod is server-side mod why it is exported as needed for the client?
If we consider changing the export as such we should consider also changing the import like I did in the mentioned PR.

**Comment by TheKodeToad** [comment]
Your other PR clearly went against Modrinth's specification. This does not.

**Review by DioEgizio — APPROVED** [review]

**Review by TayouVR — APPROVED** [review]

**Pull request merged**
