### PR TITLE
add icons to the instance context menu and 4 new icons

### PR DESCRIPTION
**Pull request by leia-uwu**
screenshots:
simples (colored icons):
image
simple (light icons):
image
simple (dark icons):
image
simple: (blue icons):
image
osx:
image
ios:
image
flat:
image

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]
The trashcans look weird, but apart from that this looks really cool

**Comment by Scrumplex** [comment]
Also, I just noticed, that most if not all Flat icons are from Material Design icons. I think we should keep it at that.

**Review by flowln — APPROVED** [review]
hehe, now i won't need to make an icon for the rename action on the ui redesign x)

looks really cool to me, thanks!

**Review by Scrumplex — CHANGES_REQUESTED** [review]
(see above)

**Review by txtsd — APPROVED** [review]
Very nice QoL change

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Pull request merged**
