### PR TITLE
replacement in Prism Launcher

### PR DESCRIPTION
**Pull request by Loweredgames**
HI. I don't understand why there is still Poly in the code. so I replaced everything in replacement in Prism Launcher. check that I'm not a programmer and in case you take my request.

### CODE REVIEW

**Comment by Loweredgames** [comment]
ok

**Comment by Loweredgames** [comment]
but why not updated? @TheKodeToad

**Comment by TheKodeToad** [comment]
I thought this was spam. But we don't need this :laughing:.

**Comment by Loweredgames** [comment]
> I thought this was spam. But we don't need this 😆.

ok 👍

**Pull request closed without merging**
