### PR TITLE
Fix shader packs detection

### LINKED ISSUE #1803: Wrong Shader Pack count, possibly other types too
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

image
There are 2 elements listed, yet it says that 3 are installed.

### Steps to reproduce

* Install a shader pack
* Go to the game and change settings
* Now Shader packs should say that you have 2 installed 

### Suspected cause

I assume it is due to the fact that shader settings are saved in the same folder, and it just counts the number of files instead of amount of stuff that are displayed on the list.
If that's the case, then other stuff like mods and rps will also show that more are installed based on file count instead of what it detects. I know some mods, especially older ones, saved some stuff in mods folder like cache things etc. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #1807: shaders not being found by launcher
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

I just updated to Prism 8 and started editing my main instance. I wanted to install BSL and complementary but after I selected them and they were successfully installed they didn't show up in the shader list. I went to check the folder and the shader files are definitely present but are just not being registered by the launcher.
image
image

### Steps to reproduce

- Open the edit menu of any instance that supports shaders
- Install any shader you like (preferably from modrinth because I got mine from them)
- see the shader being installed in your shaderpacks folder but not registered by the launcher

### Suspected cause

I'm not sure what could be causing it except that Prism isn't properly checking the shaderpacks folder for shaders

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
Parent PR: #1657
fixes #1803
fixes #1807 (this part needs more testing)

- the 1803 was because instead of removing the files we just filtered them so I connected the onParseFailed slot with the removal of that resource
- observed that some parse tasks exit without emitting any signals(if the file is not a valid resource then the task would never finish). This is not a big deal but because I added that emitFailed it may remove from display some resources

### CODE REVIEW

**Comment by TayouVR** [comment]
I was gonna test this, but the CI builds are expired xD
looks like I can't manually rerun them either

**Comment by Trial97** [comment]
Retriggered the build.

**Review by TayouVR — APPROVED** [review]
seems to be working in a quick test. Code looks good too!

**Review by DioEgizio — APPROVED** [review]

**Comment by Trial97** [comment]
I'm gonna merge this as it is meant for the 9.0 and I presume that that's enough time to test this out in nightly.

**Pull request merged**
