### PR TITLE
add icons to the instance toolbar

### PR DESCRIPTION
**Pull request by leia-uwu**
this pr adds a launch icon, enables icons in the instance toolbar and makes the instance toolbar actions left-aligned instead of centered 
image
image

### CODE REVIEW

**Review by flowln — APPROVED** [review]
This looks good, thanks!

However, since you're adding a new icon, this will kinda conflict with https://github.com/PrismLauncher/PrismLauncher/pull/65, in the sense that that icon theme won't have this icon. Either you add the icon from that PR here, after we merge that one, or that one adds the icon, after we merge this one (I mean, you could also make a 3rd PR adding the icon after the two or something). So, you and @he3als should probably coordinate on what to do :p

**Comment by he3als** [comment]
I can add the icon to my PR once this is merged

**Comment by ghost** [comment]
@leo78913 since your working on sidebar, can you make sure that the side bar doesnt have this gradient. it doesnt look good
image

**Comment by he3als** [comment]
I think that might be due to your current QT theme

**Comment by ghost** [comment]
Yes, im using macOS with system theme option, and it supposes to replicate the native UI.
However, this is wrong since native sidebars doesn't have this gradient.

**Comment by Scrumplex** [comment]
> Yes, im using macOS with system theme option, and it supposes to replicate the native UI. However, this is wrong since native sidebars doesn't have this gradient.

File a Qt bug. We can't change the theming for the System theme here.

**Comment by Scrumplex** [comment]
Now needs a Flat white version, as #65 is merged :D

**Comment by leia-uwu** [comment]
> Now needs a Flat white version, as #65 is merged :D

done

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Comment by ghost** [comment]
> File a Qt bug. We can't change the theming for the System theme here.

@Scrumplex I'm unfamiliar with c++. However, I created a simple sidebar using [PySide](https://www.qt.io/qt-for-python). According to this, a native sidebar looks like this. So It's safe to assume this is not a Qt issue?

https://user-images.githubusercontent.com/103877079/198753450-575b7e80-ecf9-4a0e-8631-de84b01850bd.mov

**Pull request merged**
