### PR TITLE
Allow disabling bundling and Sparkle updater when building

### PR DESCRIPTION
**Pull request by getchoo**
as a continuation of https://github.com/PrismLauncher/PrismLauncher/pull/1448, this disables sparkle from being downloaded or linked against when `MACOSX_SPARKLE_UPDATE_FEED_URL`  is an empty string, and allows for the overriding of `INSTALL_BUNDLE`. this is primarily to allow for building the launcher with nix on darwin, but could also be useful in similar situations where linking can be handled by another program - or for people who just don't want to build with sparkle at all

a fork of nixpkgs using this patch is available [here](https://github.com/getchoo/nixpkgs/commit/380816cb1fffe78bda56f9726abdbd7cebe498a8)

```shell
nix build github:getchoo/nixpkgs/380816cb1fffe78bda56f9726abdbd7cebe498a8#prismlauncher
```

this has built on x86_64 and aarch64, but still has some minor issues that will most likely need to be solved on the nix side

### CODE REVIEW

**Comment by RaptaG** [comment]
regarding my reviews: yes they are the same but why not 🤷🏽‍♂️

**Comment by Scrumplex** [comment]
my changes above should simplify the code a bit

**Comment by getchoo** [comment]
yeah that is much less annoying lol

**Review by Scrumplex — APPROVED** [review]

**Review by Ryex — APPROVED** [review]

**Comment by Scrumplex** [comment]
conflicting :eyes:

**Review by DioEgizio — APPROVED** [review]
Lgtm but you need to fix conflicts

**Pull request merged**
