### PR TITLE
Rework the java system

### PR DESCRIPTION
**Pull request by timoreo22**
Here we go again

This is off the base of the old JRE download pr (adding a few suggestions in)
Goal of this is to rework the way the JRE is selected, such as allowing to set a java 8 and a java 17+ version, and adding the downloading in, mostly for windows and macos

TODO :
- [x] do the JRE downloading
    - [ ] add vendor choice
- [ ] add java management
    - [ ] change ui to allow for profiles
    - [ ] make an user friendly ui for a quick inital setup / migration (downloading java if needed, set some memory and args depending on usage ?)
    - [ ] automate change to supported java (at instance creation time ?)
    - [ ] do a migration system (on an instance basis, kinda mandatory)
    - [ ] make it quickly change between profiles (change launch system to use profiles)
    - [x] check formatting for saved profiles (separate file ? json in settings ?)

### CODE REVIEW

**Comment by ghost** [comment]
How exactly does the downloading look and what JRE does it download?

**Comment by DioEgizio** [comment]
> How exactly does the downloading look and what JRE does it download?

the mojang one, fallbacks to azul when not available for the platform

**Comment by theofficialgman** [comment]
can I suggest a fallback to adoptium/temurin instead of azul? thats more of a "pure" openjdk build and has better system support (eg: desktop armhf and arm64 linux jres).

this should be its api https://api.adoptium.net/q/swagger-ui/

**Comment by TayouVR** [comment]
I think given existing file structure "javaDownloader.[cpp, h]" should be in the java folder, right? (not like it really matters in the end..)

**Comment by ethanwillis** [comment]
While I'm personally in favor of temurin vs azul as a default for *reasons.* I think even if the switch isn't made to use it there's a better path forward here. It should be user configurable outside of whatever defaults are chosen. There are definitely cases where you might one or the other (or others) for performance/system stability reasons.

**Comment by caitlynrw** [comment]
Adding onto what Ethan Willis said; different JDKs for different purposes. I think OpenJDK or adoptium (or whatever it's called now) is a good default given the system architectures match, then maybe have some hierarchy of fallbacks. for example, I use openjdk@17 for my Java 17 JDK then zulu8 for my JDK for Java 8 as that has native M1 support.

Just spitballing here, but maybe when the user initially sets up Prism if it doesn't detect a JDK it can either ask the user to install one either themselves or via a package manager or in a dropdown where the user can select a version for Prism to install into a library folder somewhere in the appdata dir. And the default selected is the "best" for that arch but they can select a different one if they want.

Also another unrelated nitpick I have with the current java system, it picks up 2 of the same JDK sometimes cause there's a java bin in the root folder and a bin/ folder, they're the same, it just shows up twice and is mildly annoying

**Comment by TheBjoel2** [comment]
```
   16.066 C "Could not create folder for /usr/bin/java/java-legacy/COPYRIGHT"
   16.066 C Task "Net::Download(0x55c0c1c180d0)" failed while not running!!!!:  ""
   16.066 D Task "Net::Download(0x55c0c1c17bc0)" starting for the first time
   16.066 C "Could not create folder for /usr/bin/java/java-legacy/LICENSE"
   16.066 C Task "Net::Download(0x55c0c1c17bc0)" failed while not running!!!!:  ""
   16.066 D Task "Net::Download(0x55c0c1b24700)" starting for the first time
   16.066 C "Could not create folder for /usr/bin/java/java-legacy/README"
   16.066 C Task "Net::Download(0x55c0c1b24700)" failed while not running!!!!:  ""
   16.067 D Task "Net::Download(0x55c0c1b09a60)" starting for the first time
   16.067 C "Could not create folder for /usr/bin/java/java-legacy/THIRDPARTYLICENSEREADME-JAVAFX.txt"
   16.067 C Task "Net::Download(0x55c0c1b09a60)" failed while not running!!!!:  ""
   16.067 D Task "Net::Download(0x55c0c1c26040)" starting for the first time
   16.067 C "Could not create folder for /usr/bin/java/java-legacy/THIRDPARTYLICENSEREADME.txt"
   16.067 C Task "Net::Download(0x55c0c1c26040)" failed while not running!!!!:  ""
   16.067 D Task "Net::Download(0x55c0c1c261b0)" starting for the first time
   16.067 C "Could not create folder for /usr/bin/java/java-legacy/Welcome.html"
   16.067 C Task "Net::Download(0x55c0c1c261b0)" failed while not running!!!!:  ""
   16.067 D Task "Net::Download(0x55c0c1b0cea0)" starting for the first time
   16.067 C "Could not create folder for /usr/bin/java/java-legacy/bin/java"
   16.067 C Task "Net::Download(0x55c0c1b0cea0)" failed while not running!!!!:  ""
   22.391 D Task "JavaDownloader(0x55c0c1ae4770)" aborted.
   22.409 D Task "NetJob(JRE::FileDownload)" aborted.
```
Maybe download java to somewhere else?

**Comment by RaptaG** [comment]
Shouldn't this be in a milestone or something?

**Comment by TheKodeToad** [comment]
It's a draft.

**Comment by ColonelGerdauf** [comment]
I will suggest to at least offer an option to download sandboxed runtimes within Prism.

The thing is, Java will create a lot of confusion to the semi-casual players, especially in the scope of Windows. It is easy for them to forget that Minecraft non-Bedrock requires Java, and will uninstall the JRE's due to the lack of a use case anywhere else. This is even worse for situations where 8 and 17 are expected to be used in the same installation. That will generate a lot of confusion.

Not to mention, a number of Java application in Windows that are updated nowadays come with their own runtimes internally, due to the need of specific versions, and the lack of a need of Java elsewhere.

I understand the hesitation for internal libraries, but this will lead to a rather messy situation with the computer software stack. It leads me to the question: why should a Windows user install a runtime  on their whole system when it is almost never used outside of Minecraft?

**Comment by TheKodeToad** [comment]
Well presumably this would download it as opposed to install it — I don't think it would be more of an issue than with the official Minecraft launcher which does download it.

**Comment by ColonelGerdauf** [comment]
Actually, that is an excellent point.

The Mojang launcher already comes with their own runtime(s), and on top of that still let the users configure external JREs including installed. Their implementation may be less than ideal, as it is uncertain if there is any version switching or even more than one engine.

**Comment by Noxiuam** [comment]
Just a suggestion, but I would notify users if a certain version of the game is not recommended for a certain Java version (Minecraft Alpha/Beta for example can be ran on newer versions of Java but it is not recommended to go higher than 8 due to compatibility issues)

**Comment by getchoo** [comment]
there's some discussion relevant to this in https://github.com/PrismLauncher/PrismLauncher/pull/1179 (we actually seem to have come with a similar solution...i kinda forgot about this pr)

this could seriously help the current issues in that, as the biggest limitation currently is using jvms outside of prism's data directory

**Comment by Scrumplex** [comment]
any activity on this? Or can we close this and hope someone else picks up the work?

**Comment by TheKodeToad** [comment]
I tried fixing the conflicts. Hopefully I didn't make a mistake, but it looks like timoreo fixed the path traversal vulnerability too

Edit: i don't think it'll compile any more. lol

**Comment by TheKodeToad** [comment]
GitHub's being weird, but I have hopefully brought it more up to date! hope this helps, sorry if it doesn't :P

**Comment by Alyaqdhans** [comment]
We need this Java rework ASAP!
I opened an issue thinking no one suggested this #2289

**Comment by Trial97** [comment]
closing this in favor of https://github.com/PrismLauncher/PrismLauncher/pull/2069

**Pull request closed without merging**
