### PR TITLE
Pack import fixes and improvements

### LINKED ISSUE #536: Auto-name downloaded icons from platforms which don't get proper names
### Role

It's mostly just for aesthetics and easier sorting of icons in the selection menu

### Suggestion

When downloading a modpack, take the pack name and use that as the name of the icon if it's from a platform which doesn't keep icon name metadata

### Benefit

Again mostly just aesthetic and sorting benefits, not having a bunch of icons named "curseforge_[string_of_numbers]" everywhere

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When downloading a modpack via the various website and launcher sections in the import menu, Prism Launcher imports the icon for the pack automatically. In many cases this works fine, specifically with FTB, FTB Legacy, and ATLauncher packs. But when installing packs from Curseforge or Technic, the icons will have unreadable names consisting of either:
curseforge_XXXXXXXXXXXXXXXXXX or technic_XXXXXXX (where any "X" is a number)
Modrinth has a lesser version of this where every icon is labelled as modrinth_name (where "name" is a lowercase representation of the pack, either an acronym or the name itself)

Given that Prism Launcher already generates a valid name for the pack at around the same time it grabs the icon (when the pack is first selected in the menu), I feel it wouldn't be too hard to save the icon with the name of the pack instead in cases where it would look better than the messy ID's used by Curseforge, Technic, and Modrinth.

I know this is an extremely minor complaint, but I feel like it wouldn't be too hard to do and would greatly improve the appearance of the Icon menu and folder after you've downloaded several packs from these places.

No change:
image
image

Where it would get the name:
image

After the change (With characters that can't be used by the filesystem removed/replaced):
image
image

(Note: File Explorer examples have had .png added at the end so the icon is visible in File Explorer)

### LINKED ISSUE #1652: Mods were downloaded into root .minecraft folder instead of mods/ while importing a Modrinth modpack "Create Extra"
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.0

### Description of bug

Upon installing the Modrinth pack [Create Extra Full - 1.2.0](https://modrinth.com/modpack/create-extra/version/MqYT8IQ2) I discovered that out of the 60 mods that were downloaded only 3 were present in the Mods list in Prism.

I investigated the .minecraft directory and found the missing mods in the .minecraft directory itself. Their filenames started with `mods\`. Here are the contents of .minecraft:

- config
- coremods
- mods
- mods\3dskinlayers-fabric-1.5.2-mc1.19.1.jar
- mods\AdaptiveTooltips-1.0.1-fabric-1.19.2.jar
- mods\Adorn-3.9.1+1.19.2-fabric.jar
- mods\AdvancementPlaques-1.19.2-fabric-1.4.6.jar
- mods\AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar.disabled
- mods\BetterF3-4.0.0-Fabric-1.19.2.jar
- mods\CITResewn-1.1.2+1.19.2.jar
- mods\CreativeCore_FABRIC_v2.9.4_mc1.19.2.jar
- mods\CullLessLeaves-1.0.6.jar
- mods\Debugify-2.8.0.jar.disabled
- mods\Iceberg-1.19.1-fabric-1.0.46.jar
- mods\InventoryProfilesNext-fabric-1.19-1.10.6.jar
- mods\MouseTweaks-fabric-mc1.19-2.22.jar
- mods\NoChatReports-FABRIC-1.19.2-v1.13.12.jar.disabled
- mods\YetAnotherConfigLib-2.2.0-for-1.19.2.jar
- mods\Zoomify-2.9.0.jar
- mods\advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
- mods\antighost-1.19.1-fabric0.58.5-1.1.5.jar
- mods\appleskin-fabric-mc1.19-2.4.1.jar
- mods\architectury-6.5.85-fabric.jar.disabled
- mods\badpackets-fabric-0.2.1.jar.disabled
- mods\betterbeds-1.2.0.jar
- mods\betterstats-2.9.3+1.19.2.jar
- mods\blur-2.6.0.jar
- mods\bobby-4.0.1.jar
- mods\capes-1.5.2+1.19.2-fabric.jar
- mods\chat_heads-0.10.19-fabric-1.19.2.jar
- mods\clickthrough-1.19.1-fabric0.58.5-0.4.jar
- mods\cloth-config-8.3.103-fabric.jar.disabled
- mods\continuity-2.0.2+1.19.jar
- mods\create-fabric-0.5.1-b-build.1089+mc1.19.2.jar
- mods\create_enchantment_industry-1.0.0.jar
- mods\creategoggles-1.19.2-0.5.5.c-[FABRIC].jar
- mods\dark-loading-screen-1.6.12.jar
- mods\dashloader-4.1.3+1.19.jar
- mods\dynamic-fps-2.2.0.jar
- mods\emotecraft-for-MC1.19.2-2.2.7-b.build.50-fabric.jar
- mods\enhancedblockentities-0.7.2+1.19.2.jar
- mods\entity_model_features_fabric_1.19.2-0.2.13.jar
- mods\entity_texture_features_fabric_1.19.2-4.4.4.jar
- mods\entityculling-fabric-1.6.1-mc1.19.2.jar
- mods\extrasounds-2.3.1+1.19.2-1.19.1.jar
- mods\fabric-api-0.76.0+1.19.2.jar.disabled
- mods\fabric-carpet-1.19.2-1.4.84+v221018.jar.disabled
- mods\fabric-language-kotlin-1.10.8+kotlin.1.9.0.jar.disabled
- mods\fabrishot-1.9.2.jar
- mods\fastquit-2.1.0+1.19-1.19.2.jar
- mods\indium-1.0.9+mc1.19.2.jar
- mods\iris-mc1.19.2-1.6.5.jar
- mods\jei-1.19.2-fabric-11.6.0.1016.jar
- mods\journeymap-1.19.2-5.9.7-fabric.jar.disabled
- mods\krypton-0.2.1.jar.disabled
- mods\lambdynamiclights-2.2.0+1.19.2.jar
- mods\language-reload-1.5.8+1.19.2.jar
- mods\lazydfu-0.1.3.jar.disabled
- mods\letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar.disabled
- mods\libIPN-fabric-1.19-3.0.2.jar
- mods\lithium-fabric-mc1.19.2-0.11.1.jar.disabled
- mods\main-menu-credits-1.1.1.jar
- mods\memoryleakfix-fabric-1.17+-1.1.1.jar.disabled
- mods\midnightlib-fabric-1.0.0.jar.disabled
- mods\modmenu-4.2.0-beta.2.jar
- mods\moonlight-1.19.2-2.2.43-fabric.jar
- mods\notenoughanimations-fabric-1.6.2-mc1.19.2.jar
- mods\phosphor-fabric-mc1.19.x-0.8.1.jar.disabled
- mods\reeses_sodium_options-1.6.4+mc1.19.2-build.93.jar.disabled
- mods\replaymod-1.19.2-2.6.13.jar
- mods\shulkerboxtooltip-fabric-3.2.2+1.19.2.jar
- mods\simple-rpc-fabric-1.19.x-3.2.3.jar
- mods\smoothboot-fabric-1.19-1.7.1.jar.disabled
- mods\sodium-extra-0.4.16+mc1.19.2-build.90.jar
- mods\sodium-fabric-mc1.19.2-0.4.4+build.18.jar
- mods\soundphysics-fabric-1.19.2-1.0.18.jar
- mods\spark-1.10.37-fabric.jar.disabled
- mods\stendhal-1.3.5-1.19.jar
- mods\supplementaries-1.19.2-2.3.20-fabric.jar
- mods\visuality-0.5.6.jar
- mods\voicechat-fabric-1.19.2-2.4.16.jar
- mods\vt-downloader-2.0.0.jar
- mods\wthit-fabric-5.18.0.jar.disabled
- options.txt
- resourcepacks
- saves
- screenshots
- shaderpacks
- texturepacks

Contents of mods/:

- Create_Deco_Casing_3.0.0_1.19_Fabric.jar
- litematica-fabric-1.19.2-0.12.7.jar
- malilib-fabric-1.19.2-0.13.0.jar

### Steps to reproduce

- Use macOS
- Import [Create Extra Full - 1.2.0](https://modrinth.com/modpack/create-extra/version/MqYT8IQ2)
- Let it create the instance
- Check .minecraft and find that some mods didn't get installed in the mods/ directory

### Suspected cause

The backslashes are used as file delimiters on Windows. Might have something to do with that?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
Multiple fixes and improvements regarding pack import:
- Replace `\` with `/` in the file path for modrinth export (this pack: https://modrinth.com/modpack/another-rpg-pack failed to correctly install because of this)
- Added a new dialog in pack import to ask the user what optional mods should be enabled (this is for both flame and modrinth)
- Fixed some issues introduced by  https://github.com/PrismLauncher/PrismLauncher/pull/1456
- Fixed #536
- Fixed #1652

### CODE REVIEW

**Comment by DioEgizio** [comment]
wouldn't not selecting a mod = not downloading it make more sense? this behavior is kinda weird. Apart from that this pr seems fine

**Comment by Trial97** [comment]
Well not really: If you would want to add them later how would you know what mods need to be added and what version?
Some alternatives would be:
- reading the manifest file and downloading the files yourself(that's not easy at all)
- if you have access to a modlist compare it with the current one and again download the correct versions of the mods you want
- reinstall the pack (this is the easier option) but would overwrite config and disabled mods

Also the previous implementation the mods are always downloaded but they are disabled if they are optional.

**Comment by DioEgizio** [comment]
https://docs.modrinth.com/docs/modpacks/format_definition/#env-optional

The modrinth docs seem to prefer the behaviour I mentioned (which is honestly the one which makes the most sense to me and it's what launchers that have this option do, and what we do for atlauncher packs)

honestly it doesn't make much sense to have the page if you're still gonna download it but disabled anyways

**Comment by TheKodeToad** [comment]
I think it's nice as it allows the user to review the mods which will be disabled by default

**Comment by Trial97** [comment]
In the documentation, I do not see anywhere how should I handle the unselected resources(doesn't say that I should not download them).
I  still want to keep them downloaded: in case you want to enable an optional mod in the future.
Also checked against : 
- curseforge downloads the optional and marks them as disabled
- modrinth downloads the optional and doesn't mark them as disabled

All of them download the optional files.

**Comment by TheKodeToad** [comment]
I assume in the case of Modrinth it is either unimplemented or a bug :P

**Comment by TheKodeToad** [comment]
Maybe we should stop checking extension and just add `.disabled`?

**Comment by Trial97** [comment]
I thought that was something modrinth does, on flame there is no such check.
I just copied the code from the previous implementation so we can drop it

**Comment by TheKodeToad** [comment]
Not necessarily in this pr - but resource packs etc. can also be optional

**Comment by nopeless** [comment]
hey @Trial97 , I like the pull request, but I think `[^a-zA-Z0-9]` is too restrictive.

something like `[\0-\31\/:*?"<>|]` would be better

**Comment by Trial97** [comment]
Hi @nopeless,
I'm not sure as I understand what you want to achieve with the new regex.
Why the need to change that?
Do we have collisions between the ATLauncher packs with the current regex?
We use that field only for the logo filename so if there are no collisions between the packs I would prefer to remain the same.

**Comment by nopeless** [comment]
> Hi @nopeless,
> I'm not sure as I understand what you want to achieve with the new regex.
> Why the need to change that?
> Do we have collisions between the ATLauncher packs with the current regex?
> We use that field only for the logo filename so if there are no collisions between the packs I would prefer to remain the same.

No, and I doubt there will be any collisions unless the filename is unicode (which is very unlikely either)

However, I don't see why the regexp has to be so restrictive either. If it needs to be filename safe, then the regex should show that intent. 

At the very least, I think you should add a space to the allow character list so spaces are preserved for easier reading in case of a need to debug.

**Comment by nopeless** [comment]
Or I may have misread the code I'm assuming `safeName` is for storing in local. If there's another use for it, I can see where I'm wrong

**Comment by Trial97** [comment]
That name is precisely only used when we import the pack to give the name of the icon of the pack, nothing else.
And I stand firm in my decision to not change the regex.
Obviously, if you understand what you do please open a PR with your suggested change, and explain why we would want that.

**Review by DioEgizio — APPROVED** [review]

**Review by TayouVR — APPROVED** [review]
everything seems to work in my testing.

this "Create Extra" pack from mr confused me a bit as it seems to put a lot of libraries like fabric API and fabric language kotlin, etc. as optional. But I guess thats just how it is..
It seems a bit odd to me, but I have to assume its just the pack making weird choices in what should be optional and what not...

~~UNLESS thats something coming from prism due to some dependency resolution stuff that needs to be considered here?~~ thats just how the pack comes, imma merge

image

**Pull request merged**
