### PR TITLE
Ensure that core mods tab is visible on correct versions

### PR DESCRIPTION
**Pull request by Trial97**
fixes the described behavior from #2017 where the core mods tab is visible on the latest forge versions

### CODE REVIEW

**Comment by TheKodeToad** [comment]
wouldn't it be better to update the tab when Forge is downloaded than to do this?

**Comment by Trial97** [comment]
The tab will be visible until you start the game.
Right now if you open the edit window that tab is visible(for new instances that do not have the version yet loaded).And is only visible on first view(if you close the window and open it again that tab is no longer there)
So if we do this when forge is downloaded then it would be already too late.

**Comment by TheKodeToad** [comment]
Forge's JSON file should automatically be downloaded 🤔

**Comment by Trial97** [comment]
Not really, it downloads but because it's async it is not instant resulting:
 - you open the window
 - if the file is not there download it 
 - because we do not for it to download we display the core mods tab
PS. Feel free to test it yourself(with and without my fix)

**Review by TheKodeToad — CHANGES_REQUESTED** [review]
This will cause a freeze which is worse than a delay. Please *try* an alternative like the one I suggested.

**Comment by TheKodeToad** [comment]
**Not a freeze, still quite weird behaviour though imo

**Comment by Trial97** [comment]
Fixed following you suggestion TheKobeToad

**Review by Ryex — APPROVED** [review]
starting the task if the Minecraft component and returning false hasn't been loaded seems like the correct move

**Comment by TheKodeToad** [comment]
Hmm, i really don't think a const getter method should have side-effects

**Comment by Trial97** [comment]
> Hmm, i really don't think a const getter method should have side-effects

 I moved that stuff inside the constructor.

**Review by TheKodeToad — APPROVED** [review]

**Pull request merged**
