### PR TITLE
8.0 staging merge

### LINKED ISSUE #1495: Combine the install mod loader buttons
### Role

I like to put together my own modded instances.

### Suggestion

The "Install Forge," "Install Fabric," "Install Quilt," and "Install LiteLoader" buttons in Edit Instance should all be combined into one "Install Mod Loader" button.

### Benefit

This would make the cluttered sidebar in Edit Instance a lot cleaner.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The button could open a popup with the same UI as the bottom of the New Instance window.
image

This suggestion would also affect #1356, which adds yet another mod loader!

### PR DESCRIPTION
**Pull request by Scrumplex**

### CODE REVIEW

**Review by TheKodeToad — APPROVED** [review]
(provided the actions pass, this is to allow merging)

**Comment by Trial97** [comment]
fixes #1495
Missed the chance to close it with this PR: https://github.com/PrismLauncher/PrismLauncher/pull/1230

**Review by Trial97 — APPROVED** [review]
needs at least two approvals right?

**Comment by Scrumplex** [comment]
I'll resolve the conflicts tomorrow

**Comment by TheKodeToad** [comment]
You have seven minutes :trollface:

**Comment by Scrumplex** [comment]
git commit history is so gonna be a mess :(

**Comment by Trial97** [comment]
Better a mess than a single gigantic commit with all these changes, right?

**Comment by Scrumplex** [comment]
still conflicting. I need some time to focus on resolving

**Comment by Trial97** [comment]
Is this enough for merge conflicts: https://github.com/PrismLauncher/PrismLauncher/compare/staging...Trial97:PrismLauncher:staging?expand=1 or do you have something more fancy?

**Pull request merged**
