### PR TITLE
feat:neoforge can download forge mods

### PR DESCRIPTION
**Pull request by Trial97**
Parent PR: #1498 

Until we implement multiple loaders filter(for flame provider) or neoforge drops forge support we should consider using the same approach that we use for fabric and quilt.
And yes I know that curseforge has added a new parameter to the search API that you can specify multiple loader types.
But it has yet to implement the same functionality for the get versions API.

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]
While this is fine right now, they did announce that the next NeoForge versions are gonna start breaking things. This could very well be within the our own release window

**Comment by TheKodeToad** [comment]
I think we should just implement multiple loader filters... is that not possible right now?

**Comment by Trial97** [comment]
I don't know if somebody started working on it, but until then this can be a workaround until that is implemented.
Let me know if somebody wants to implement it, as I may start working on that next.

**Comment by TheKodeToad** [comment]
surely it's not too hard to implement? it doesn't feel necessary to create a temporary workaround.

**Comment by TheKodeToad** [comment]
I'm working on this right now, so no need for you to do so :P

**Review by TheKodeToad — APPROVED** [review]
As you can see, I tried implementing it properly and over 10 hours later it somehow isn't done lol

**Pull request merged**
