### PR TITLE
Fix demo mode

### LINKED ISSUE #1705: Minecraft 1.20.2 crashes with exit code 65, "Invalid argument"
### Operating System

_Fedora 38 KDE on BTRFS_

### Version of Prism Launcher

Prism Launcher 7.2 installed from the Copr repo for Fedora 38.

### Version of Qt

Qt 5.15.10; default Qt bundled with KDE 5.27

### Description of bug

I have a fresh install of Prism Launcher 7.2. If I try to launch Minecraft 1.20.2, it crashes with exit code no. 65.

### Steps to reproduce

I have no idea how to reproduce this error, but I am running a fresh install of Fedora 38 on BTRFS. I tried it with both Java 17 and 21.

### Suspected cause

This error might have occurred due to my system's filesystem. It uses BTRFS instead of EXT4 like any other Linux distribution.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #1810: Play Demo mode crashes with an account that doesn't own Minecraft
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

When launching Demo mode with an account that doesn't have Minecraft, Prism Launcher crashes. However if you do the same with a normal account it does not.

### Steps to reproduce

1. Use a Microsoft account that doesn't have Minecraft
2. Try loading Minecraft
3. Crashes

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #1810
fixes #1705 (made sure the uuid is always non empty)
and also enables players to play demo without a owning Minecraft copy
As I touched some auth stuff Scrumplex I request your review on this.

### CODE REVIEW

**Review by wamserma — COMMENTED** [review]
Tested on top of the 8.0 release with a pretty pristine Microsoft Account. Created a XBox profile (otherwise the account couldn't be added) and used this account to log in to minecraft.net.
While I get the option to choose Demo mode when attempting to launch, there still seems to be an issue with the UUID:

```
Params:
  --username  --version 1.20.4 --gameDir /home/XXX/.local/share/PrismLauncher/instances/1.20.4/.minecraft --assetsDir /home/XXX/.local/share/PrismLauncher/assets --assetIndex 12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 10599


Illegal argument
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.base/java.util.UUID.fromString1(UUID.java:280)
	at java.base/java.util.UUID.fromString(UUID.java:258)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:151)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ILLEGAL_ARGUMENT
Der Prozess wurde mit Status 65 beendet.
```

**Comment by Trial97** [comment]
Try without an account(I will stil try to reproduce what you discribed)

**Comment by wamserma** [comment]
> Try without an account(I will stil try to reproduce what you discribed)

The account was required as otherwise PrismLauncher wouldn't download game assets (jars). After removing all account PrismLauncher asks me to add an account, even when selecting Demo mode. If I decline to add an account, launching aborts. If I accept , but close the config window without adding an account, I'm presented with an empty account selection dialog and launching aborts after pressing OK.

Only output is on terminal:
```
264.009 D | Paged dialog close requested
   264.010 D | Sorting icon list...
   264.011 D | Detecting proxy settings...
   264.011 D | Using no proxy is an option!
   264.011 D | Paged dialog close approved
   264.011 D | Paged dialog geometry saved
   264.053 D | Discovering instances in "/home/XXX/.local/share/PrismLauncher/instances"
   264.053 D | Found instance ID "1.20.4"
   264.054 D | Should keep and soft-reload "1.20.4"
   264.071 D | 1
```

**Comment by Trial97** [comment]
Nope, I'm not able to reproduce it at all. No account was required for me,I was able to launch demo mode with and without it.

**Comment by wamserma** [comment]
My bad, mixed up builds and tested against upstream 🙄 
Your commit applies cleanly to release tag 8.0 and works as expected (could launch demo without an account configured).

**Review by wamserma — APPROVED** [review]
Tested on top of release 8.0.

**Review by TayouVR — APPROVED** [review]
forgor to review, got too carried away playing demo mode 😄 

So; I don't have a MS account that doesn't own MC... so can't test that, 
but just tested by messing up the token for my account, making it invalid and all seems to work with playing demo.

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
