### PR TITLE
Create empty pack action

### PR DESCRIPTION
**Pull request by TheKodeToad**
image

### CODE REVIEW

**Comment by Scrumplex** [comment]
What is the use-case?

**Comment by TheKodeToad** [comment]
Oops. I think I missed this! Sorry.

Basically I find it quite awkward to create a blank resource pack sometimes...
Maybe I didn't need to add it to the milestone since I wasn't totally sure about it :woman_shrugging:

**Comment by getchoo** [comment]
> Basically I find it quite awkward to create a blank resource pack sometimes...

imo, this would be better suited to a different tool like a shell script. i don't really see how this would be used in the launcher

**Comment by TheKodeToad** [comment]
> imo, this would be better suited to a different tool like a shell script. i don't really see how this would be used in the launcher

I don't see how it's very different to any of the other resource pack management functions. It's just convenience imo.

You certainly don't need a launcher to delete a file. Also, the script would need to determine the Minecraft version and work out its pack format...

**Comment by getchoo** [comment]
> I don't see how it's very different to any of the other resource pack management functions. It's just convenience imo.

other resource pack functions give end users something they can use in-game. here they're just getting what's virtually an empty directory, which would only really be used by developers - who probably know how to create the short mcmeta file. it is convenient though, i'll admit, i'm just not sure if it's worth it to add here since manual intervention will still be required to actually make a real resource pack.

> You certainly don't need a launcher to delete a file

sure, but it makes sense when you're also adding files using the same interface. this isn't really comparable to something few people would be likely to use, let alone when it doesn't really add anything to your game

>  Also, the script would need to determine the Minecraft version and work out its pack format...

i don't think this is very difficult for people making resource packs, especially when you would still need to look for it in the current implementation when you aren't making a resource pack for the same version as the current instance. the minecraft wiki also has [very helpful information](https://minecraft.fandom.com/wiki/Tutorials/Creating_a_resource_pack#%22pack_format%22) on this

**Comment by TheKodeToad** [comment]
The idea is it can maybe be expanded on and have other features such as to extract the vanilla resource pack

**Comment by TheKodeToad** [comment]
Honestly, I was just experimenting with an idea and it was quick to implement so I'm not too bothered!

Adding it to a milestone was probably a mistake considering I didn't consult anyone else. oh well.

**Comment by getchoo** [comment]
> The idea is it can maybe be expanded on and have other features such as to extract the vanilla resource pack

i still think that could be a little out of scope for launcher (since it's still a little niche and not very similar to other functions besides maybe exports i guess?), but i think it would be much more interesting to see a full implementation like that in the future :)

**Comment by TheKodeToad** [comment]
yeah. should I mark this as draft then so I can add that in future?

**Comment by getchoo** [comment]
i think that'd be a good idea. it'd make it a lot easier to revisit :)

**Comment by ditto-ditto-ditto** [comment]
If extracting the vanilla resources does get added, I would like to see the ability to extract mod resources as well. Could definitely see it being outside of scope of prism though.

**Comment by TheKodeToad** [comment]
I don't think this will go anywhere
Maybe it could be revisited if there's more demand

**Pull request closed without merging**
