### PR TITLE
Fix resetting settings when saving

### LINKED ISSUE #1856: "Keep play time" in instance copying is ignored
### Operating System

_No response_

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

Regardless of the "Keep play time" toggle being set or not, play time will always be copied over when copying an instance

### Steps to reproduce

1. Copy an instance with playtime
2. Notice how the "Keep play time" option is ignored, and play time is copied over regardless

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #1856
And most probably other issues where the setting was reset but persisted on save.

### CODE REVIEW

**Comment by TheKodeToad** [comment]
I haven't tested but this probably causes the state of columns being shown/hidden to be reset in some cases.

**Comment by Trial97** [comment]
> I haven't tested but this probably causes the state of columns being shown/hidden to be reset in some cases.

It shouldn't. The clear happens on the written-in file settings, but their value should already be in memory as we want to write them, so unless we reset the setting that will not happen(also from my testing I could not reproduce it). 
Please test it out but this should have no implication for the column state.
For column stuff look here: https://github.com/PrismLauncher/PrismLauncher/pull/1849

**Comment by TheKodeToad** [comment]
Oh, it should be fine. Unregistered settings will still be preserved, right?

**Review by TheKodeToad — APPROVED** [review]

**Comment by Trial97** [comment]
> Unregistered settings will still be preserved, right?

So long they were saved before yes.
This PR only brings back the old functionality where on save the file was replaced instead of merged.

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
