### PR TITLE
Update of logos

### PR DESCRIPTION
**Pull request by ColonelGerdauf**
This is intended to have Forge and Quilt remain visible in multiple conditions while becoming more floaty.

With Quilt specifically, the original logo was a bit too small for the scope and visual size of the Prism launcher.

### CODE REVIEW

**Comment by Trial97** [comment]
I don't think this is necessary needed:
- the rift is not used so why should we include the logo? At least not until we have rift supported
- the size of the logos should not be a problem: they are SVG and should scale without any issues
- do we have the right to use the new files? I do believe that when the original ones were added Scrumplex did ask  around if we could use them in Prism

**Comment by Scrumplex** [comment]
> do we have the right to use the new files? I do believe that when the original ones were added Scrumplex did ask around if we could use them in Prism

Forge branding was determined to be LGPL2 by LexManos.

No idea about Rift

Quilt is CC0 iirc

**Comment by ColonelGerdauf** [comment]
> the size of the logos should not be a problem: they are SVG and should scale without any issues

I was speaking of relative visibility of the logo. It being scalable does not matter much when in the places they are used they are quite small. Also, the size of the actual logo in relation to the rest of the SVG does not align with the likes of NeoForge(d) or LiteLoader, which are quite large and floaty.

**Comment by TheKodeToad** [comment]
- Forge has a background for contrast.
- Quilt has a background for consistency (it is used in the site's favicon and on the Discord server).

**Pull request closed without merging**
