### PR TITLE
Lossless image asset compression

### PR DESCRIPTION
**Pull request by Awqre**
Applied lossless zopfli/ect/deflopt compression to PNG files including ones contained in ICO files.

Repacked ICO files with optidash icopack
Repacked ICNS with icnsutil

### CODE REVIEW

**Review by TheKodeToad — APPROVED** [review]

**Review by Trial97 — APPROVED** [review]

**Review by Ryex — APPROVED** [review]

**Comment by Ryex** [comment]
Any chance you could add add a bash or similar script that would replicates most or all of these operations on an arbitrary file in case we change or add resources in the future?

**Comment by txtsd** [comment]
I'm able to compress files even further using `oxipng`. Let me append to this PR before merging.


```
1708 bytes (0.29% smaller): ./launcher/resources/multimc/48x48/log.png
1246 bytes (6.10% smaller): ./launcher/resources/multimc/50x50/instances/enderman_legacy.png
1265 bytes (5.74% smaller): ./launcher/resources/multimc/48x48/viewfolder.png
1677 bytes (0.12% smaller): ./launcher/resources/multimc/24x24/resourcepacks.png
3768 bytes (1.44% smaller): ./launcher/resources/multimc/48x48/worlds.png
2759 bytes (1.43% smaller): ./launcher/resources/multimc/48x48/star.png
3411 bytes (4.77% smaller): ./launcher/resources/multimc/48x48/checkupdate.png
2000 bytes (20.67% smaller): ./launcher/resources/multimc/48x48/cat.png
589 bytes (2.97% smaller): ./launcher/resources/multimc/24x24/log.png
1451 bytes (0.07% smaller): ./launcher/resources/multimc/24x24/minecraft.png
4556 bytes (0.15% smaller): ./launcher/resources/multimc/48x48/minecraft.png
2211 bytes (0.18% smaller): ./launcher/resources/multimc/48x48/new.png
2403 bytes (0.66% smaller): ./launcher/resources/multimc/32x32/resourcepacks.png
2259 bytes (7.00% smaller): ./launcher/resources/multimc/32x32/instance-settings.png
850 bytes (11.27% smaller): ./launcher/resources/multimc/32x32/viewfolder.png
43656 bytes (2.38% smaller): ./launcher/resources/backgrounds/rory-flat.png
2259 bytes (7.00% smaller): ./launcher/resources/multimc/32x32/settings.png
1779 bytes (1.55% smaller): ./launcher/resources/multimc/48x48/status-good.png
917 bytes (0.33% smaller): ./launcher/resources/multimc/32x32/status-yellow.png
1308 bytes (8.60% smaller): ./launcher/resources/multimc/22x22/instance-settings.png
832 bytes (29.19% smaller): ./launcher/resources/multimc/24x24/cat.png
3432 bytes (5.38% smaller): ./launcher/resources/multimc/48x48/refresh.png
48339 bytes (2.85% smaller): ./launcher/resources/backgrounds/rory-flat-bday.png
1530 bytes (0.39% smaller): ./launcher/resources/multimc/48x48/status-bad.png
474 bytes (0.21% smaller): ./launcher/resources/multimc/22x22/viewfolder.png
49917 bytes (3.66% smaller): ./launcher/resources/backgrounds/rory-flat-xmas.png
173755 bytes (0.66% smaller): ./launcher/resources/backgrounds/teawie-spooky.png
1009 bytes (1.27% smaller): ./launcher/resources/multimc/22x22/bug.png
1046 bytes (0.19% smaller): ./launcher/resources/multimc/32x32/status-good.png
1308 bytes (8.60% smaller): ./launcher/resources/multimc/22x22/settings.png
1146 bytes (3.05% smaller): ./launcher/resources/multimc/22x22/refresh.png
905 bytes (0.22% smaller): ./launcher/resources/multimc/22x22/new.png
739 bytes (19.32% smaller): ./launcher/resources/multimc/22x22/cat.png
2335 bytes (0.72% smaller): ./launcher/resources/multimc/32x32/minecraft.png
1949 bytes (6.07% smaller): ./launcher/resources/multimc/32x32/refresh.png
161740 bytes (1.12% smaller): ./launcher/resources/backgrounds/teawie-bday.png
1149 bytes (26.95% smaller): ./launcher/resources/multimc/32x32/cat.png
791 bytes (6.94% smaller): ./launcher/resources/multimc/32x32/log.png
887 bytes (0.34% smaller): ./launcher/resources/multimc/32x32/status-bad.png
969 bytes (1.82% smaller): ./launcher/resources/multimc/32x32/instances/chicken_legacy.png
2171 bytes (1.09% smaller): ./launcher/resources/multimc/32x32/worlds.png
442 bytes (4.12% smaller): ./launcher/resources/multimc/22x22/copy.png
1442 bytes (0.69% smaller): ./launcher/resources/multimc/32x32/instances/ftb_logo_legacy.png
229 bytes (0.43% smaller): ./launcher/resources/multimc/32x32/instances/tnt_legacy.png
1490 bytes (0.13% smaller): ./launcher/resources/multimc/32x32/star.png
3068 bytes (18.49% smaller): ./launcher/resources/multimc/64x64/cat.png
1899 bytes (1.20% smaller): ./launcher/resources/multimc/64x64/status-yellow.png
2268 bytes (1.56% smaller): ./launcher/resources/multimc/64x64/status-good.png
5138 bytes (4.00% smaller): ./launcher/resources/multimc/64x64/refresh.png
1453 bytes (1.16% smaller): ./launcher/resources/multimc/64x64/viewfolder.png
5981 bytes (0.68% smaller): ./launcher/resources/multimc/64x64/resourcepacks.png
4445 bytes (1.53% smaller): ./launcher/resources/multimc/128x128/instances/herobrine_legacy.png
18514 bytes (2.27% smaller): ./launcher/resources/multimc/128x128/instances/enderpearl_legacy.png
6901 bytes (0.46% smaller): ./launcher/resources/multimc/64x64/worlds.png
1902 bytes (3.55% smaller): ./launcher/resources/multimc/64x64/status-bad.png
4932 bytes (3.33% smaller): ./launcher/resources/multimc/64x64/checkupdate.png
3112 bytes (1.43% smaller): ./launcher/resources/multimc/64x64/new.png
857 bytes (6.03% smaller): ./launcher/resources/multimc/16x16/instance-settings.png
2412 bytes (0.33% smaller): ./launcher/resources/multimc/64x64/log.png
4247 bytes (0.38% smaller): ./launcher/resources/multimc/64x64/coremods.png
176 bytes (7.85% smaller): ./launcher/resources/multimc/16x16/noaccount.png
10528 bytes (22.26% smaller): ./launcher/resources/multimc/scalable/atlauncher-placeholder.png
857 bytes (6.03% smaller): ./launcher/resources/multimc/16x16/settings.png
318 bytes (2.75% smaller): ./launcher/resources/multimc/16x16/log.png
608 bytes (1.62% smaller): ./launcher/resources/multimc/16x16/bug.png
826 bytes (0.24% smaller): ./launcher/resources/multimc/16x16/refresh.png
525 bytes (25.74% smaller): ./launcher/resources/multimc/16x16/cat.png
```

**Review by txtsd — CHANGES_REQUESTED** [review]
`sips` is known to output badly scaled images, so I changed the genicons script to use the same method on macOS as on windows.

Someone who has a mac, please run the script and commit the icns file.

**Comment by txtsd** [comment]
Added a `scripts/compress_images.sh` to help us in the future.

**Comment by Awqre** [comment]
> Added a `scripts/compress_images.sh` to help us in the future.

For this application I assume it's not gonna cause issues but "--strip all" will convert any animated PNGs to static. I was surprised OxiPNG was able to improve sizes considering in the past it was always worse than other options, maybe it's because I never apply --alpha since it's technically lossy but I'll test it out again. Thanks for going through the extra steps!

For ICO generation, I've found that the [Optidash version of icopack](https://github.com/optidash-ai/icopack) can combine post-optimized images and gives much better results.

**Comment by txtsd** [comment]
> I was surprised OxiPNG was able to improve sizes considering in the past it was always worse than other options, maybe it's because I never apply --alpha since it's technically lossy but I'll test it out again. Thanks for going through the extra steps!

I might have been a little responsible for that https://github.com/shssoichiro/oxipng/issues/444

> For ICO generation, I've found that the [Optidash version of icopack](https://github.com/optidash-ai/icopack) can combine post-optimized images and gives much better results.

Thanks! I will take a look at Optidash. I don't think we can include a script in the repo invoking an [unpackaged tool](https://repology.org/projects/?search=optidash) though.

**Review by txtsd — APPROVED** [review]
We can add the icns file in another PR no problemo

**Pull request merged**
