### PR TITLE
Improve approachability

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
This adds additional links, such as contact information to make it more approachable for users if they need help or want to contribute.

This MR does the following changes/additions:
- adds [additional categories](https://specifications.freedesktop.org/menu-spec/latest/apas02.html) (search for "game" in the page)
- adds `multimc` and `polymc` as keywords, in case someone is migrating from MultiMC or PolyMC, but are used to typing the aforementioned names in the app menu
- adds URL types in appstream
- changes developer name to "PrismLauncher Contributors" ("Authors" is a good alternative if "Contributors" is rejected)
- fixes minor typos

---

https://github.com/PrismLauncher/PrismLauncher/blob/325e58d98c26fb802956de75e8ddfcfe0d9e3782/program_info/org.prismlauncher.PrismLauncher.metainfo.xml.in#L4-L6

These lines were removed as they were reported as circular dependencies per `appstreamcli`:
```
❯ appstreamcli validate program_info/org.prismlauncher.PrismLauncher.metainfo.xml.in
W: org.prismlauncher.PrismLauncher:5: circular-component-relation

✘ Validation failed: warnings: 1, pedantic: 2
```

What needs to be addressed:
- [x] URL type for translations
- [x] Is the name "Prism Launcher" or "PrismLauncher"? I need this so I can properly set the name in the appstream file.

---

I'm marking as draft to encourage a discussion in some topics prior to merging (or rejecting).

~~Blocked by https://github.com/PrismLauncher/PrismLauncher/issues/41.~~

### CODE REVIEW

**Comment by CodexNotFound** [comment]
> Is the name "Prism Launcher" or "PrismLauncher"? I need this so I can properly set the name in the appstream file.

It's `Prism Launcher`, two seperate words

**Comment by tobimori** [comment]
Naming guidelines:
Display Name: Prism Launcher
Slug (package name): prismlauncher
Alternative Slug: PrismLauncher
App ID: org.prismlauncher.PrismLauncher

**Comment by TheEvilSkeleton** [comment]
Alright, all we need is a translation link now.

**Comment by TheEvilSkeleton** [comment]
Should be good to go.

**Review by Scrumplex — APPROVED** [review]
LGTM, Thanks!

**Review by flowln — APPROVED** [review]
thanks!

**Pull request merged**
