### PR TITLE
Improve wizard page

### LINKED ISSUE #949: Add login to onboarding
### Role

A new user

### Suggestion

I want Prism to prompt me to login when I open it for the first time

### Benefit

In order to play Minecraft

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As it currently stands, users must know to create an instance and will then see the login prompt:
image
This could be much better.

I'd also like to see that message mention that the Mojang or Microsoft account must have a license to Minecraft. 

Prism already has a quick setup on first launch where it asks users to select a language and a Java executable. Logging in should be part of this quick setup as it's not clear where to start.

image
It's also quite empty. This should have some sort of text that informs users that they can add an instance by clicking on "Add Instance". If this is something skippable like the language selection prompt in the quick setup, it should also inform users when they haven't added an account that they will be unable to play, should they skip that in the quick setup. It should also inform users when they haven't added a path Java executable (as that can be skipped for each launch). 

image
This message should state that their account must have a license to Minecraft, and that Mojang accounts are only capable of playing offline and that users must migrate to a Microsoft account for online functionality.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #949
also the java: https://discord.com/channels/1031648380885147709/1031682669945294869/1278406211875897374

### CODE REVIEW

**Comment by TayouVR** [comment]
can we squeeze the account add thing into a wizard page so it doesn't look so out of place?

**Comment by Trial97** [comment]
> can we squeeze the account add thing into a wizard page so it doesn't look so out of place?

I would need to recode the whole thing so no. I accept PRs if you want that.
Also I can separate the two stuff: java redesign in one PR and the other for the login onboarding

**Comment by TayouVR** [comment]
ehh, this is better than what we had and I don't have the time to do it myself...

**Review by TayouVR — APPROVED** [review]

**Review by Ryex — APPROVED** [review]
Tested. personaly I think the account add dialog to add one account is sufficient for the setup process.

**Comment by ZekeZDev** [comment]
Looks good so far however I have a couple nitpicks that would need to be made before id want to merge. 

As I discussed previously is there a way that we can remove the "Automatic Java Download" popup. 
image
this should be redundant as the next page is the java settings and has a checkbox to enable/disable it. 

Speaking of the next java page, the wording has not been updated to reflect the new functionality:
"You do not have a working Java set up yet or it went missing. Please select one of the following or browse for Java executable"
image

I suggested an alternative text for this in the mockup, feel free to change the wording:
"Please select how much memory to allocate to instances and if Prism Launcher should manage java automatically or manually."

Also due to the login wizard being a seperate widget and not offering a way to return to the setup wizard I think it would make sense for the final theming page to instead of have "next" have a "finish" button. This then indicates you wont be able to click a back button in the next step.

**Comment by ZekeZDev** [comment]
oh and also I found a bug that occasionally happens when you cancel the login section:
image

**Review by ZekeZDev — APPROVED** [review]
LGTM!

**Pull request merged**
