### PR TITLE
Fix crash on invalid CurseForge link on import

### LINKED ISSUE #2290: Crash When Trying to Import Curseforge Modpack from URL
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

Prism launcher crashes to desktop when entering "curseforge://" into the link field of the add instance menu.

### Steps to reproduce

* Click "Add Instance".
* Open "Import" tab.
* Type "curseforge://" into the "Local file or link to direct download" field, Prism Launcher crashes.

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #2290

### CODE REVIEW

**Review by TheKodeToad — CHANGES_REQUESTED** [review]
Why not show a MessageBox like with other errors?

**Comment by Trial97** [comment]
Because is not an error per see: it is just an incomplete link

**Review by TayouVR — APPROVED** [review]

**Comment by TheKodeToad** [comment]
> Because is not an error per see: it is just an incomplete link

It's an error with the input. Isn't it better to show something instead of just closing the dialog?

**Comment by Trial97** [comment]
> It's an error with the input. Isn't it better to show something instead of just closing the dialog?

No, it is not, and the dialog doesn't close on that function end. 
Did you test this PR or are you just assuming stuff based on code?

**Review by TheKodeToad — APPROVED** [review]

**Pull request merged**
