### PR TITLE
Add UserData as another posible path for portable builds

### LINKED ISSUE #139: Make portable version have a dedicated user data directory
### Role

I am a Prism Launcher user and Prism Launcher Scoop packager.

### Suggestion

I want there to be a dedicated user data directory folder for the portable version of Prism Launcher on Windows.

### Benefit

It would be more organised (more simple and easy) and it would mean that I could make a portable Scoop package for Prism Launcher (currently I can not due to this issue https://github.com/ScoopInstaller/Scoop/issues/1372#issuecomment-304462955).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### PR DESCRIPTION
**Pull request by Trial97**
fixes #139 
I choose `UserData` as simply `data` was too generic and I did not want the space from `User data` suggestion.
The name can be changed if needed.

### CODE REVIEW

**Review by TayouVR — CHANGES_REQUESTED** [review]
This does work as intended, **if** i create the directory myself. 

I am not sure, but was the directory supposed to be created by the launcher?
Reading the linked issue it does sound like the folder should be always there when running portable.

to do that, I would add something like this above, though there might be a better way to go on about it? 
```cpp
if (!QFile::exists(FS::PathCombine(m_rootPath, "prismlauncher.cfg")) {
    // create UserData dir
}
```
or migrate the loose folders into `UserData`, but I feel that would be more error prone and might mess some peoples setups up.

**Comment by Trial97** [comment]
The initial scope of this PR was just to see if the folder exists and use that if not go to the next option.
That's why I did not create it by default, leaving the creation to the package managers.

**Review by TayouVR — APPROVED** [review]
ah, in that case, it works. ^^

**Review by TheKodeToad — APPROVED** [review]

**Comment by Ryex** [comment]
Just a heads up, we probably want this behavior to trigger only if `portable.txt` also exists. otherwise we might get some off behavior with the updater

**Comment by Trial97** [comment]
I did forgot about updater( so I need to add it there also)
 done here:https://github.com/PrismLauncher/PrismLauncher/pull/2589

**Pull request merged**
