### PR TITLE
Remove the PolyMC meta URL and replace it with the recommended meta URL

### PR DESCRIPTION
**Pull request by pandaninjas**
Signed-off-by: pandaninjas <101084582+pandaninjas@users.noreply.github.com>

### CODE REVIEW

**Comment by NotJansel** [comment]
were already setting up a seperate meta for this

**Review by TheAirBlow — COMMENTED** [review]
Why is the commit name "Update CMakeLists.txt"?
The commit name should explain what it does.

**Comment by Scrumplex** [comment]
Thanks, but we will handle this in #13

**Comment by hollymlem** [comment]
> Why is the commit name "Update CMakeLists.txt"?
> The commit name should explain what it does.

That's the default commit text

**Comment by TheAirBlow** [comment]
> > Why is the commit name "Update CMakeLists.txt"?
> > The commit name should explain what it does.
> 
> That's the default commit text

IK, and that's the point

**Pull request closed without merging**
