### PR TITLE
[macOS] Add code signing and notarization

### LINKED ISSUE #141: PrismLauncher.app is blocked by Gatekeeper on macOS because it is signed with an ad-hoc signature
### Operating System

macOS 12.6 (ARM)

### Version of PolyMC

Prism Launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

Launching PrismLauncher.app for the first time results in an error message from Gatekeeper on macOS due to the app not being signed with a Developer ID. While this can be worked around by right-clicking and selecting "Open" a second time, it's still a bit annoying and it would be nice if the app could be signed so it can be opened on the first attempt.

Running `codesign -dvv /Applications/PrismLauncher.app` shows that the application has an ad-hoc signature, and running `spctl -a -t exec -vv /Applications/PrismLauncher.app` shows that the app's signature is rejected.

See also:
* <https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG211>
* <https://developer.apple.com/support/code-signing/>
* <https://developer.apple.com/developer-id/>

### Steps to reproduce

n/a

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #141

# TODO
- [x] Add Actions variables
- [x] Update Sparkle appcast to support Prism Launcher `.zip` releases (See https://github.com/PrismLauncher/prismlauncher.org/pull/396)

### CODE REVIEW

**Comment by Scrumplex** [comment]
Perhaps it is also time to split up our builds into separate workflows

**Review by Trial97 — APPROVED** [review]

**Comment by Trial97** [comment]
Will the change from tar.gz to zip impact in any way the mac updater?

**Comment by Scrumplex** [comment]
> Will the change from tar.gz to zip impact in any way the mac updater?

It should work fine with the PR I linked above

**Review by DioEgizio — APPROVED** [review]

**Comment by txtsd** [comment]
Finally! 🤤

**Pull request merged**
