### PR TITLE
Fixes to CI

### PR DESCRIPTION
**Pull request by DioEgizio**
Some fixes, the commit messages are self explanatory

### CODE REVIEW

**Comment by flowln** [comment]
i think you should probably fix the CodeQL error before merging :iea:

**Comment by DioEgizio** [comment]
> i think you should probably fix the CodeQL error before merging :iea:

Out of scope for this pr :blobfoxpeek:

**Comment by flowln** [comment]
> Out of scope for this pr :blobfoxpeek:

it will cause errors in every PR based on develop after this is merged, and until someone fixes it :eyes:

**Comment by DioEgizio** [comment]
image


Feel free to push ;)

**Comment by flowln** [comment]
> Feel free to push ;)

~or i can just not approve it until you fix it~ /hj

**Review by txtsd — APPROVED** [review]
The CodeQL error is from other PRs so I think it's okay to merge this and deal with the CodeQL errors as they appear in PRs.

**Review by txtsd — APPROVED** [review]
Nice! You fixed it!

**Review by flowln — APPROVED** [review]

**Pull request merged**
