### PR TITLE
Reintroduce parsing of INI files

### LINKED ISSUE #1168: Older Technic packs on 1.4.7 and 1.5.2 fail to install
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.1

### Description of bug

Some older Technic platform modpacks fail to install, throwing an error stating `Invalid "forgeversion.properties"!`. This appears to be isolated to packs running on Forge for MC 1.4.7 and 1.5.2.

### Steps to reproduce

* Create a new instance using the Technic platform.
* Select a modpack which runs on Forge for MC 1.4.7 or 1.5.2. One known pack which can be used for testing is Tekkit Lite.
* Attempt to install the pack. Prism will successfully download all the pack's mods, but then fail to complete the installation.

### Suspected cause

I've spent a while trying to debug the issue, and I believe that I've managed to isolate the cause of the bug.
As far as I can tell, the issue was introduced by changes made to [launcher/settings/INIFile.cpp](https://github.com/PrismLauncher/PrismLauncher/blob/b174f8226132a5484aa3b1421352a929372ed2b0/launcher/settings/INIFile.cpp) in https://github.com/PrismLauncher/PrismLauncher/commit/788fa40c2ae0e9786c070f4593a4e7ff6efc77d3 - this commit removed the code from the INI file handler which allowed it to be passed a file as a QByteArray rather than being passed a filename.

I suspect that this change broke the code at at [launcher/modplatform/technic/TechnicPackProcessor.cpp, lines 108-124](https://github.com/PrismLauncher/PrismLauncher/blob/b174f8226132a5484aa3b1421352a929372ed2b0/launcher/modplatform/technic/TechnicPackProcessor.cpp#L108-L124), which handles Technic modpacks on these Forge versions, as this code attempts to pass a QByteArray to `INIFile.loadFile`.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #1168

### CODE REVIEW

**Comment by TheKodeToad** [comment]
I was working on another solution which involved parsing Java properties files in a more correct way, but I doubt it would have any difference in practice since the files we deal with happen to also be valid ini files! :P

**Comment by Trial97** [comment]
> I was working on another solution which involved parsing Java properties files in a more correct way, but I doubt it would have any difference in practice since the files we deal with happen to also be valid ini files! :P

If your solution is cleaner I can close this PR but just make sure that your solution includes the 2 technic loadFiles(fmlVersionData and forgeVersionData) and the one from launcher/minecraft/mod/tasks/LocalModParseTask.cpp that I reverted back in this PR.

**Comment by TheKodeToad** [comment]
Honestly it wasn't very clean. this is more concise :D

there are just a lot of cases where parsing properties files as though they are ini files won't work correctly such as `key:value`, `key value`, `"value"`, `value\[newline]continued`, `\u[codepoint]`, `! comment`

**Review by TheKodeToad — APPROVED** [review]

**Review by AnnaThorne — APPROVED** [review]
nice!

**Comment by TheKodeToad** [comment]
this will also use the old parsing, maybe that's good to ensure it doesn't create issues

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
