### PR TITLE
add additional minecraft arguments setting

### LINKED ISSUE #2656: Support for the --resourcePackDir argument to change your resource pack folder
### Role

I use different instances of mc

### Suggestion

Add an option to specify a resource pack folder as a directory, which then gets sent to the game with --resourcePackDir

### Benefit

Won't have to copy over resource packs which take a good amount of space, also allows for shared packs, likely on most versions

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently possible by editing the minecraft launch json

### PR DESCRIPTION
**Pull request by Trial97**
Adds a new Minecraft setting for adding extra Mc arguments.
See: https://github.com/PrismLauncher/PrismLauncher/issues/797#issuecomment-2217037201 (hope that there will be a separate issue)
fixes #2656

### CODE REVIEW

**Review by Ryex — APPROVED** [review]

**Comment by TheKodeToad** [comment]
This seems pretty niche and the options are undocumented so I think it's better to have our own ui for any special options that are useful (although we should probably rework arguments in meta)

**Comment by Trial97** [comment]
> This seems pretty niche and the options are undocumented so I think it's better to have our own ui for any special options that are useful (although we should probably rework arguments in meta)

Because the options are undocumented leave that as just a text area, this is clearly meant for some edge cases where the user knows what he is doing. Also like you mentioned this is `pretty niche` so why should we complicate with more than a text area?

**Comment by TheKodeToad** [comment]
For the user to work out the options, they'd need to read Minecraft's source code as far as I know (although perhaps they are documented on the wiki). I think everyone else is going to put the Java options in there by mistake. We already do have proxy settings, it's pretty weird that you need to use a separate setting. Also, sometimes arguments are positional; this doesn't let you override them but the existing components do.

Perhaps an annoyance with components is changing versions, but you can simply create a new empty component which will take precedence. Also, the format of these arguments do vary between versions and loaders/launchers and may cause errors.

**Comment by Trial97** [comment]
Again, I'm planning on this for advanced users. 

The setting is harder to find than the java (java argument box will always be shown first).
Because the arguments may not be supported by each MC version I don't want to add them by default(we would have a similar case as we had with the start maximized option).
And adding meta support for this to fetch all possible args and stuff looks like an overkill.

If you have any cleaner solution for the changing versions stuff please do post them on the associated issues(and optionally close them as completed).

And this is not only for proxy settings(see the second issue associated)

**Comment by TheKodeToad** [comment]
Good point! Perhaps we could have traits in a similar way to how server arguments are determined: SupportsResourcePackDir perhaps, and better indicate that it's only supported on some versions. The issue I have with this implementation is it's not very well integrated and inconsistent with other settings. Changing the resource pack dir will still have the launcher show the old one & you will need to keep game and launcher proxy settings in sync.

**Comment by Trial97** [comment]
Closing this due to issues mentioned by TheKodeToad

**Comment by aparatext** [comment]
> We already do have proxy settings

The proxy settings only apply to the launcher, not the Minecraft instance. The label says Minecraft doesn't accept them, but according to [Minecraft ignores java proxy parameters](https://bugs.mojang.com/browse/MC/issues/MC-38872), there are `--proxyHost`, `--proxyPort`, `--proxyUser`, and `--proxyPass` arguments.

I believe either the current global proxy settings should attempt to set these or a proxy tab should be added to instance settings, either grayed out or fallen back to Java settings for versions before these args were introduced.

**Pull request closed without merging**
