### PR TITLE
Fix: update datapack and resourcepack versions

### PR DESCRIPTION
**Pull request by DioEgizio**

### CODE REVIEW

**Review by Trial97 — APPROVED** [review]

**Comment by Trial97** [comment]
Yo may need to run clang format: https://github.com/PrismLauncher/PrismLauncher/pull/2534/checks?check_run_id=26354511964

**Review by Ryex — APPROVED** [review]
what the heck is Mojang doing with these version numbers?

**Comment by Trial97** [comment]
@DioEgizio  should we add the rest of them mentioned here: https://minecraft.wiki/w/Pack_format ?
image

**Comment by DioEgizio** [comment]
I didn't see those




pain




honestly we should find another solution at some point, this is way too much lol 


On the other hand I don't think many people make rpacks only for snapshots so it's not a big deal

**Comment by Trial97** [comment]
> honestly we should find another solution at some point, this is way too much lol

Do they provide them in meta?



> On the other hand I don't think many people make rpacks only for snapshots so it's not a big deal

Yeah but would still be nice to have all the mappings until we get something better in place

**Comment by Ryex** [comment]
> > honestly we should find another solution at some point, this is way too much lol
> 
> Do they provide them in meta?
> 
they do not. that wiki is the only place I know to document the version numbers because they seem to be found via reverse engineering.

I still want to know why they were bumping the version number every snapshot...

**Comment by Trial97** [comment]
They are improving a lot of stuff in data packs

**Comment by TayouVR** [comment]
at least between 1.20 and 1.21 there were tons of changes to the formats, so makes sense that they would've gone through a lot of versions.
not like they're gonna run out of them anytime soon :P

**Pull request merged**
