### PR TITLE
Display all system themes in widget theme selector

### PR DESCRIPTION
**Pull request by TayouVR**
Signed-off-by: Tayou <git@tayou.org>

### CODE REVIEW

**Review by Trial97 — APPROVED** [review]
On linux works the same as 8.4

**Comment by TayouVR** [comment]
it should show all installed themes in addition to "System", so e.g. on my linux installs it would show "Breeze", "Lightly" and anything else I have installed.
I will definitely have a look at this myself on linux when I get some time.

**Comment by Trial97** [comment]
Oh yeah, they are added: I missed them when I first tested.

**Review by DioEgizio — APPROVED** [review]
maybe we should consider using Fusion by default on windows too?

**Pull request merged**
