### PR TITLE
Made settings editable when instance is running

### LINKED ISSUE #247: Keep "Settings" available while the instance is running
### Role

I use the launcher.

### Suggestion

I want the settings tab to not be hidden while the instance is running, as those settings only apply on startup and have no effect on runtime.

### Benefit

There's a period of time after the game closes while the instance is still considered running; this suggestion being implemented would allow one to get to adjusting their startup options a second or two earlier (trust, it's way more annoying than you think to wait those few seconds). Also adds consistency to the UI.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### PR DESCRIPTION
**Pull request by Trial97**
fixes #247

### CODE REVIEW

**Comment by TheKodeToad** [comment]
i wish this was done in the other pr tbh

**Comment by Trial97** [comment]
Sure thing, moved the change here: https://github.com/PrismLauncher/PrismLauncher/pull/1241

**Comment by TheKodeToad** [comment]
Oh, I wasn't very clear. I meant #1067, and i meant it in the sense of praising this one! :upside_down_face: 

oh well. I guess these are both similar changes so that does make sense!

**Comment by Trial97** [comment]
If needed I can reopen this and remove the changes from the other one. Just say it and it's done.

**Pull request closed without merging**
