### PR TITLE
Change C old style cast to C++ cast

### PR DESCRIPTION
**Pull request by bensuperpc**
Change C old style cast to C++ cast

Signed-off-by: Bensuperpc <bensuperpc@gmail.com>

### CODE REVIEW

**Comment by flowln** [comment]
why is [`2639e39`](https://github.com/PrismLauncher/PrismLauncher/pull/228/commits/2639e39b288927747540748b20144e88292368e4) here :thinking:

**Comment by Scrumplex** [comment]
Yep this seems wrong :eyes:

**Comment by bensuperpc** [comment]
Should I do something ? ^^

**Comment by Scrumplex** [comment]
```
git reset --hard 56ae4e5b6ad984d4c9569cb024d807bd695555a6
git push --force
```

This should fix it

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Review by flowln — APPROVED** [review]

**Pull request merged**
