### PR TITLE
new cat

### PR DESCRIPTION
**Pull request by r58Playz**
Replace background cat with prismcat(made by me).
Still need to change the other 2.

PS: done online

### CODE REVIEW

**Comment by r58Playz** [comment]
Added all of the variants.

**Review by AshtakaOOf — CHANGES_REQUESTED** [review]
cat
Use this instead (made by me)

**Review by Su386yt — APPROVED** [review]

**Comment by triphora** [comment]
We should use Rory instead.
https://rory.cat
@Chew Please give your approval to use Rory in Prism Launcher

**Comment by AshtakaOOf** [comment]
> We should use Rory instead. https://rory.cat @Chew Please give your approval to use Rory in Prism Launcher

He isn't a drawing :despair:

**Comment by Chew** [comment]
This launcher is Rory approved. image

**Comment by triphora** [comment]
> He isn't a drawing :despair:

@AshtakaOOf SHE is not a drawing, and I don't think it makes too much of a difference

**Comment by AshtakaOOf** [comment]
> @AshtakaOOf SHE is not a drawing, and I don't think it makes too much of a difference

¯\_(ツ)_/¯

**Comment by cfazilleau** [comment]
As rory.cat even has a REST API, let's push it even further and get a random image from this API every time

**Comment by jn64** [comment]
For special occasions

out min

```sh
#!/bin/bash

wget -q https://user-images.githubusercontent.com/66513643/196572431-827ef3bb-f08a-4783-8003-3450917af565.png -O 0.png

declare n=$(( 300 - (100 / 7 * 2 ) ))
for i in {0..5}; do
	convert "$i.png" -modulate 100,100,$n "$(( ++i )).png"
done

convert -delay 10 -loop 0 {0..6}.png out.gif
gifsicle -i -k 256 -O3 out.gif > out.min.gif
```

**Review by aprilthepink — APPROVED** [review]
cat is good. but we should add more than one cat. maybe a fox too

**Review by cfazilleau — APPROVED** [review]

**Comment by leumasme** [comment]
I've always wondered why the cat looks so _bad_. Looks as if it had been upscaled and background removed automatically. The line width and shape is all over the place.
Is it maybe time to redraw the cat, or is there a special history behind this image?

**Review by luximus-hunter — APPROVED** [review]

**Comment by jschenke488** [comment]
> > He isn't a drawing :despair:
> 
> @AshtakaOOf SHE is not a drawing, and I don't think it makes too much of a difference

Get someone to draw Rory :)

**Review by Su386yt — APPROVED** [review]

**Comment by forkiesassds** [comment]
> ... or is there a special history behind this image?

IIRC it was an inside joke from one of the MMC developers how the original image was on packaging for an ethernet cable, so they took a photo, traced it and colored it and thus background cat was born.

**Comment by Scrumplex** [comment]
I do not feel comfortable replacing the cat. We might look into configurable backgrounds, though. We could offer some preset ones and allow users to provide their own.

**Comment by AshtakaOOf** [comment]
> Get someone to draw Rory :)

@Chew what do you think of this?
image
image

**Comment by Chew** [comment]
They're beautiful 😍 @AshtakaOOf

**Comment by AshtakaOOf** [comment]
https://rory.cat/id/11 Fanart

**Comment by Heath123** [comment]
Can there be multiple cats with a way to cycle between them?

**Comment by phit** [comment]
> Is it maybe time to redraw the cat, or is there a special history behind this image?

since the base cat was already explained, yes it was on a CAT cable box. I drew the christmas hat at some point in Paint because I thought it would be nice to have seasonal variants.

**Comment by txtsd** [comment]
The Prism icon is not consistent across the newly added cats. And there are strange jagged borders between the colors.
Not saying we'll merge this, but nitpicking just in case anyways.

**Comment by AshtakaOOf** [comment]
Should I do a PR with my Rory drawing? To replace Polycat?

**Review by Annabxlla — APPROVED** [review]
I approve of this but maybe also the option to have the original cat for some people who like the original better / some way to hold onto the past.

**Comment by AshtakaOOf** [comment]
#372

**Comment by Scrumplex** [comment]
Please integrate this with the system introduced by #372

**Comment by r58Playz** [comment]
#372

**Pull request closed without merging**
