### PR TITLE
feat: add flatpak builds to the ci for testing

### LINKED ISSUE #62: Flatpak artifacts for testing
### Role

I contribute to software (I don't play Minecraft but I can help here and there)

### Suggestion

Create Flatpak artifacts for testing commits and MRs

### Benefit

Testing PrismMC on Linux will be easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

We can utilize [flatpak-github-actions](https://github.com/flatpak/flatpak-github-actions) to build Flatpak artifacts. Once succeeded, we can download the artifact, install the flatpak with `flatpak install file.flatpak`, run and test the commit it was built against. This could make testing a lot easier for QA testers.

I can submit an MR if this proposal gets accepted.

### PR DESCRIPTION
**Pull request by DioEgizio**
closes #62

### CODE REVIEW

**Comment by Scrumplex** [comment]
I don't really like that we would be having duplicate code here and two places that would require updates

**Comment by DioEgizio** [comment]
I mean this is only on debug builds (yes I noticed it's building on release too, I have to fix later)
I don't think we can reuse the same yml everywhere

**Comment by guihkx** [comment]
I think there's an alternative to maintaining two Flatpak manifests (it's a bit hacky, though):

1. Clone [org.prismlauncher.PrismLauncher](https://github.com/flathub/org.prismlauncher.PrismLauncher)
2. Use [`yq`](https://github.com/marketplace/actions/yq-portable-yaml-processor) to update the required bits of the manifest, something like:

```yml
- name: Checkout Flatpak manifest
  uses: actions/checkout@v3
  with:
    repository: flathub/org.prismlauncher.PrismLauncher

- name: Install yq
  uses: mikefarah/yq@v4.30.4

- name: Update Flatpak manifest to build using this repo
  run: yq -i '(.modules[] | select(.sources[].url == "*/PrismLauncher/*")).sources = {"type": "dir", "path": ".."}' org.prismlauncher.PrismLauncher.yml

- name: Show modified manifest
  run: cat org.prismlauncher.PrismLauncher.yml

  # build flatpak...
```

**Comment by DioEgizio** [comment]
Very hacky and there can be breaking changes related to the build system between releases

**Comment by guihkx** [comment]
Yeah, it can get tricky... Perhaps another alternative is maintaining a single Flatpak manifest in-tree, like OBS Studio and Firefox both do for their apps:

- https://github.com/obsproject/obs-studio/blob/master/CI/flatpak/com.obsproject.Studio.json
- https://hg.mozilla.org/releases/mozilla-release/file/tip/taskcluster/docker/firefox-flatpak/runme.sh

I'm not sure if this requires a special process within Flathub, though.

**Comment by DioEgizio** [comment]
i think it's better to keep duplicated for now

**Review by flowln — APPROVED** [review]

**Comment by Scrumplex** [comment]
Who is going to keep this manifest up-to-date though?

**Comment by DioEgizio** [comment]
I guess we can update when it's needed, I don't think it'll need frequent updating anyways, and it can be useful for the actual stable flatpak to be able to have the manifest updated and see if there are any regressions

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
