### PR TITLE
Fix hardcoded icon

### PR DESCRIPTION
**Pull request by fn2006**
Replaces hardcoded SVG path in `launcher/Application.cpp` with a BuildConfig variable.

Signed-off-by: fn2006 <usernamefn2006alreadyused@protonmail.com>

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Comment by txtsd** [comment]
What about this?
https://github.com/PrismLauncher/PrismLauncher/blob/1c0139c5f41592ba2b60465496f54097bf43e02b/program_info/CMakeLists.txt#L28

If it's unneeded, please remove it.

EDIT: Actually, it's used later on. Maybe you could make it use the variable you created.

**Comment by fn2006** [comment]
Okay, `Launcher_SVG` now uses `Launcher_SVGFileName`
I also made `Launcher_Desktop` use `Launcher_DesktopFileName`, is that ok?

**Review by Scrumplex — APPROVED** [review]

**Review by txtsd — APPROVED** [review]
This is good. Thank you!

**Pull request merged**
