### PR TITLE
chore: bump to 7.1

### PR DESCRIPTION
**Pull request by DioEgizio**

### CODE REVIEW

**Comment by Scrumplex** [comment]
this belongs to `release-7.x`

**Comment by DioEgizio** [comment]
> this belongs to `release-7.x`

I mean, since there's no new feature in develop yet can't we just merge this to develop and then ff release-7.x?

**Comment by Scrumplex** [comment]
Just change the merge base to release-7.x and merge this as the very last PR before releasing. That's how we did it in the past.

We technically need an 8.0 bump on develop

**Review by Scrumplex — APPROVED** [review]

**Review by TheKodeToad — APPROVED** [review]
lol

**Pull request merged**
