### PR TITLE
Print hashes of release artifacts

### PR DESCRIPTION
**Pull request by Scrumplex**
This way people can verify, that our release builds are actually what they are.

### CODE REVIEW

**Comment by Scrumplex** [comment]
Haven't tested yet :eyes:

**Comment by txtsd** [comment]
This only prints it in the build logs, yes?

**Comment by txtsd** [comment]
We could, instead, PGP sign our releases like KeePassXC does.
https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.3

**Comment by Scrumplex** [comment]
https://github.com/Scrumplex/PrismLauncher/actions/runs/3345836282/jobs/5542549182#step:5:279
doesn't work :|

**Comment by DioEgizio** [comment]
Perhaps we could use something like https://github.com/marketplace/actions/generate-release-hashes

**Comment by txtsd** [comment]
> .AppImage: Is a directory

WAT

**Comment by Scrumplex** [comment]
Seems to work now.

**Comment by DioEgizio** [comment]
Sure but it's kinda useless if it's just in the GitHub action log :/

**Review by txtsd — APPROVED** [review]
Okay from a technical standpoint. Questionable from a regular user standpoint.

**Comment by Scrumplex** [comment]
> Sure but it's kinda useless if it's just in the GitHub action log :/

The kind of people who will want to verify that our binaries were not modified will be fine checking the actions logs

**Comment by DioEgizio** [comment]
> > Sure but it's kinda useless if it's just in the GitHub action log :/
> 
> The kind of people who will want to verify that our binaries were not modified will be fine checking the actions logs

Not really, also the action log can't be viewed by people not logged and it deletes after a while. This is not a good solution

**Comment by Scrumplex** [comment]
Hmm. Logs getting deleted is a problem. But then there is no way to verify that no one has tampered with the binaries

**Comment by Ryex** [comment]
echo them to a .txt, upload the .txt as an artifact?

**Comment by Scrumplex** [comment]
> echo them to a .txt, upload the .txt as an artifact?

An attacker could just replace that file after they have tampered with the binaries

**Comment by Ryex** [comment]
> > echo them to a .txt, upload the .txt as an artifact?
> 
> An attacker could just replace that file after they have tampered with the binaries

place a pgp key in a secrete accessible to the action and sign the .txt?

so long as the public key needed to verify the signature is available from a trusted source I think that should be solid.
if an attacker gains enough access to get that secret there are bigger problems yeah?

**Comment by Scrumplex** [comment]
We don't have PGP keys yet. But cryptographic signatures might be the best idea, yeah

**Pull request closed without merging**
