### PR TITLE
Better handling for non-latin stuff in the mod updater on WIndows

### LINKED ISSUE #226: Indexing mods hangs when paths have Chinese, cyrillic or with diacritics characters
### Operating System

Windows

### Version of Prism Launcher

5.0

### Version of Qt

6.4.0

### Description of bug

When indexing mod metadata and there are mods with Chinese characters, the launcher just hangs.

### Steps to reproduce

- Add chinese characters to mod filenames.
- Try to index

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Fixes #226

my sanity has vanished, qt can open the files just fine, and tomlplusplus says it can too, BUT IT CAN'T???

Update: It was a both a toml++ issue (fixed upstream), and an issue with out handling of `std::string` that needs to be `std::wstring` on Windows for non-latin characters.

### CODE REVIEW

**Comment by nightsnowlinouo** [comment]
The instance name is Chinese characters and Mandarin Phonetic Symbols. The Updater Mod will no longer be unresponsive and can be executed normally.

**Comment by snowlinouo** [comment]
The instance names are Chinese characters and Mandarin Phonetic Symbols, and the Updater Mod provider options are:
Modrinth works fine
CurseForge did not respond

**Review by Scrumplex — APPROVED** [review]
LGTM

**Comment by DioEgizio** [comment]
Now that the bug is fixed in toml++, can't we just update the submodule?

**Comment by flowln** [comment]
yes, i'm waiting for windows to compile it so i can test before committing :+1:

**Comment by txtsd** [comment]
Apart from the last commit, which we won't need if toml++ works correctly now, the rest of the commits are an improvement anyway.

**Comment by snowlinouo** [comment]
Download the updated toml++ test version, Updater Mod provider selects CurseForge launcher, no response

Instead Modrinth will not cause the launcher not to respond

https://user-images.githubusercontent.com/113241163/200313104-c89b2568-b657-4b80-98ee-f958a2297100.mp4

https://user-images.githubusercontent.com/113241163/200312769-728dc345-67c1-43b4-8035-13a5d598c748.mp4

**Comment by flowln** [comment]
Last commit should've fixed the CF issue (i think)!

**Comment by snowlinouo** [comment]
> Last commit should've fixed the CF issue (i think)!

CurseForge can be executed normally, the same as Modrinth will not be unresponsive！

**Review by txtsd — APPROVED** [review]
LGTM! You could fix the CodeQL alerts before merge though. It does not like updating the for loop counters from within the loop in `StringUtils.cpp`.

**Review by txtsd — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
