### PR TITLE
update login flow

### PR DESCRIPTION
**Pull request by Trial97**
Parent PR: #2402
invalidates https://github.com/PrismLauncher/PrismLauncher/pull/2477
but needs to add `prismlauncher://oauth` as the login URL inside Microsoft Azure client stuff
Also where should I point the help button?

**This design was copied from:** [TheKodeToad](https://github.com/TheKodeToad/PrismLauncher/commit/0452cb6b4fc2199d54e7a4d689fb97ffb171d79c)

preview:
image

image

### CODE REVIEW

**Comment by DioEgizio** [comment]
image
this doesn't seem to be clickable, also I assume there's no prismlauncher://oauth stuff yet in azure config because it doesn't seem to work. But anyways the UI is amazing for sure

**Comment by Trial97** [comment]
It is and it works (maybe you need the mime type set correctly; that should come with the installer) but the link I will update it.

**Comment by DioEgizio** [comment]
> It is and it works (maybe you need the mime type set correctly; that should come with the installer)

That won't work with AppImage, portable and a few edge cases. Maybe we need to use another solution

**Comment by Trial97** [comment]
either this:`xdg-mime default org.prismlauncher.PrismLauncher.desktop x-scheme-handler/prismlauncher` 
or use the second one.
I can even detect if is portable/appimage and remove that login

**Comment by DioEgizio** [comment]
> I can even detect if is portable/appimage and remove that login

that's probably the best solution, it's terrible UX to have something that can't work, still worried about some edge cases when the mime handler isn't registred

and that command doesn't work for me:

/usr/bin/xdg-mime: line 885: qtpaths: command not found

**Comment by Trial97** [comment]
Install qt5-tools

**Comment by DioEgizio** [comment]
then (as I expected) it tried to open the system PrismLauncher and not the AppImage one

**Comment by Trial97** [comment]
For me it worked to specify the executable in that menu

**Comment by Trial97** [comment]
we can have a hybrid approach were we serve the redirect server for appimage and portable and for the rest use the mime-type approach

**Comment by lordofpipes** [comment]
**Edit:** May just be able to randomize the port number by allowing Qt to find an available port, @Trial97 discovered that Azure does not care about the localhost port number.

---

If localhost oauth flow is used as a fallback for appimage/portable/user-deleted-shortcut, to make a port overlap as unlikely as possible I would suggest the following process for choosing a port number. This Node.js script will resolve to two ports within 24 hours (2024-06-15 12:52), using the result of a randomness beacon and a list of known ports to avoid. It also tries to find a directly adjacent fallback port that is available, in case there ends up being code to attempt another port binding when the first fails.

(I am mildly obsessed with the idea of nothing-up-my-sleeve numbers and randomness beacons, I use this every time I need a random unused port number and want to be able to justify its randomness)
```javascript
let epoch = 4097950 + 2880; // 24 hours

async function getAvailablePorts() {
    let responseTcp = await fetch("https://raw.githubusercontent.com/maraisr/ports-list/9768e934b1a7e64b6ea68b6004c4041a8716c3c0/tcp.csv");
    let textTcp = await responseTcp.text();
    let portsTcp = textTcp.trim().split("\n").slice(1).map(line => parseInt(line.split(",")[1]));

    let responseUdp = await fetch("https://raw.githubusercontent.com/maraisr/ports-list/9768e934b1a7e64b6ea68b6004c4041a8716c3c0/udp.csv");
    let textUdp = await responseUdp.text();
    let portsUdp = textUdp.trim().split("\n").slice(1).map(line => parseInt(line.split(",")[1]));

    let available = [];
    for (let i = 2000; i < 65536; i++) {
        if (!portsUdp.includes(i) && !portsTcp.includes(i))
            available.push(i);
    }
    return available;
}

async function main() {
    let availablePorts = await getAvailablePorts();

    let response = await fetch(`https://api.drand.sh/8990e7a9aaed2ffed73dbd7092123d6f289930540d7651336225dc172e51b2ce/public/${epoch}`);
    if (response.status === 404) {
        throw new Error("Entropy from the randomness beacon is not yet available.");
    }
    let json = await response.json();
    let data = Buffer.from(json.randomness, "hex");
    for (let i = 0; i < 16; i++) {
        let num = data.slice(i*2).readUint16BE();
        if (availablePorts.includes(num) && availablePorts.includes(num + 1)) {
            console.log(`Used epoch ${epoch}`);
            console.log(`Main port: ${num}`);
            console.log(`Fallback port: ${num + 1}`);
            return;
        }
    }
    console.log("Extremely rare circumstances have occurred and a port number could not be chosen. Schedule a new epoch to choose from.");
}
main();
```
```bash
node ./get-random-port.js
```

(This won't be used, but if you're curious, the result of the randomness process was: 39633 and 39634)

**Comment by Trial97** [comment]
The port is part of the url we register to azure so it can't be changed

**Comment by lordofpipes** [comment]
> The port is part of the url we register to azure so it can't be changed

That's the point &mdash; set it once and be done with it. I don't think 1337 is rare enough, I've seen a lot of dev tools use it.

Unless you mean only one URL can be set per flow, meaning a fallback is not possible. And it seems that having a fallback port with `QOAuth` is tricky anyways.

**Review by Ryex — APPROVED** [review]
I can't find any issues. OAuthflows look good. (I've look at a lot of them :P)
Love the url scheme usage.
UI is beautifully laid out

The one change I *might* suggest is to trigger a loading of the "successfully logged in" page when using the prismlauncher url sheme so that there is some browser feedback too.

**Comment by Trial97** [comment]
> The one change I _might_ suggest is to trigger a loading of the "successfully logged in" page when using the prismlauncher url sheme so that there is some browser feedback too.

I don't think I can achieve that without the HTTP server, so that would defeat the purpose of having the custom URL scheme. And from what I know there is no way to control that tab from qt. Do you have any suggestions on how to achieve that?

**Comment by Ryex** [comment]
> > The one change I _might_ suggest is to trigger a loading of the "successfully logged in" page when using the prismlauncher url sheme so that there is some browser feedback too.
> 
> I don't think I can achieve that without the HTTP server, so that would defeat the purpose of having the custom URL scheme. And from what I know there is no way to control that tab from qt. Do you have any suggestions on how to achieve that?

I was thinking it would just open a new page, the idea being that even if the browser was still in focus it would just switch tabs.

**Comment by Trial97** [comment]
Wouldn't that be annoying for the user?
When you open prism try to login then that opens the browser you login into the browser that asks you to open with prism then prism opens another tab to tell that the login was successful (they already see that in the launcher once the dialog finishes).

**Comment by Ryex** [comment]
in my testing on windows, it asked to open prism (and that worked) but prism did not then take focus. the browser kept focus.

it's not an important change so if on balance it work best without it then that's fine.

**Review by TayouVR — APPROVED** [review]

**Comment by TayouVR** [comment]
i feel like the two options in the UI should take up the same space and the "or" needs to be more obvious.
Probably by having more whitespace. Wouldn't having the options side by side look better, the same as what discord login has?

**Pull request merged**
