### PR TITLE
Migrate to toml

### PR DESCRIPTION
**Pull request by Trial97**
Part of https://github.com/PrismLauncher/PrismLauncher/issues/1182

### CODE REVIEW

**Comment by TheKodeToad** [comment]
IMO we should rework everything else if we are doing this. Everything is in the same table and has inconsistent Pascal and camelCase, uses unix timestamps, and both instance properties and state is stored together.

**Comment by Trial97** [comment]
That is a good point I do plan to refactor the instance settings stuff but I want to start small: split my work into multiple PRs to make it easy to merge(review)

**Comment by TheKodeToad** [comment]
Could we merge it to a separate branch?

**Comment by Trial97** [comment]
Yeah sure, feel free to change the branch as needed. I partially left this allone as I wanted to work on a few other stuff related to instance creation(still no idea on how to improve it).
Do you want to work on this stuff?

**Comment by TheKodeToad** [comment]
My reason for doing it all at once is that we will break a lot. If we don't write migration for every single PR people may end up with instances that only work on certain development commits, and the more migrations we need to handle the more code we need to maintain.

Also, I think we need to introduce a new form of migrations. Instead of it being automatic I think the user should be prompted as they will not be able to open the instance on older verisons.

Maybe older instances should be loaded in an immutable state where only the name and icon is loaded and have a single action on the toolbar to update them. Upon pressing it a dialog box would appear saying "Would you like to update this instance? It will stop working on older versions of Prism Launcher." with a checkbox to keep the old config as instance.cfg.old. To preserve sanity the user should be prompted with a dialog to update all instances at once (or only checked instances?) when they start the new version.

**Comment by TheKodeToad** [comment]
Also, we should probably keep compatibility for exporting to MultiMC which this PR breaks. We might have already broken it a little bit (since we use a more standard INI parser/dumper) but most people are not aware as we did not give warning and people can usually get away with importing Prism instances into MultiMC in the current version. Arguably we never officially supported it but it has always worked and is something people would expect from a MultiMC fork.

**Comment by Trial97** [comment]
I think this PR is not a good idea:
- if we want multilevel configs, the change signals can't be trivially accessed.
- the converting struct to and from toml is horrible (similar to JSON at best)
- this change breaks too many stuff that we want to keep
- the migration will be a hassle 
- the code will not be more readable than now

This was intended for tracking resources inside the instance configs and also maybe the Java profiles.
But it would be easier to have a separate file for this and not touch the configs.

Closing this for now.

**Pull request closed without merging**
