### PR TITLE
Fix LTO compilation with `-Werror=odr` flag

### PR DESCRIPTION
**Pull request by flowln**
It also makes this more inline to how smart pointers are handled in other places (like for `Task::Ptr`)

### CODE REVIEW

**Comment by txtsd** [comment]
Where do I stick the Werror flag to test compilation?

**Comment by flowln** [comment]
> Where do I stick the WError flag to test compilation?

On the CMake configuration call, you can set other flags with something like
`-DCMAKE_CXX_FLAGS="-Werror=odr $CMAKE_CXX_FLAGS"`

**Comment by txtsd** [comment]
> > Where do I stick the WError flag to test compilation?
> 
> On the CMake configuration call, you can set other flags with something like `-DCMAKE_CXX_FLAGS="-Werror=odr $CMAKE_CXX_FLAGS"`

I did it but there were no errors or warnings on `develop`, which I thought this PR would then fix.

**Comment by flowln** [comment]
> I did it but there were no errors or warnings on `develop`, which I thought this PR would then fix.

:thinking: i got errors with it, and it's not just me, I originally got to know of this error due to Gentoo's CI (https://bugs.gentoo.org/878877)

i'll try to compile with only the `-Werror=odr` flag then. My current setup, for reference, is:
`-DCMAKE_CXX_FLAGS="-g -pedantic -O2 -pipe -frecord-gcc-switches -fstrict-aliasing -DQT_NO_DEPRECATED_WARNINGS=Y -DQT_DISABLE_DEPRECATED_BEFORE=0x050C00 -Werror=lto-type-mismatch -Werror=odr -Werror=strict-aliasing -fsanitize=address $(echo $CMAKE_CXX_FLAGS | sed -e "s/-Wall//g")"`

**Comment by txtsd** [comment]
Could be correlated to another flag in there.

This was my complete cmake config for reference:
`cmake -S . -B build -DLauncher_BUILD_PLATFORM=Linux -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -DENABLE_LTO=ON -DLauncher_QT_VERSION_MAJOR=6 -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-Werror=odr $CMAKE_CXX_FLAGS" -G Ninja`

**Comment by flowln** [comment]
It fails on develop on my computer even with only `-Werror=odr`:

```bash
[383/383] Linking CXX executable prismlauncher
FAILED: prismlauncher 
: && /usr/bin/g++ -Wall -pedantic -fstack-protector-strong --param=ssp-buffer-size=4 -Werror=odr -DQT_NO_DEPRECATED_WARNINGS=Y -DQT_DISABLE_DEPRECATED_BEFORE=0x050C00 -O2 -D_FORTIFY_SOURCE=2 -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects  launcher/CMakeFiles/PrismLauncher.dir/PrismLauncher_autogen/mocs_compilation.cpp.o launcher/CMakeFiles/PrismLauncher.dir/main.cpp.o -o prismlauncher  -Wl,-rpath,::::::::  launcher/libLauncher_logic.a  libraries/systeminfo/libsysteminfo.a  libraries/murmur2/libLauncher_murmur2.a  libraries/libnbtplusplus/libnbt++.a  -lz  buildconfig/libBuildConfig.a  libraries/katabasis/libKatabasis.a  /usr/lib64/libQt6Widgets.so.6.3.1  libraries/gamemode/libgamemode.a  -ldl  /usr/lib64/libQt6Xml.so.6.3.1  /usr/lib64/libQt6Concurrent.so.6.3.1  /usr/lib64/libquazip1-qt6.so.1.3  /usr/lib64/libz.so  libraries/hoedown/libhoedown.a  libraries/LocalPeer/libLocalPeer.a  /usr/lib64/libQt6Network.so.6.3.1  /usr/lib64/libQt6Core5Compat.so.6.3.1  libraries/rainbow/libLauncher_rainbow.a  /usr/lib64/libQt6Gui.so.6.3.1  /usr/lib64/libQt6Core.so.6.3.1  /usr/lib64/libGLX.so  /usr/lib64/libOpenGL.so && :
/home/low/Documents/repos/Prism/build/launcher/Launcher_logic_autogen/F26Q4VW2FO/../../../../launcher/meta/VersionList.h:28:7: error: type ‘struct VersionList’ violates the C++ One Definition Rule [-Werror=odr]
   28 | class VersionList : public BaseVersionList, public BaseEntity
      |       ^
/home/low/Documents/repos/Prism/launcher/meta/VersionList.h:28:7: note: a different type is defined in another translation unit
   28 | class VersionList : public BaseVersionList, public BaseEntity
      |       ^
/home/low/Documents/repos/Prism/build/launcher/Launcher_logic_autogen/F26Q4VW2FO/../../../../launcher/meta/VersionList.h:92:25: note: the first difference of corresponding definitions is field ‘m_versions’
   92 |     QVector<VersionPtr> m_versions;
      |                         ^
/home/low/Documents/repos/Prism/launcher/meta/VersionList.h:92:25: note: a field of same name but different type is defined in another translation unit
   92 |     QVector<VersionPtr> m_versions;
      |                         ^
/home/low/Documents/repos/Prism/build/launcher/Launcher_logic_autogen/F26Q4VW2FO/../../../../launcher/meta/VersionList.h:28:7: note: type name ‘QList<std::shared_ptr<Meta::Version> >’ should match type name ‘QList<std::shared_ptr<Version> >’
   28 | class VersionList : public BaseVersionList, public BaseEntity
      |       ^
/home/low/Documents/repos/Prism/launcher/meta/VersionList.h:69:10: warning: type of ‘hasVersion’ does not match original declaration [-Wlto-type-mismatch]
   69 |     bool hasVersion(QString version) const;
      |          ^
/home/low/Documents/repos/Prism/launcher/meta/VersionList.cpp:143:6: note: ‘hasVersion’ was previously declared here
  143 | bool VersionList::hasVersion(QString version) const
      |      ^
/home/low/Documents/repos/Prism/launcher/meta/VersionList.cpp:143:6: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
lto1: some warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/g++ returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by flowln** [comment]
> Could be correlated to another flag in there.
> 
> This was my complete cmake config for reference: `cmake -S . -B build -DLauncher_BUILD_PLATFORM=Linux -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -DENABLE_LTO=ON -DLauncher_QT_VERSION_MAJOR=6 -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-Werror=odr $CMAKE_CXX_FLAGS" -G Ninja`

oh, try using `-DCMAKE_BUILD_TYPE=Release` :p

**Comment by txtsd** [comment]
> > Could be correlated to another flag in there.
> > This was my complete cmake config for reference: `cmake -S . -B build -DLauncher_BUILD_PLATFORM=Linux -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -DENABLE_LTO=ON -DLauncher_QT_VERSION_MAJOR=6 -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-Werror=odr $CMAKE_CXX_FLAGS" -G Ninja`
> 
> oh, try using `-DCMAKE_BUILD_TYPE=Release` :p

Okay, this threw the error correctly.

**Review by txtsd — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]
LGTM

**Pull request merged**
