### PR TITLE
Only allow getting blocked mods from Modrinth when it's safe to do so

### LINKED ISSUE #321: CurseForge import does not catch all mods that are disallowed from being auto-downloaded, leading to broken/incomplete modpacks
### Operating System

Windows 10

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

When downloading a modpack from curseforge, some mods do not allow a client to auto download them. Prism catches this and opens the links for you so that you can download and copy-paste them yourself, however I have noticed that with Medieval MC, the latest version will _consistently_ miss some mods (notably the deeperanddarker mod), and will _not_ mention it. Although it seems to be installed, it does not function in any way unless manually reinstalled. This issue does not occur with any other client that allows curse importing, making me believe it is unique to Prism.

### Steps to reproduce

Create Instance
Select CurseForge
Select Medieval MC 1.19.2, v9
Attempt to run mod, check Modlist in-game for Deeper and Darker
It does not load, nor will it exist in game

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Fixes #321

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]

**Comment by DioEgizio** [comment]
this just breaks downloading mods like that for mods with more than one modloader, and probably almost every fabric mod since they tag for quilt too

**Comment by flowln** [comment]
> this breaks mods for more than one modloader, and probably almost every fabric mod since they tag for quilt too

it just doesn't do the workaround in the CF modpack mod resolving, the Modrinth stuff isn't touched. I don't think there is any other way of doing this

**Comment by DioEgizio** [comment]
Yeah I meant blocked mods that tag for more than one mod loader on modrinth

**Comment by flowln** [comment]
> Yeah I meant blocked mods that tag for more than one mod loader on modrinth

It only looks at the version, not the mod itself. If a mod has various versions tagged, each with a different mod loader (as it should normally), it will still be fine

**Comment by DioEgizio** [comment]
> > Yeah I meant blocked mods that tag for more than one mod loader on modrinth
> 
> It only looks at the version, not the mod itself. If a mod has various versions tagged, each with a different mod loader (as it should normally), it will still be fine

I'm trying to say that many fabric mods make their version quilt too, and many mods work with multiple modloaders (especially with stuff like forgix) so

**Comment by flowln** [comment]
> I'm trying to say that many fabric mods make their version quilt too, and many mods work with multiple modloaders (especially with stuff like forgix) so

ok, but I don't think there's anything we can do about that, we can't differentiate between a situation like the one you're describing, and one that creates the problem in #321 i think .-.

**Comment by triphora** [comment]
This shouldn't be necessary, multiple files for multiple mod loaders should never happen on Modrinth. If you do come across any like that it should be reported.

**Comment by flowln** [comment]
> This shouldn't be necessary, multiple files for multiple mod loaders should never happen on Modrinth. If you do come across any like that it should be reported.

If this will be enforced by Modrinth, then I'm fine closing it. However, it seems to me like the same sort of issue as #319, with the difference that non-conforming versions won't segfault, but will rather silently miss out a mod. Most users, still, will probably be less attentive to their mod list after downloading a pack than #321's OP, and so this problem would go unnoticed, possibly giving very hard-to-debug issues for said users.

So, as with #319, in normal circumstances it shouldn't be necessary, but given it has happened before, it might happen again in the future, and we should handle it better than straight-up creating a wrong modpack.

**Review by timoreo22 — APPROVED** [review]

**Pull request merged**
