### PR TITLE
Add commit hash to `--version`

### PR DESCRIPTION
**Pull request by RuiNtD**
Adds the commit hash to `--version` in CLI

### CODE REVIEW

**Review by txtsd — CHANGES_REQUESTED** [review]
Surround those `+`s with spaces please.

**Comment by TheKodeToad** [comment]
You could probably do '\n' instead of "\n". I don't know which is preferred here though.

**Comment by txtsd** [comment]
> You could probably do '\n' instead of "\n". I don't know which is preferred here though.

The double quotes are fine.

**Review by DioEgizio — APPROVED** [review]

**Comment by Scrumplex** [comment]
I wonder if this has an effect on other parts of the program.

**Comment by txtsd** [comment]
@Scrumplex So far nothing explicitly calls [applicationVersion](https://doc.qt.io/qt-6/qcoreapplication.html#applicationVersion-prop)()

[This line](https://github.com/PrismLauncher/PrismLauncher/blob/debc1659e100de1a85d80a8f0ba41623293d0103/launcher/Application.cpp#L250) is the only line that (indirectly) pulls that information. So I don't think it shows up anywhere other than in the `-v/--version` CLI output.

**Review by txtsd — APPROVED** [review]

**Comment by Scrumplex** [comment]
Yeah. I was just wondering if Qt uses the version number somewhere in GUI, though. I wouldn't be surprised if this affected something on say macOS.

**Comment by DioEgizio** [comment]
https://github.com/PrismLauncher/PrismLauncher/blob/debc1659e100de1a85d80a8f0ba41623293d0103/CMakeLists.txt#L286

Probably not

**Review by Scrumplex — APPROVED** [review]
I have searched through the source code of qtbase and I couldn't find anything that I wouldn't expect. LGTM

**Pull request merged**
