### PR TITLE
[Linux] Shorten desktop entry comment field

### LINKED ISSUE #1030: Shorten desktop entry comment field (program description text)
### Role

I have Prism Launcher installed on Linux

### Suggestion

Have a shorter description text in my program launcher

### Benefit

More consistent with other programs and reduces noise when searching for programs

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The comment field should be a short and concise description of the program. It's currently a fairly long sentence - it would be nice if it was shortened to something more concise such as "Custom Minecraft launcher". There seems to be several places where the description is written so they may all require updating.

### PR DESCRIPTION
**Pull request by deadmeu**
Shortens the desktop entry comment field which is used to display the description text of a program in application launchers.

There are several other locations where the existing description text exists which may also need updating:

- https://github.com/PrismLauncher/PrismLauncher/blob/8dc3267925537d58a1e9418863b78e4cc55bd1c1/CMakeLists.txt#L307
- https://github.com/PrismLauncher/PrismLauncher/blob/8dc3267925537d58a1e9418863b78e4cc55bd1c1/flake.nix#L2
- https://github.com/PrismLauncher/PrismLauncher/blob/8dc3267925537d58a1e9418863b78e4cc55bd1c1/program_info/org.prismlauncher.PrismLauncher.metainfo.xml.in#L7

I'm unfamiliar with these platforms and files so let me know if you think they should be updated as well.

Closes https://github.com/PrismLauncher/PrismLauncher/issues/1030

### CODE REVIEW

**Review by flowln — COMMENTED** [review]
looking at [the xdg specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys), seems to me that your version of `Comment` would be better suited for `GenericName`.

For sure, I think `Comment` could make some improvements, for instance basing more off the description at https://prismlauncher.org/, but i'm not convinced your version is the best for that field.

Perhaps something like `Discover, manage and play Minecraft instances` could make-do too.

**Comment by getchoo** [comment]
bumping this since flow's idea was really good. the current description is a little verbose, and could definitely be improved with something like that

**Comment by Scrumplex** [comment]
any activity on this? Or can we close this and hope someone else picks up the work?

**Comment by deadmeu** [comment]
Sorry for the inactivity. I need to have a play with the field to make sure I'm using the right one. I'll need to verify that the Comment field is the right one to change (it might potentially be distro specific).
I'm happy to go with flowin's suggestion so I'll take another look and update the PR sometime this week.

**Comment by Trial97** [comment]
Is this PR dead? 
As I see no activity from  July when the same question was asked.

**Comment by deadmeu** [comment]
I've updated the text - this should be good now.

**Review by Trial97 — APPROVED** [review]

**Review by Ryex — APPROVED** [review]

**Pull request merged**
