### PR TITLE
ensure minimal folder permissions when extracting files

### PR DESCRIPTION
**Pull request by Trial97**
Parent PR: #1409
fixes folder permissions when extracting packs: https://discord.com/channels/1031648380885147709/1031823065937629267/1267586847312183427

### CODE REVIEW

**Review by Ryex — APPROVED** [review]

**Comment by TheKodeToad** [comment]
Wait I might misunderstand this but why would you need execute permissions?

**Comment by Trial97** [comment]
> Wait I might misunderstand this but why would you need execute permissions?

To be able to search inside the directories: 
https://superuser.com/questions/168578/why-must-a-folder-be-executable
https://linux.die.net/man/1/chmod

**Comment by TheKodeToad** [comment]
For files only reading for the current user is in min permissions, why didn't you separate the min and max permissions?

**Comment by Trial97** [comment]
> For files only reading for the current user is in min permissions, why didn't you separate the min and max permissions?

For files, I do not want to change permissions if it has at least read capabilities. But I still do not wish to have full 777 permissions on them(also I hoped that minimizing the cases where I set the file permissions would not trigger antiviruses so often).

For folders, this is irrelevant as you always want to have all the bits set so the folder is accessible. If you have Linux look at folder permissions inside the home or root directory, all have `drwxr-xr-x`.

**Review by TayouVR — APPROVED** [review]

**Review by TheKodeToad — APPROVED** [review]

**Pull request merged**
