### PR TITLE
Replace NDEBUG checks with AUTH_DEBUG for security

### PR DESCRIPTION
**Pull request by TheKodeToad**
This seems like a silly change, but I've seen examples in the past of why it may be needed (I don't want to be too specific). This makes the debugging messages for authentication opt-in with AUTH_DEBUG.

### CODE REVIEW

**Comment by flowln** [comment]
I feel like this being a compile-time flag is somewhat cumbersome (speaking of both the new code and the old code). It seems to me like this should be a runtime setting instead, disabled by default ofc, but not requiring a recompilation to enable.  So, i think something like logging categories would be better suited here.

**Comment by TheKodeToad** [comment]
The reason for implementing it like this is that these messages are only really useful when working on the auth code.

You're already going to have to recompile, and qDebug is already *kind of* a category.

**Comment by flowln** [comment]
> The reason for implementing it like this is that these messages are only really useful when working on the auth code.
> 
> You're already going to have to recompile, and qDebug is already _kind of_ a category.

And I may want to take a look at the net responses and stuff in my non-dev build if MS servers decide to take a vacation or something. And I wouldn't want to recompile them just for that, and when I'm done with it recompile again to remove them.

Yes, you have to recompile it rn, which is the issue i'm pointing at ("speaking of both the new code and the old code" in my comment).

and yes, i'm very aware that qDebug is a category of its own, and that's not what i'm talking about. what i'm talking about is using something like `qCDebug(AUTH_INTERNALS) << ...` instead of removing the debug statement at compile-time, so that you can enable and disable it more easily. I started doing something among those lines in https://github.com/PolyMC/PolyMC/pull/1092 if you want an example of how it'd work.

**Comment by TheKodeToad** [comment]
The log which I saw an access token in is now fortunately deleted. The user who uploaded it said they were using the makedeb package. That's probably how it happened, so I think it's more important that the package is fixed.

Since the changes I've made don't seem to be ideal, I'll close this.

**Pull request closed without merging**
