### PR TITLE
Fully reload the instance list once the folder is changed

### LINKED ISSUE #1584: Instance half changing
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 5.15.10

### Description of bug

The instance setting only shows the instances, but when you try to launch them it tries from the normal instance directory and gives this message:
image
(in case of people searching for the issue: Couldn't load the instance profile.)

### Steps to reproduce

- Install prism launcher
- Change your instance folder to another folder that was in use before
- Launch an instance that isn't in the normal folder

### Suspected cause

The launcher uses the normal instance folder instead of whatever is changed in the settings

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #1584

### CODE REVIEW

**Review by TayouVR — DISMISSED** [review]

**Comment by TheKodeToad** [comment]
All of the instances are removed for me

**Comment by TayouVR** [comment]
it works for me...

**Comment by Trial97** [comment]
> All of the instances are removed for me

I want to try to reproduce this, can you describe the steps?

**Comment by TheKodeToad** [comment]
I mean without this PR it's already removing instances for me

**Comment by Trial97** [comment]
Well obviously that already happens, what doesn't happen is:
- if you have two instance folders and have an instance with the same id
- switch between them in the settings menu( without restarting the launcher)
- trying to start the instance with the same name would result in using the old one if the previous path is still valid, if the instance is no longer there, you will get the same prompt as in the linked issue

My test method for this was:
- open prism
- go to prism root folder
- rename the `instances` folder to `instances2`
- go into prism settings and change the folder to `instances2`
- try to start an instance

**Comment by TayouVR** [comment]
huh, after some more testing.... 
This PR still works perfectly.
But on the develop branch build I have installed it just crashes... without any obvious indicator of what is happening.. might run a debugger on it at some point, though I have like no time at all right now and for the coming days
Didn't test the ID thing specifically, but yeah....

EDIT: reworded it a tiny bit to make it more clear

**Comment by Trial97** [comment]
> EDIT: reworded it a tiny bit to make it more clear

I'm confused now does this PR crashes or not?
I removed your approval because I thought that the crash was related to my PR. Can you approve it again if it is not the case?

**Review by TayouVR — APPROVED** [review]
the develop branch had a crash in my testing, the PR didn't. hence I tried to clarify the comment.
But as stated I need to see what is actually happening.. when i have time (I have job interviews and other appointments every day until friday next week, so I have to see if I can squeeze some debugging in somewhere)

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
