### PR TITLE
[Linux] Add support for Snap packaging

### LINKED ISSUE #596: Snap 6.0 Microsoft login freeze on [Open page and copy code]
### Operating System

Linux

### Version of Prism Launcher

Snap 6.0

### Version of Qt

Qt 5.15.5

### Description of bug

Trying to log in with a Microsoft account and clicking the `Open page and copy code` button freezes the application.

### Steps to reproduce

Click the `Open page and copy code` button.

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by ashuntu**
This PR adds Snap support back to PrismLauncher since it was removed in PR #929. Some minor code changes were added (similar to the existing Flatpak code) that allows Snap to work.

~~`.github/workflows/build.yml` is almost exactly how it was prior to #929, the only change is that I changed it to run on Ubuntu 22.04.~~

~~`snap/snapcraft.yaml` is also largely the same, however, it is now based on core22 and properly builds with the KDE/Qt extensions and snaps (they use qt5). I also added the non-qt dependencies (since qt should be provided by the `kf` snaps) that are listed [here](https://prismlauncher.org/wiki/development/build-instructions/) to `build-packages`.~~

This successfully builds locally and via GitHub actions (see my run [here](https://github.com/ashuntu/PrismLauncher/actions/runs/5418581824/jobs/9850814337)).

I've tested installing the built Snap on my machine (Ubuntu 23.04) and running it with `snap run prismlauncher`, logging into a Microsoft account, adding Minecraft instances, and playing on servers. Everything seems to work :)

~~If more/different Java versions are needed or wanted in the future, they can be easily added in the `stage-packages` section, which makes them available for users to select to use.~~

Also fixes #596

Edit: the Snap itself now exists here: https://github.com/ashuntu/prismlauncher-snap, and is published here: https://snapcraft.io/prismlauncher

### CODE REVIEW

**Comment by ashuntu** [comment]
https://github.com/PrismLauncher/PrismLauncher/pull/1294/commits/51d7a6289e1cf2df463ae8d7c0b08b4a61faea3c also fixes the freeze/crash described in #497, but folders (or any files, for that matter) still do not actually open. Working on a fix for it, but not sure the cause at the moment.

Edit: seems to be an issue that was fixed, but not currently available in the kde-neon extension (https://bugreports.qt.io/browse/QTBUG-83939)

**Comment by Scrumplex** [comment]
Is it possible to manage this out-of-tree?

The main reason for dropping Snap support was that no one on the team was using it. If no one on the team is comfortable maintaining it, then I don't think we should maintain it in our tree.

**Comment by ashuntu** [comment]
The `snapcraft.yaml` should not really ever change, unless a new Java version is needed (which is a 1 line change) or PrismLauncher's qt requirements change. Still, if you guys aren't comfortable having it in the main repo, I could create my own repo just for the Snap if you'd prefer.

However, Snap does need some special consideration like Flatpak does in the actual code, so those changes will likely need to stay here either way if you want to support it.

**Comment by TheKodeToad** [comment]
`DesktopServices::openDirectory` doesn't seem to work on snap

**Comment by ashuntu** [comment]
> `DesktopServices::openDirectory` doesn't seem to work on snap

Yeah, apparently there was a bug that was fixed in qt (https://bugreports.qt.io/browse/QTBUG-83939), but not in the version that the snap uses. I believe it's being worked on.

**Comment by getchoo** [comment]
> The main reason for dropping Snap support was that no one on the team was using it. If no one on the team is comfortable maintaining it, then I don't think we should maintain it in our tree

i agree with scrumplex here. none of us really have much of an interest or experience with snap, so it may not be the best idea to upstream this. we also already have two "universal" packaging solutions in tree that are more known to us (flatpak + nix).

> Still, if you guys aren't comfortable having it in the main repo, I could create my own repo just for the Snap if you'd prefer.
> However, Snap does need some special consideration like Flatpak does in the actual code, so those changes will likely need to stay here either way if you want to support it.

i think this is the best solution. i'd be more than happy to upstream any changes required for the package itself - similar to what we do with other community package

**Comment by ashuntu** [comment]
I've made a repo [here](https://github.com/ashuntu/prismlauncher-snap) for the Snap itself that checks for updates daily and updates the Snap accordingly.

As I understand it, you guys have "prismlauncher" reserved in the Snap store. Would you be open to relinquishing the name and having [Snapcrafters](https://github.com/snapcrafters) publish it instead?

**Comment by Scrumplex** [comment]
> I've made a repo [here](https://github.com/ashuntu/prismlauncher-snap) for the Snap itself that checks for updates daily and updates the Snap accordingly.
> 
> As I understand it, you guys have "prismlauncher" reserved in the Snap store. Would ou be open to relinquishing the name and having [Snapcrafters](https://github.com/snapcrafters) publish it instead?

Yes, that would be ideal! I am not sure how to delete our reserved prismlauncher Snap on the Snap Store. I can't find documentation as most documentation is about the snap CLI :D

**Comment by ashuntu** [comment]
> Yes, that would be ideal! I am not sure how to delete our reserved prismlauncher Snap on the Snap Store. I can't find documentation as most documentation is about the snap CLI :D

I can submit a dispute for the name, and once approved, then I can then publish it under my name on the Snap store until we can get it transferred to Snapcrafters (in which case it will show as published by Snapcrafters on the store, and the repo will be moved to the Snapcrafters org on Github).

Edit: I submitted a dispute for the name

**Comment by ashuntu** [comment]
The Snap is now published (unlisted for now) in the store here: https://snapcraft.io/prismlauncher. I hope it's ok that I used the project's logo and images, please let me know otherwise. I believe @Scrumplex is still on the Snap as a collaborator, so they should be able to edit the listing as well.

In https://github.com/PrismLauncher/PrismLauncher/pull/1294/commits/1467072f3dcd6ea5d2e3375ad5d69f3ee6d58af2 I removed the `snapcraft.yaml` and build workflow, so this PR is now *just* the code changes required for Snap to work.

**Review by Ryex — APPROVED** [review]

**Review by getchoo — APPROVED** [review]

**Review by Scrumplex — CHANGES_REQUESTED** [review]
Changes look good. But we need sign-offs on the last few commits for our DCO bot to pass.

You can check instructions here: https://github.com/PrismLauncher/PrismLauncher/pull/1294/checks?check_run_id=15441527533

**Review by Scrumplex — APPROVED** [review]
Thanks a lot!

**Pull request merged**
