### PR TITLE
Refactor ImgurUpload

### LINKED ISSUE #265: Screenshot upload can't be aborted
### Operating System

Windows

### Version of Prism Launcher

5.0-develop

### Version of Qt

5.15.6

### Description of bug

In an instance's screenshots tab, you can press the "Upload" button to upload a screenshot to Imgur. However, there is no way to abort the upload once you have clicked this button.

### Steps to reproduce

Go to the screenshots tab

Select an existing screenshot and click "Upload" on the right sidebar

There won't be an abort button

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
~Requires https://github.com/PrismLauncher/PrismLauncher/pull/1102~
Fixes #265

Refactors the Imgur task allowing them to be aborted by the user.

### CODE REVIEW

**Comment by Trial97** [comment]
This should be merged as only one commit

**Comment by DioEgizio** [comment]
it says "unknown error" when aborting which is not really user friendly, shouldn't it just say aborted like everything else?

**Comment by Trial97** [comment]
> it says "unknown error" when aborting which is not really user friendly, shouldn't it just say aborted like everything else?

Done

**Review by Scrumplex — APPROVED** [review]

**Comment by DioEgizio** [comment]
now if there's no internet it says it uploaded successfuly but doesn't add anything in the clipboard

**Comment by Trial97** [comment]
> now if there's no internet it says it uploaded successfuly but doesn't add anything in the clipboard

Yeah this happens because the concurrent task( the neJob base class) never fails.
For more information look at: https://github.com/PrismLauncher/PrismLauncher/pull/1364 
The correct solution is to also merge that PR but it may break some concurrent tasks( on my testing it worked as expected).
If you feel that the fact that I do not report the error there please remove this from the milestone( or consider merging the previously mentioned PR)

**Comment by Scrumplex** [comment]
> > now if there's no internet it says it uploaded successfuly but doesn't add anything in the clipboard
> 
> Yeah this happens because the concurrent task( the neJob base class) never fails. For more information look at: #1364 The correct solution is to also merge that PR but it may break some concurrent tasks( on my testing it worked as expected). If you feel that the fact that I do not report the error there please remove this from the milestone( or consider merging the previously mentioned PR)

I think this is a reasonable compromise. We can schedule a fix for 8.1 to get 8.0 out the door.

**Review by DioEgizio — APPROVED** [review]

**Pull request merged**
