### PR TITLE
Use macOS 14 in CI

### PR DESCRIPTION
**Pull request by Trial97**
edit it fixes the linkeage issue with the brew.
Q: Why did this happen? 
A: I don't know.

Q: Can this be done with fewer lines?
A: Yes, but I don't know what lines I don't

### CODE REVIEW

**Review by Ryex — APPROVED** [review]
Thanks, I hate it.
(Mac Python is a hellscape)

**Review by getchoo — CHANGES_REQUESTED** [review]
This feels like a really bad workaround, especially as this version of Python is a dependency of ECM. Have you tried using `brew link --overwrite python@3.12` as the error [says](https://github.com/PrismLauncher/PrismLauncher/actions/runs/10884246104/job/30199120074#step:11:124)?

**Review by getchoo — APPROVED** [review]

**Review by DioEgizio — CHANGES_REQUESTED** [review]
This makes the build x64 only and so not universal. This is not the solution

**Review by DioEgizio — APPROVED** [review]
nvm this is fine, idk how was the legacy one not set to x64 before

**Comment by getchoo** [comment]
> idk how was the legacy one not set to x64 before

My guess is that CMake defaulted to only x64 on older macOS versions, while on 14 it's x64 *and* aarch64. We could probably remove the explicit definition in the modern builds now because of this, but I think we've played with CI enough today :p

**Pull request merged**
