### PR TITLE
Bye bye icons

### PR DESCRIPTION
**Pull request by TheKodeToad**

### CODE REVIEW

**Comment by Ryex** [comment]
why?

**Comment by TheKodeToad** [comment]
They can be moved somewhere else; see #design

**Review by getchoo — APPROVED** [review]
i agree with the discussion from #design, these icons are very bleh! the only concern i would have is for users who really do enjoy these, and i think we should follow up on dio's suggestion of moving them to the themes repo so people can still have them

otherwise, lgtm!

**Review by DioEgizio — APPROVED** [review]
i think this should be merged when the icons are added to the themes repo though

**Comment by TheKodeToad** [comment]
I think i'll give this another go if+when #1407 is merged; I'm not meant to be creating branches on the upstream repo 0_0 and additional commits will inevitably be pushed at some point

Quote from Scrumplex

**Pull request closed without merging**
